"use strict";
/* Pulmonary cases */
CASES.push(
{
  id:'copd', subject:'Pulm', tier:1, tierWhy:'Among the most common reasons for admission.', bed:'ED 3', setting:'Emergency Dept', name:'Harold Brenner', age:68, sex:'M',
  look:{skin:'#e0b49a', hair:'#c4c4c4', sex:'M', habitus:'thin', barrel:true, cyan:.4, o2:'cannula'},
  cc:'I can’t catch my breath. It’s worse than my usual.',
  brief:'68-year-old man brought by EMS with 3 days of worsening shortness of breath. EMS started 2 L nasal cannula.',
  vitals:{hr:108, sbp:148, dbp:86, rr:26, spo2:87, temp:37.9, o2:'2 L NC'},
  hist:{
    hpi:'Three days ago I caught a cold. My breathing’s gotten worse every day since. I’m using my albuterol every hour and it barely helps.',
    cough:'I’m coughing more than usual. The phlegm went from white to thick green, and there’s a lot more of it.',
    fever:'I’ve felt a bit warm. No night sweats.',
    cp:'My chest feels tight, but there’s no real pain.',
    smoke:'Pack and a half a day since I was 17. I cut down to half a pack last year.',
    expo:'Roofer for 40 years. Retired now.',
    pmh:'COPD. They told me it was “severe” a couple of years ago. High blood pressure. I was in the hospital once last year for my breathing.',
    meds:'Tiotropium once a day, albuterol when I need it, lisinopril.',
    sleep:'When my breathing’s bad I sleep in the recliner.',
  },
  keyHist:['hpi','cough','pmh'],
  exam:{
    general:'Thin man sitting forward with his hands on his knees (tripod position). Speaking in short phrases. Pursed-lip breathing.',
    heent:'Lips slightly dusky.',
    neck:'Trachea midline. Sternocleidomastoids contract with each breath. No JVD.',
    lungR:'Diffuse expiratory wheezes with a prolonged expiratory phase. Hyperresonant. Distant breath sounds. No focal crackles.',
    lungL:'Diffuse expiratory wheezes with a prolonged expiratory phase. Hyperresonant. Distant breath sounds. No focal crackles.',
    heart:'Tachycardic, regular. Distant heart sounds.',
    hands:'Mild peripheral cyanosis. No clubbing.',
    legs:'No edema.',
  },
  keyExam:['lungR','lungL','general'],
  tests:{
    abg:{r:'On 2 L NC: pH 7.31 · PaCO2 58 · PaO2 56 · HCO3 29', y:'key', w:'Acute-on-chronic respiratory acidosis: a high HCO3 shows chronic compensation, and the low pH shows an acute rise. pH < 7.35 with PaCO2 > 45 means he needs noninvasive ventilation.'},
    cxr:{r:'Hyperinflated lungs with flattened diaphragms and a narrow heart. No consolidation, pneumothorax, or edema.', img:{type:'cxr', f:['hyper']}, y:'key', w:'Rules out pneumonia, pneumothorax, and edema as the trigger.'},
    cbc:{r:'WBC 11.8 (78% neutrophils) · Hgb 16.9 · Plt 260', y:'useful', w:'Mild leukocytosis. Secondary polycythemia from chronic hypoxemia.'},
    cmp:{r:'Na 138 · K 4.3 · Cl 95 · HCO3 30 · BUN 18 · Cr 1.0 · Glu 132', y:'useful', w:'A high bicarbonate is the metabolic compensation for chronic CO2 retention.'},
    ecg:{img:{type:'ecg', f:['stach','rad','ppulm']}, r:'Sinus tachycardia 108. Right axis deviation. Peaked P waves in II (P pulmonale). No ST changes.', y:'useful', w:'Reasonable to rule out an arrhythmia or ischemia as the trigger.'},
    bnp:{r:'BNP 85 pg/mL', y:'optional', w:'Helps exclude heart failure when the picture is mixed.'},
    sputum:{img:{type:'gram', f:['gncb','pmn']}, r:'Many PMNs. Gram-negative coccobacilli. Culture pending.', y:'optional', w:'Not routine, but reasonable in someone with frequent exacerbations.'},
    pft:{r:'Unable to complete maneuvers. Effort-limited FEV1 0.6 L.', y:'low', w:'Spirometry isn’t used to diagnose or grade an acute exacerbation. Do it when he’s stable.'},
    ctpa:{img:{type:'ct', region:'chest', contrast:true, f:['emphysema']}, r:'No pulmonary embolism. Upper-lobe centrilobular emphysema.', y:'low', w:'Nothing here suggests PE. Contrast, cost, and time without a change in management.'},
    ddimer:{r:'D-dimer 1.1 µg/mL FEU (elevated)', y:'low', w:'Nonspecific in acute illness. A positive result here only adds noise.'},
    a1at:{r:'AAT 145 mg/dL (normal)', y:'low', w:'Everyone with COPD should be screened once, but it isn’t part of acute care.'},
  },
  dx:'aecopd', dxPartial:{cap:10, a1at:10, asthma:5},
  plan:[
    {t:'Nebulized albuterol + ipratropium', k:'essential', w:'Short-acting bronchodilators are first-line.'},
    {t:'Prednisone 40 mg daily for 5 days', k:'essential', w:'Five days works as well as longer courses (REDUCE trial).'},
    {t:'Azithromycin or doxycycline', k:'essential', w:'Antibiotics are indicated when sputum purulence increases along with more dyspnea or sputum volume.'},
    {t:'BiPAP (noninvasive ventilation)', k:'essential', w:'pH < 7.35 with PaCO2 > 45 and increased work of breathing. Lowers intubation rates and mortality.'},
    {t:'Titrate oxygen to SpO2 88–92%', k:'essential', w:'Prevents worsening hypercapnia in a CO2 retainer.'},
    {t:'Non-rebreather mask, target SpO2 100%', k:'harmful', w:'Too much O2 worsens hypercapnia through V/Q mismatch and the Haldane effect.'},
    {t:'IV aminophylline', k:'harmful', w:'Methylxanthines add toxicity without benefit in exacerbations.'},
    {t:'Lorazepam for air hunger', k:'harmful', w:'Respiratory depression in a patient who is already retaining CO2.'},
    {t:'Immediate endotracheal intubation', k:'wrong', w:'Reserved for NIV failure, altered mental status, inability to protect the airway, or hemodynamic instability.'},
    {t:'Refer to pulmonary rehab after discharge', k:'good', w:'Starting rehab within weeks of discharge reduces readmissions.'},
  ],
  pearls:[
    'Cardinal symptoms: more dyspnea, more sputum, more purulent sputum. Give antibiotics when purulence is one of two or more, or when he needs ventilatory support.',
    'BiPAP for pH < 7.35 with PaCO2 > 45. Intubate for NIV failure, altered mental status, or hemodynamic instability.',
    'Target SpO2 88–92% in CO2 retainers.',
    'Long-term home O2 improves survival when PaO2 ≤ 55 or SpO2 ≤ 88%, or ≤ 59 / 89% with cor pulmonale or Hct > 55%.',
    'Clubbing is not a feature of COPD. If you see it, look for cancer, bronchiectasis, or ILD.',
  ],
  target:{min:70, cost:500},
},
{
  id:'asthma', subject:'Pulm', tier:2, tierWhy:'Common, but the normal PaCO2 trap catches many students.', bed:'ED 7', setting:'Emergency Dept', name:'Maya Okafor', age:22, sex:'F',
  look:{skin:'#7a4a32', hair:'#1b1310', sex:'F', habitus:'normal', cyan:.15, sweat:true},
  cc:'Can’t… breathe… inhaler… isn’t working.',
  brief:'22-year-old woman with known asthma and 6 hours of worsening wheeze that began at a house party. Speaking 1–2 words at a time.',
  vitals:{hr:128, sbp:128, dbp:78, rr:32, spo2:90, temp:37.0, o2:'RA'},
  decline:{by:90, to:{hr:140, sbp:112, dbp:70, rr:16, spo2:83}},
  events:[{at:40, text:'She’s now speaking single words and looks exhausted.'},{at:75, text:'She’s drowsy. Her wheezes are getting quieter: the chest is going silent.'}],
  histDefault:'She shakes her head. She can’t get the words out.',
  hist:{
    hpi:'Party… cat… smoke… six hours… ten puffs… nothing.',
    pmh:'Asthma… ICU once… breathing tube… two years ago.',
    meds:'Albuterol… only. Ran out of… the steroid one.',
    smoke:'Vape… sometimes.',
    cough:'Dry… cough.',
    fever:'No.',
  },
  keyHist:['pmh','hpi'],
  exam:{
    general:'Sitting bolt upright and diaphoretic. Speaks 1–2 words at a time. Intercostal and supraclavicular retractions.',
    heent:'No stridor. No lip or tongue swelling.',
    neck:'Sternocleidomastoid use. Trachea midline.',
    lungR:'Diffuse high-pitched expiratory wheezes. Very poor air movement.',
    lungL:'Diffuse high-pitched expiratory wheezes. Very poor air movement.',
    heart:'Tachycardic, regular. Pulsus paradoxus 22 mmHg.',
    skin:'Diaphoretic. No hives.',
  },
  keyExam:['general','lungR','lungL'],
  tests:{
    pef:{r:'PEF 140 L/min (about 30% of predicted 460)', y:'key', w:'PEF < 50% of predicted means a severe exacerbation.'},
    abg:{r:'Room air: pH 7.38 · PaCO2 43 · PaO2 62 · HCO3 25', y:'key', w:'In a tachypneic asthmatic, PaCO2 should be low. A NORMAL PaCO2 means she is tiring: impending respiratory failure.'},
    cxr:{r:'Hyperinflation. No pneumothorax. No consolidation.', img:{type:'cxr', f:['hyper'], mild:true, view:'AP'}, y:'optional', w:'Not routine, but reasonable in a severe attack to rule out pneumothorax.'},
    cbc:{r:'WBC 12.1 (6% eosinophils) · Hgb 13.4 · Plt 300', y:'low', w:'Doesn’t change acute treatment.'},
    cmp:{r:'Na 140 · K 3.4 · HCO3 24 · BUN 10 · Cr 0.7 · Glu 141', y:'low', w:'Mild hypokalemia from beta-agonists. Worth knowing, but it didn’t change the plan.'},
    ctpa:{img:{type:'ct', region:'chest', contrast:true, f:[]}, r:'No PE. Diffuse bronchial wall thickening.', y:'harmful', w:'Sending an unstable asthmatic to CT delays treatment.'},
    pft:{r:'Unable to perform.', y:'low', w:'Formal spirometry isn’t feasible here. Use peak flow instead.'},
    ecg:{img:{type:'ecg', f:['stach']}, r:'Sinus tachycardia 128.', y:'low', w:'Expected. Doesn’t change management.'},
  },
  dx:'asthma', dxPartial:{anaphylaxis:5},
  plan:[
    {t:'Continuous nebulized albuterol + ipratropium', k:'essential', w:'First-line for severe exacerbations.'},
    {t:'Systemic glucocorticoids (IV methylprednisolone or oral prednisone)', k:'essential', w:'Give within the first hour. Oral works as well as IV if she can swallow.'},
    {t:'IV magnesium sulfate 2 g', k:'essential', w:'For severe attacks that don’t respond to initial bronchodilators.'},
    {t:'Admit to ICU and prepare for intubation', k:'essential', w:'Normal PaCO2, fatigue, and a prior intubation all put her at high risk of fatal asthma.'},
    {t:'Oxygen to SpO2 93–95%', k:'good', w:'Correct hypoxemia without over-oxygenating.'},
    {t:'Lorazepam to calm her breathing', k:'harmful', w:'Sedation can tip a tiring asthmatic into respiratory arrest.'},
    {t:'Salmeterol (LABA) alone as her new controller', k:'harmful', w:'LABA monotherapy increases asthma deaths. Controllers must contain an ICS.'},
    {t:'Empiric azithromycin', k:'wrong', w:'Antibiotics only when there’s evidence of a bacterial infection.'},
    {t:'Discharge if she feels better after one nebulizer', k:'harmful', w:'Severe features and a normal PaCO2 call for admission.'},
    {t:'IM epinephrine', k:'wrong', w:'Reserved for anaphylaxis or angioedema. Neither is present.'},
  ],
  pearls:[
    'PaCO2 should be LOW in an asthma attack. Normal or high PaCO2 means fatigue → ICU.',
    'Severe: speaks in words, RR > 30, HR > 120, SpO2 < 90%, PEF ≤ 50%. Drowsiness or a silent chest is life-threatening.',
    'Add IV magnesium when SABA + ipratropium + steroids aren’t enough.',
    'Risk factors for fatal asthma: prior intubation or ICU stay, ≥ 2 hospitalizations per year, using > 2 SABA canisters a month.',
    'Discharge on an ICS-containing controller. Never LABA monotherapy.',
  ],
  target:{min:40, cost:250},
},
{
  id:'pe', subject:'Pulm', tier:2, tierWhy:'Common, and the D-dimer trap is classic.', bed:'ED 2', setting:'Emergency Dept', name:'Linda Castillo', age:54, sex:'F',
  look:{skin:'#c98e6b', hair:'#3b2418', sex:'F', habitus:'heavy', swollen:'L', o2:'cannula'},
  cc:'It hurts to take a deep breath, and I can’t get enough air.',
  brief:'54-year-old woman, 6 days after a left total knee replacement, with sudden pleuritic chest pain and dyspnea that began 3 hours ago.',
  vitals:{hr:116, sbp:124, dbp:78, rr:24, spo2:91, temp:37.6, o2:'2 L NC'},
  hist:{
    hpi:'About three hours ago I got up from the couch and felt a sharp pain on the right side of my chest. All of a sudden I couldn’t catch my breath.',
    cp:'Sharp, on the right, worse when I breathe in. Changing position doesn’t help.',
    cough:'A little dry cough. Once there was a streak of blood.',
    immob:'My left knee was replaced six days ago. I’ve mostly been on the couch. My left calf has been sore and swollen since yesterday. I thought it was from the surgery.',
    meds:'Oxycodone for pain. I was supposed to do blood-thinner shots, but I stopped after two days because they bruised.',
    pmh:'Osteoarthritis and high blood pressure.',
  },
  keyHist:['immob','cp','meds'],
  exam:{
    general:'Anxious and mildly tachypneic. Speaking full sentences.',
    lungR:'Clear. She splints slightly with deep breaths.',
    heart:'Tachycardic, regular. Loud P2. No murmur.',
    legs:'Left calf is 3.5 cm larger than the right, warm, and tender along the deep veins. The left knee incision is healing without redness.',
  },
  keyExam:['legs'],
  tests:{
    ctpa:{img:{type:'ct', region:'chest', contrast:true, f:['pe']}, r:'Filling defects in right lower lobe segmental and subsegmental arteries. RV/LV ratio 0.9 (no RV dilation).', y:'key', w:'Confirms PE. With a high pretest probability, go straight to CTPA.'},
    ddimer:{r:'D-dimer 3.8 µg/mL FEU (elevated)', y:'low', w:'Her Wells score is about 10 (high probability). A D-dimer can’t rule PE out at that level, and it’s elevated after surgery anyway.'},
    duplex:{r:'Noncompressible left popliteal and posterior tibial veins. Acute DVT.', y:'useful', w:'Confirms VTE. Especially useful when CTPA is contraindicated.'},
    cxr:{r:'Clear lungs. No pneumothorax.', img:{type:'cxr', f:[]}, y:'useful', w:'A clear film in a hypoxemic patient should raise suspicion for PE.'},
    ecg:{img:{type:'ecg', f:['stach']}, r:'Sinus tachycardia 116. No S1Q3T3. Nonspecific T-wave flattening.', y:'useful', w:'Rules out STEMI. Sinus tachycardia is the most common ECG finding in PE.'},
    trop:{r:'hs-Troponin T 9 ng/L (normal)', y:'useful', w:'Risk stratification: normal troponin and no RV strain → low-risk PE.'},
    bnp:{r:'BNP 60 pg/mL', y:'optional', w:'Another risk-stratification marker.'},
    abg:{r:'Room air: pH 7.48 · PaCO2 31 · PaO2 63 · HCO3 23', y:'optional', w:'Respiratory alkalosis with a widened A-a gradient. Supportive, not diagnostic.'},
    cmp:{r:'Na 138 · K 4.0 · BUN 12 · Cr 0.8 · Glu 104', y:'useful', w:'Check kidney function before contrast and before choosing an anticoagulant.'},
    cbc:{r:'WBC 9.1 · Hgb 11.9 · Plt 310', y:'useful', w:'Baseline counts before anticoagulation.'},
    vq:{r:'High probability for PE.', y:'low', w:'V/Q is for patients who can’t get contrast. Her kidneys are fine, and CTPA is faster.'},
    tte:{r:'Normal RV size and function. LVEF 60%.', y:'low', w:'CTPA already showed no RV strain.'},
  },
  dx:'pe', dxPartial:{},
  plan:[
    {t:'Start anticoagulation now (LMWH, or a DOAC such as apixaban)', k:'essential', w:'With high suspicion and no contraindication, start before imaging results return.'},
    {t:'Plan 3 months of anticoagulation', k:'essential', w:'Provoked by a major transient risk factor (surgery) → 3 months.'},
    {t:'Systemic thrombolysis with alteplase', k:'harmful', w:'Only for massive PE (sustained SBP < 90 or shock). She’s normotensive without RV strain.'},
    {t:'IVC filter', k:'harmful', w:'Only when anticoagulation is contraindicated or has failed.'},
    {t:'Oxygen to SpO2 ≥ 90%', k:'good', w:'Supportive care.'},
    {t:'Lifelong anticoagulation', k:'wrong', w:'Indefinite therapy is for unprovoked or recurrent VTE, or persistent risk factors like active cancer.'},
    {t:'Thrombophilia workup now', k:'wrong', w:'Not indicated for provoked VTE. Results are unreliable during acute clot and anticoagulation.'},
    {t:'Warfarin alone, no heparin overlap', k:'harmful', w:'Warfarin needs at least 5 days of heparin overlap. Early protein C depletion makes it briefly prothrombotic.'},
  ],
  pearls:[
    'Wells > 4 (PE likely): go straight to CTPA. Wells ≤ 4: D-dimer first; a negative result rules out PE.',
    'PERC rule for low-risk patients: age < 50, HR < 100, SpO2 ≥ 95%, no hemoptysis, no estrogen, no prior VTE, no unilateral leg swelling, no recent surgery or trauma.',
    'Can’t get contrast (renal failure, allergy)? Use a V/Q scan or LE duplex.',
    'Massive PE with hypotension → thrombolytics. Anticoagulation contraindicated → IVC filter.',
    'Most common ECG: sinus tachycardia. Most common ABG: respiratory alkalosis with a high A-a gradient.',
  ],
  target:{min:90, cost:1500},
},
{
  id:'tension', subject:'Pulm', tier:2, tierWhy:'Time-critical: the clock will kill him.', bed:'Trauma 1', setting:'Trauma bay', name:'Derek Liu', age:31, sex:'M',
  look:{skin:'#e7c3a5', hair:'#16110d', sex:'M', habitus:'normal', cyan:.5, sweat:true, o2:'mask', trachea:1, jvd:true, asym:'R'},
  cc:'(gasping) My chest… I can’t—',
  brief:'31-year-old restrained driver in a high-speed collision with steering-wheel impact. Getting worse in the ambulance despite a non-rebreather.',
  vitals:{hr:134, sbp:82, dbp:50, rr:34, spo2:84, temp:36.6, o2:'NRB'},
  decline:{by:16, to:{hr:152, sbp:58, dbp:30, rr:40, spo2:72}},
  arrestAt:24,
  events:[{at:8, text:'BP is now 74/44. He’s becoming confused.'},{at:16, text:'He’s barely responsive. Radial pulses are gone.'}],
  histDefault:'He can’t answer. He’s gasping for air.',
  hist:{
    hpi:'EMS: “Hit the steering wheel at about 50 mph. He was talking at the scene but has gotten steadily worse on the way in.”',
    pmh:'EMS: “No medical history, per his partner.”',
    meds:'EMS: “None that we know of.”',
  },
  keyHist:[],
  exam:{
    general:'Agitated, diaphoretic, in severe respiratory distress.',
    heent:'Lips cyanotic.',
    neck:'Trachea deviated to the LEFT. Neck veins distended.',
    lungR:'ABSENT breath sounds on the right. Hyperresonant to percussion. The right chest barely moves.',
    lungL:'Breath sounds present and clear.',
    heart:'Tachycardic. Heart sounds audible. Thready pulse.',
    skin:'Cool, mottled extremities. Seat-belt bruise across the chest.',
  },
  keyExam:['neck','lungR'],
  tests:{
    pocus:{r:'Right: no lung sliding; barcode sign on M-mode. Left: normal sliding. No pericardial effusion.', y:'useful', w:'A 30-second bedside look is acceptable, but this is a clinical diagnosis. Don’t let it delay decompression.'},
    cxr:{r:'Large right pneumothorax with complete lung collapse. Mediastinum shifted to the LEFT. Depressed right hemidiaphragm.', img:{type:'cxr', f:['ptx_R','shift_L'], view:'AP'}, y:'harmful', w:'Tension pneumothorax is a clinical diagnosis. Waiting for an X-ray in a hypotensive patient delays life-saving decompression.'},
    ct:{img:{type:'ct', region:'chest', f:['ptx'], side:'R'}, r:'Right tension pneumothorax. Two nondisplaced right rib fractures.', y:'harmful', w:'Never send an unstable patient to CT.'},
    ctpa:{img:{type:'ct', region:'chest', contrast:true, f:['ptx'], side:'R'}, r:'Right tension pneumothorax.', y:'harmful', w:'Never send an unstable patient to CT.'},
    abg:{r:'NRB: pH 7.24 · PaCO2 52 · PaO2 54 · HCO3 22', y:'low', w:'Confirms what you can already see. Time matters more.'},
    ecg:{img:{type:'ecg', f:['stach','lowvolt']}, r:'Sinus tachycardia 134. Low voltage.', y:'low', w:'Doesn’t change what he needs.'},
    cbc:{r:'WBC 13.0 · Hgb 13.9 · Plt 255', y:'low', w:'Hemoglobin is normal. Not the problem right now.'},
    lactate:{r:'Lactate 5.2 mmol/L', y:'low', w:'Shock is obvious at the bedside.'},
    tte:{r:'Small, underfilled LV. No pericardial effusion.', y:'low', w:'Not needed. Treat first.'},
  },
  dx:'tension', dxPartial:{ptx:20, hemothorax:5},
  plan:[
    {t:'Immediate needle decompression (2nd ICS midclavicular, or 4th–5th ICS anterior axillary line)', k:'essential', w:'Relieves the tension in seconds. This is the life-saving step.'},
    {t:'Chest tube after decompression', k:'essential', w:'Definitive treatment: 4th–5th ICS, just anterior to the midaxillary line.'},
    {t:'High-flow O2 and two large-bore IVs', k:'good', w:'Standard trauma resuscitation.'},
    {t:'Wait for chest X-ray confirmation before any procedure', k:'harmful', w:'He can arrest while you wait for a film.'},
    {t:'Pericardiocentesis', k:'harmful', w:'That treats tamponade, which keeps breath sounds and a midline trachea.'},
    {t:'Intubate before decompressing', k:'harmful', w:'Positive-pressure ventilation enlarges a tension pneumothorax and can cause arrest. Decompress first.'},
    {t:'Large-volume crystalloid as the main treatment for his hypotension', k:'wrong', w:'This is obstructive shock. It won’t improve until the tension is relieved.'},
  ],
  pearls:[
    'Clinical diagnosis: hypotension + absent breath sounds + trachea deviated AWAY + JVD → decompress immediately.',
    'Needle decompression at the 2nd ICS midclavicular line, or the 4th–5th ICS anterior axillary line (often better in adults with thick chest walls).',
    'Tension pneumothorax vs. tamponade: both cause JVD and hypotension. Tamponade keeps breath sounds and a midline trachea, with muffled heart sounds.',
    'Small primary spontaneous pneumothorax in a stable patient: observation and O2. Large or symptomatic: needle aspiration or chest tube.',
  ],
  target:{min:10, cost:150},
},
{
  id:'cap', subject:'Pulm', tier:1, tierWhy:'The most common infection you’ll admit.', bed:'ED 5', setting:'Emergency Dept', name:'Walter Pruitt', age:72, sex:'M',
  look:{skin:'#d9a88a', hair:'#e6e6e6', sex:'M', habitus:'normal', o2:'cannula', sweat:true},
  cc:'I’ve had a fever and this cough that won’t quit.',
  brief:'72-year-old man with 4 days of fever, productive cough, and right-sided chest pain.',
  vitals:{hr:104, sbp:132, dbp:78, rr:24, spo2:91, temp:38.9, o2:'RA'},
  hist:{
    hpi:'It started four days ago with chills and a cough. Now I’m bringing up rust-colored phlegm, and the right side hurts when I breathe.',
    cough:'Rusty-brown sputum, a lot of it.',
    fever:'Shaking chills. It was 102 at home.',
    cp:'Sharp on the right when I take a breath.',
    smoke:'Quit 20 years ago.',
    pmh:'Type 2 diabetes and high cholesterol.',
    meds:'Metformin and atorvastatin. No antibiotics or hospital stays in the last 3 months.',
    travel:'No travel. No hotels or cruises.',
    expo:'Retired teacher. No birds.',
  },
  keyHist:['cough','fever','meds'],
  exam:{
    general:'Ill-appearing and flushed. Alert and oriented ×3.',
    lungR:'Right lower posterior field: bronchial breath sounds, inspiratory crackles, dull to percussion, increased tactile fremitus, egophony (E → A).',
    heart:'Tachycardic, regular. No murmur.',
    skin:'Warm and flushed.',
  },
  keyExam:['lungR','general'],
  tests:{
    cxr:{r:'Dense right lower lobe consolidation with air bronchograms. No effusion.', img:{type:'cxr', f:['consol_RL']}, y:'key', w:'Pneumonia needs radiographic confirmation.'},
    cbc:{r:'WBC 17.2 (88% neutrophils, 9% bands) · Hgb 14.1 · Plt 288', y:'useful', w:'Leukocytosis with a left shift.'},
    cmp:{r:'Na 134 · K 4.2 · HCO3 22 · BUN 26 · Cr 1.2 · Glu 188', y:'key', w:'BUN > 19 counts toward CURB-65.'},
    bcx:{r:'Drawn. Pending (final in 48–72 h).', y:'optional', w:'2019 ATS/IDSA guidance: blood cultures are for severe CAP or MRSA/Pseudomonas risk. Many hospitals still send them.'},
    sputum:{img:{type:'gram', f:['gpdc','pmn']}, r:'Many PMNs. Lancet-shaped gram-positive diplococci.', y:'optional', w:'Consistent with Streptococcus pneumoniae. Not required for nonsevere CAP.'},
    uag:{r:'Pneumococcal antigen POSITIVE. Legionella antigen negative.', y:'optional', w:'Supports pneumococcus. Not required for nonsevere CAP.'},
    pct:{r:'Procalcitonin 2.4 ng/mL', y:'low', w:'Start empiric antibiotics for radiographic CAP no matter what the procalcitonin is.'},
    lactate:{r:'Lactate 1.6 mmol/L', y:'optional', w:'Reasonable sepsis screening. Normal.'},
    abg:{r:'Room air: pH 7.45 · PaCO2 34 · PaO2 62', y:'optional', w:'Mild hypoxemia, already obvious from the pulse oximeter.'},
    ct:{img:{type:'ct', region:'chest', f:['consol'], side:'R'}, r:'Right lower lobe consolidation. No abscess or effusion.', y:'low', w:'The X-ray already showed it. More radiation and cost.'},
    hiv:{r:'Nonreactive', y:'optional', w:'Reasonable one-time screening.'},
  },
  dx:'cap', dxPartial:{empyema:10, chestsyndrome:5},
  plan:[
    {t:'Admit to a medical ward', k:'essential', w:'CURB-65 = 2 (BUN 26, age 72) → inpatient. Consider ICU at ≥ 3 or with severe criteria.'},
    {t:'Ceftriaxone + azithromycin', k:'essential', w:'Non-ICU inpatient: a β-lactam plus a macrolide, or a respiratory fluoroquinolone alone.'},
    {t:'Oxygen to SpO2 ≥ 92%', k:'good', w:'Supportive care.'},
    {t:'Pneumococcal vaccination before discharge or at follow-up', k:'good', w:'Indicated at 65 and older.'},
    {t:'Outpatient amoxicillin, follow up in 3 days', k:'harmful', w:'CURB-65 of 2 plus hypoxemia means he needs admission.'},
    {t:'Vancomycin + piperacillin-tazobactam', k:'harmful', w:'No MRSA or Pseudomonas risk factors: no prior isolation, no IV antibiotics or hospitalization in 90 days. Needlessly broad.'},
    {t:'Systemic corticosteroids', k:'wrong', w:'Not routinely recommended for nonsevere CAP.'},
    {t:'Routine repeat chest X-ray in 6–8 weeks', k:'ok', w:'Not routine per guidelines. Consider it if symptoms persist or for lung cancer screening concerns.'},
  ],
  pearls:[
    'CURB-65: Confusion, BUN > 19, RR ≥ 30, SBP < 90 or DBP ≤ 60, age ≥ 65. Score 0–1 outpatient, 2 ward, ≥ 3 consider ICU.',
    'Healthy outpatient: amoxicillin or doxycycline. With comorbidities: amox-clav or a cephalosporin plus a macrolide or doxycycline, or a respiratory fluoroquinolone.',
    'Inpatient non-ICU: β-lactam + macrolide, or a respiratory FQ alone. ICU: β-lactam + macrolide, or β-lactam + FQ.',
    'Consolidation: dullness, increased fremitus, bronchial breath sounds, egophony. Effusion: dullness with decreased fremitus and breath sounds.',
  ],
  target:{min:60, cost:500},
},
{
  id:'sarcoid', subject:'Pulm', tier:3, tierWhy:'Uncommon, with a multi-system workup.', bed:'Clinic 4', setting:'Pulmonary clinic', name:'Danielle Brooks', age:34, sex:'F',
  look:{skin:'#6b4430', hair:'#120c09', sex:'F', habitus:'normal'},
  cc:'I’ve had a dry cough for months, and I get winded on the stairs.',
  brief:'34-year-old woman referred by her primary care doctor for 4 months of dry cough, exertional dyspnea, and an abnormal chest X-ray.',
  vitals:{hr:84, sbp:118, dbp:74, rr:18, spo2:95, temp:37.1, o2:'RA'},
  hist:{
    hpi:'It started about four months ago. A dry cough, and now I get out of breath after two flights of stairs. I used to run.',
    ros:'Last year my eyes got red and painful. The eye doctor called it uveitis and gave me drops. My ankles have been achy too.',
    fever:'I’m tired and have some low-grade temperatures. No real night sweats.',
    wt:'I’ve lost about 8 pounds without trying.',
    expo:'I teach middle school. No birds, hot tubs, or mold.',
    travel:'Born and raised in Ohio. No TB contacts and no travel.',
    pmh:'I passed a kidney stone last year.',
    meds:'Just a multivitamin with vitamin D.',
  },
  keyHist:['ros','pmh'],
  exam:{
    general:'Well-appearing. Talking comfortably.',
    heent:'No active eye redness today.',
    neck:'A few small, nontender, mobile cervical nodes.',
    lungR:'A few fine crackles in the mid-lung field. Otherwise clear.',
    lungL:'A few fine crackles in the mid-lung field. Otherwise clear.',
    skin:'Two firm, painless, violaceous papules on the nose.',
  },
  keyExam:['skin'],
  tests:{
    cxr:{r:'Bilateral hilar lymphadenopathy with mid-zone reticulonodular opacities (Scadding stage II).', img:{type:'cxr', f:['hilar','retic_mid']}, y:'key', w:'Bilateral hilar adenopathy is the classic finding.'},
    ct:{img:{type:'ct', region:'chest', f:['lad','micronod']}, r:'Symmetric bilateral hilar and mediastinal lymphadenopathy. Perilymphatic micronodules along the bronchovascular bundles, upper/mid-zone predominant.', y:'useful', w:'Defines the nodal stations to biopsy.'},
    hrct:{img:{type:'ct', region:'chest', f:['lad','micronod']}, r:'Perilymphatic and subpleural micronodules, upper/mid-zone predominant. Bulky bilateral hilar nodes. No fibrosis.', y:'useful', w:'Characterizes the parenchymal pattern.'},
    cmp:{r:'Na 140 · K 4.0 · BUN 14 · Cr 0.9 · Ca 11.2 · Alb 4.0 · ALP 160', y:'key', w:'Hypercalcemia: granuloma macrophages make 1α-hydroxylase, which raises calcitriol.'},
    ace:{r:'ACE 98 U/L (elevated)', y:'optional', w:'Supportive, but neither sensitive nor specific. It can’t confirm or exclude sarcoidosis.'},
    pft:{r:'FEV1/FVC 0.84 · TLC 72% · DLCO 64%', y:'key', w:'Restrictive pattern with a low DLCO. Helps decide whether to treat.'},
    bronch:{r:'EBUS-guided needle aspiration of the subcarinal node: NONCASEATING granulomas. AFB and fungal stains negative.', y:'key', w:'Most patients need a tissue diagnosis. Löfgren syndrome is the exception.'},
    ecg:{img:{type:'ecg', f:['nsr']}, r:'Normal sinus rhythm 82. PR 180 ms. No block.', y:'useful', w:'Everyone with sarcoidosis gets screened for cardiac involvement (heart block, arrhythmia).'},
    igra:{r:'Negative', y:'optional', w:'Reasonable before steroids, and to exclude TB.'},
    cbc:{r:'WBC 4.1 (lymphopenia) · Hgb 12.6 · Plt 230', y:'optional', w:'Lymphopenia is common in sarcoidosis.'},
    afb:{r:'AFB smears negative. TB NAAT: not detected.', y:'optional', w:'Reasonable to exclude TB, a granulomatous mimic.'},
  },
  dx:'sarcoid', dxPartial:{lymphoma:5, tb:0},
  plan:[
    {t:'Oral glucocorticoids (prednisone)', k:'essential', w:'Treat: she has symptomatic lung disease, impaired PFTs, and hypercalcemia.'},
    {t:'Ophthalmology slit-lamp exam', k:'essential', w:'Yearly eye exams for everyone with sarcoidosis, and she’s already had uveitis.'},
    {t:'Baseline ECG and cardiac screening', k:'good', w:'Cardiac sarcoid causes heart block and sudden death.'},
    {t:'Stop vitamin D supplements and avoid excess sun', k:'good', w:'Both worsen hypercalcemia from extra calcitriol.'},
    {t:'Start 4-drug anti-TB therapy', k:'harmful', w:'Noncaseating granulomas, negative AFB testing. Not TB.'},
    {t:'Mediastinoscopy with complete lymph-node resection', k:'harmful', w:'Diagnosis is already made from minimally invasive EBUS sampling.'},
    {t:'Observation only, recheck in a year', k:'wrong', w:'Asymptomatic stage I disease gets observed. She’s symptomatic, with impaired PFTs and hypercalcemia.'},
    {t:'Methotrexate as first-line therapy', k:'wrong', w:'A steroid-sparing second-line drug.'},
  ],
  pearls:[
    'Classic: young Black woman, bilateral hilar adenopathy, noncaseating granulomas. Look for hypercalcemia, uveitis, erythema nodosum, lupus pernio, and heart block.',
    'Löfgren syndrome (erythema nodosum + bilateral hilar adenopathy + arthritis ± fever) resolves on its own. NSAIDs, no biopsy needed.',
    'Treat with steroids for symptoms, falling PFTs, or extrapulmonary disease (eye, heart, CNS, hypercalcemia).',
    'Mechanism of hypercalcemia: granuloma 1α-hydroxylase → more 1,25-(OH)2 vitamin D. PTH is suppressed.',
  ],
  target:{min:330, cost:5500},
},
{
  id:'ipf', subject:'Pulm', tier:3, tierWhy:'Rare, and steroids are a trap.', bed:'Clinic 2', setting:'Pulmonary clinic', name:'Robert Haines', age:70, sex:'M',
  look:{skin:'#e2b9a0', hair:'#d0d0d0', sex:'M', habitus:'normal', clubbing:true, cyan:.15},
  cc:'I can’t keep up anymore. Even walking to the mailbox winds me.',
  brief:'70-year-old man with 18 months of slowly progressive exertional dyspnea and a dry cough.',
  vitals:{hr:88, sbp:136, dbp:82, rr:20, spo2:92, temp:36.8, o2:'RA'},
  hist:{
    hpi:'It came on gradually over a year and a half. A dry, hacking cough that never goes away.',
    cough:'Dry. No blood.',
    smoke:'A pack a day for 30 years. Quit 15 years ago.',
    expo:'Accountant my whole career. No asbestos, no birds, no farming, no hot tub.',
    meds:'Lisinopril and omeprazole for reflux. Never been on amiodarone, methotrexate, or nitrofurantoin.',
    ros:'No joint pain, rashes, trouble swallowing, or color changes in my fingers.',
    pmh:'Reflux and high blood pressure.',
    fhx:'My older brother had some kind of lung-scarring disease.',
    wt:'Lost a few pounds.',
  },
  keyHist:['expo','meds','ros'],
  exam:{
    general:'Comfortable at rest. Short of breath after talking for a while.',
    lungR:'Fine, dry “Velcro” crackles at the base at end-inspiration.',
    lungL:'Fine, dry “Velcro” crackles at the base at end-inspiration.',
    hands:'Digital clubbing: the angle at the nail bed is gone.',
    heart:'Regular. Normal S2.',
  },
  keyExam:['lungR','lungL','hands'],
  tests:{
    hrct:{img:{type:'ct', region:'chest', f:['honey']}, r:'Subpleural, basal-predominant reticulation with HONEYCOMBING and traction bronchiectasis. No ground glass, micronodules, or air trapping. Usual interstitial pneumonia (UIP) pattern.', y:'key', w:'A definite UIP pattern in the right clinical setting is diagnostic. No biopsy needed.'},
    ct:{img:{type:'ct', region:'chest', f:['honey']}, r:'Basal reticular opacities suggest fibrosis. Thick slices limit characterization; HRCT recommended.', y:'useful', w:'Points to fibrosis, but HRCT is the right test.'},
    cxr:{r:'Low lung volumes with bibasilar reticular opacities.', img:{type:'cxr', f:['retic_low','lowvol']}, y:'useful', w:'Suggestive, but you’ll need HRCT.'},
    pft:{r:'FEV1/FVC 0.86 · TLC 61% · DLCO 42%', y:'key', w:'Restrictive pattern with a low DLCO.'},
    auto:{r:'ANA, RF, anti-CCP, anti-Scl-70, anti-Jo-1: all negative', y:'key', w:'Rules out connective tissue disease–associated ILD.'},
    walk:{r:'Walked 310 m. SpO2 nadir 85%.', y:'useful', w:'Documents exertional desaturation, which qualifies him for ambulatory O2.'},
    bronch:{r:'BAL nonspecific. Transbronchial biopsy shows fibrosis; nondiagnostic.', y:'harmful', w:'With a definite UIP pattern on HRCT, biopsy adds risk (including acute exacerbation) without changing the diagnosis.'},
    tte:{r:'LVEF 60%. PASP 38 mmHg. Normal RV.', y:'optional', w:'Reasonable to screen for pulmonary hypertension.'},
    bnp:{r:'BNP 70 pg/mL', y:'low', w:'Heart failure isn’t in the picture.'},
  },
  dx:'ipf', dxPartial:{hp:10, asbestosis:10},
  plan:[
    {t:'Antifibrotic therapy: nintedanib or pirfenidone', k:'essential', w:'Slows the decline in FVC.'},
    {t:'Supplemental O2 with exertion', k:'essential', w:'He desaturates to 85% when walking.'},
    {t:'Refer for lung transplant evaluation', k:'essential', w:'The only treatment that extends survival. Refer early.'},
    {t:'Pulmonary rehabilitation', k:'good', w:'Improves exercise capacity and quality of life.'},
    {t:'Vaccinations (influenza, pneumococcal, COVID-19, RSV)', k:'good', w:'Respiratory infections can trigger acute exacerbations.'},
    {t:'High-dose prednisone', k:'harmful', w:'Prednisone + azathioprine + NAC increased deaths in IPF (PANTHER-IPF).'},
    {t:'Cyclophosphamide', k:'harmful', w:'No benefit in IPF. Toxic.'},
    {t:'Surgical lung biopsy', k:'harmful', w:'Not needed with a definite UIP pattern, and it can trigger an acute exacerbation.'},
  ],
  pearls:[
    'IPF: age > 60, insidious dyspnea on exertion, dry cough, Velcro crackles, clubbing. HRCT: basal, subpleural reticulation with honeycombing (UIP).',
    'PFTs: restrictive (low TLC, normal-to-high FEV1/FVC) with a low DLCO.',
    'Rule out mimics first: exposures (HP, asbestosis), drugs (amiodarone, methotrexate, nitrofurantoin, bleomycin), and connective tissue disease.',
    'Upper-lobe fibrosis: HP, sarcoid, silicosis, coal workers’ disease, TB. Lower-lobe: IPF, asbestosis, CTD, drugs.',
    'Treat with nintedanib or pirfenidone. Steroids are harmful. Transplant is the only cure.',
  ],
  target:{min:200, cost:1800},
},
{
  id:'sclc', subject:'Pulm', tier:2, tierWhy:'Two problems at once: a cancer and its paraneoplastic syndrome.', bed:'Ward 6B', setting:'Medicine ward', name:'Frank Doyle', age:63, sex:'M',
  look:{skin:'#dbb196', hair:'#8a8a8a', sex:'M', habitus:'thin'},
  cc:'My wife says I’ve been confused, and I’ve lost a lot of weight.',
  brief:'63-year-old man admitted for a week of mild confusion and fatigue. He’s also had a cough for 2 months.',
  vitals:{hr:92, sbp:128, dbp:76, rr:18, spo2:94, temp:36.9, o2:'RA'},
  hist:{
    hpi:'I’ve had a cough for two months that won’t go away. This week I’ve felt foggy and tired, and I’ve had headaches.',
    cough:'Dry cough. Twice I’ve coughed up streaks of blood.',
    smoke:'Two packs a day for 45 years. Still smoking.',
    wt:'Twenty pounds in 3 months without trying.',
    fever:'No fevers. Some night sweats.',
    meds:'Nothing. No water pills.',
    pmh:'Nothing. I haven’t seen a doctor in years.',
  },
  keyHist:['smoke','wt'],
  exam:{
    general:'Thin, with temporal wasting. Oriented to person and place but not the date. No focal deficits.',
    heent:'Moist mucous membranes.',
    neck:'No JVD. Firm 1.5 cm right supraclavicular node.',
    lungR:'Decreased breath sounds and a localized wheeze over the right upper chest.',
    legs:'No edema.',
    skin:'Normal skin turgor.',
  },
  keyExam:['heent','legs','neck'],
  tests:{
    cmp:{r:'Na 121 · K 4.0 · Cl 88 · HCO3 24 · BUN 7 · Cr 0.7 · Glu 96 · Ca 9.1', y:'key', w:'Significant hyponatremia explains the confusion.'},
    osm:{r:'Serum osm 252 · Urine osm 540 · Urine Na 58', y:'key', w:'Hypotonic hyponatremia with inappropriately concentrated urine and a high urine Na in a euvolemic patient = SIADH.'},
    endo:{r:'TSH 1.8 mIU/L · AM cortisol 16 µg/dL', y:'useful', w:'Rule out hypothyroidism and adrenal insufficiency before you call it SIADH.'},
    cxr:{r:'Right hilar mass with mediastinal widening.', img:{type:'cxr', f:['mass_R']}, y:'key', w:'A central mass in a heavy smoker.'},
    ct:{img:{type:'ct', region:'chest', f:['mass','lad']}, r:'5 cm central right hilar mass invading the mediastinum. Bulky mediastinal lymphadenopathy. Several small liver lesions.', y:'key', w:'Central location and early spread are typical of small cell carcinoma.'},
    bronch:{r:'Endobronchial biopsy: small round blue cells with scant cytoplasm, nuclear molding, and crush artifact. Synaptophysin and chromogranin positive. SMALL CELL CARCINOMA.', y:'key', w:'Tissue diagnosis.'},
    cbc:{r:'WBC 8.2 · Hgb 12.4 · Plt 330', y:'optional', w:'Mild anemia of chronic disease.'},
    ctpa:{img:{type:'ct', region:'chest', contrast:true, f:['mass']}, r:'No PE. Right hilar mass.', y:'low', w:'Not the question here.'},
    ddimer:{r:'D-dimer 1.4 µg/mL FEU (elevated)', y:'low', w:'Nonspecific in cancer.'},
    tte:{r:'Normal.', y:'low', w:'Doesn’t help.'},
  },
  dx:'sclc', dxPartial:{sqcc:15, adeno:10},
  plan:[
    {t:'Fluid restriction (< 800 mL–1 L/day)', k:'essential', w:'First-line for chronic SIADH with mild-to-moderate symptoms.'},
    {t:'Raise sodium by no more than 8 mEq/L in 24 h', k:'essential', w:'Faster correction risks osmotic demyelination.'},
    {t:'Staging with PET-CT and brain MRI', k:'essential', w:'SCLC spreads early, especially to the brain.'},
    {t:'Platinum + etoposide chemotherapy (± immunotherapy) with oncology', k:'essential', w:'Standard first-line treatment for SCLC.'},
    {t:'Smoking cessation counseling', k:'good', w:'Always.'},
    {t:'Surgical lobectomy', k:'harmful', w:'SCLC has almost always spread at diagnosis, and he has liver lesions. Not resectable.'},
    {t:'3% saline to bring sodium to normal today', k:'harmful', w:'Hypertonic saline is for severe symptoms (seizures, coma), and even then the limit is 8 mEq/L per day.'},
    {t:'2 L normal saline bolus', k:'harmful', w:'Can worsen hyponatremia in SIADH: the kidney keeps the water and excretes the salt.'},
    {t:'Salt tablets ± loop diuretic if fluid restriction fails', k:'ok', w:'Reasonable second-line. Tolvaptan is another option.'},
  ],
  pearls:[
    'Small cell: central, smokers, neuroendocrine. Paraneoplastic: SIADH, ectopic ACTH (Cushing), Lambert-Eaton (anti-VGCC).',
    'Squamous cell: central, cavitates, hypercalcemia (PTHrP). Adenocarcinoma: peripheral, most common in nonsmokers and women.',
    'SIADH: euvolemic hypotonic hyponatremia, urine osm > 100, urine Na > 40. Rule out hypothyroidism and adrenal insufficiency.',
    'Correct chronic hyponatremia by ≤ 8 mEq/L per 24 h. Use 3% saline only for severe symptoms.',
  ],
  target:{min:330, cost:5000},
},
{
  id:'empyema', subject:'Pulm', tier:2, tierWhy:'A common complication that needs a procedure.', bed:'Ward 4A', setting:'Medicine ward', name:'Teresa Vance', age:58, sex:'F',
  look:{skin:'#c48f6e', hair:'#5a3a22', sex:'F', habitus:'normal', o2:'cannula', sweat:true},
  cc:'I’m still having fevers, and now my left side hurts.',
  brief:'58-year-old woman on day 4 of IV ceftriaxone + azithromycin for left lower lobe pneumonia. She’s still spiking fevers.',
  vitals:{hr:106, sbp:118, dbp:70, rr:22, spo2:93, temp:38.7, o2:'2 L NC'},
  hist:{
    hpi:'I felt a little better on day two, but the fevers came back yesterday. Now there’s a deep ache on the left when I breathe.',
    cp:'Left-sided and sharp. Worse with a deep breath.',
    fever:'Spiking every afternoon. Drenching sweats last night.',
    cough:'Still coughing up yellow phlegm.',
    pmh:'Type 2 diabetes. I drink 5 or 6 beers a day.',
    meds:'Metformin at home. Here they’ve been giving me ceftriaxone and azithromycin.',
    smoke:'Half a pack a day.',
  },
  keyHist:['hpi'],
  exam:{
    general:'Ill-appearing and febrile.',
    lungL:'Lower third: dull to percussion, decreased tactile fremitus, decreased breath sounds. Egophony at the upper edge of the dullness.',
    heart:'Tachycardic, regular.',
  },
  keyExam:['lungL'],
  tests:{
    cxr:{r:'Moderate left pleural effusion with a meniscus, plus left lower lobe opacity.', img:{type:'cxr', f:['eff_L','consol_LL']}, y:'key', w:'Shows the effusion behind her failure to improve.'},
    pocus:{r:'Moderate left pleural effusion with internal septations and debris.', y:'key', w:'Septations suggest a complicated effusion. Ultrasound also guides the needle.'},
    thora:{r:'Cloudy yellow fluid. pH 7.05 · Glucose 38 mg/dL · LDH 1,450 U/L · Protein 4.8 g/dL. Gram stain: gram-positive cocci in chains.\nSerum: LDH 210 U/L (ULN 220) · Protein 6.5 g/dL', y:'key', w:'Exudate by Light’s criteria (protein ratio 0.74; LDH ratio 6.9). pH < 7.2, glucose < 60, and a positive Gram stain → complicated effusion → drain it.'},
    cbc:{r:'WBC 18.9 (90% neutrophils) · Hgb 11.8 · Plt 410', y:'useful', w:'Persistent leukocytosis despite antibiotics.'},
    bcx:{r:'Gram-positive cocci in chains in 1 of 2 bottles.', y:'optional', w:'Reasonable in persistent fever. Fits a streptococcal infection.'},
    ct:{img:{type:'ct', region:'chest', f:['loculated'], side:'L'}, r:'Loculated left pleural collection with enhancing, separated pleural layers (split pleura sign).', y:'optional', w:'Helps map loculations when ultrasound is limited.'},
    cmp:{r:'Na 135 · K 3.9 · BUN 12 · Cr 0.9 · Glu 182 · Alb 2.9', y:'optional', w:'Hyperglycemia from infection.'},
    pct:{r:'Procalcitonin 3.1 ng/mL', y:'low', w:'You already know she’s infected.'},
    bnp:{r:'BNP 50 pg/mL', y:'low', w:'A transudate workup isn’t needed here.'},
    bronch:{r:'Purulent secretions in the left lower lobe. No endobronchial lesion.', y:'harmful', w:'Invasive, and it doesn’t address the pleural space.'},
  },
  dx:'empyema', dxPartial:{cap:10, maligeff:0},
  plan:[
    {t:'Chest tube drainage', k:'essential', w:'Complicated effusions and empyema need drainage.'},
    {t:'Continue IV antibiotics, broadened to cover anaerobes (e.g., ampicillin-sulbactam)', k:'essential', w:'Pleural infections often involve anaerobes, especially with heavy alcohol use.'},
    {t:'Intrapleural tPA + DNase if drainage is poor', k:'good', w:'Breaks up loculations (MIST-2).'},
    {t:'Surgical consult (VATS decortication) if drainage fails', k:'good', w:'The next step when tube drainage fails.'},
    {t:'Change antibiotics only and recheck in 48 h', k:'harmful', w:'Antibiotics alone fail. A complicated effusion needs drainage.'},
    {t:'IV furosemide to mobilize the fluid', k:'wrong', w:'This is infected exudate, not volume overload.'},
    {t:'Repeat thoracentesis in 1 week', k:'wrong', w:'Delays source control. She needs a tube now.'},
    {t:'Glucose control and alcohol-withdrawal monitoring', k:'good', w:'Good inpatient care for this patient.'},
  ],
  pearls:[
    'Light’s criteria (exudate if ANY): protein ratio > 0.5, LDH ratio > 0.6, pleural LDH > 2/3 of the serum upper limit of normal.',
    'Drain when: pH < 7.2, glucose < 60, positive Gram stain or culture, frank pus, loculations, or a large effusion.',
    'Not improving after 48–72 h of appropriate antibiotics for pneumonia → look for an effusion or empyema.',
    'Transudates: heart failure (most common), cirrhosis, nephrotic syndrome. A serum-minus-pleural protein gradient > 3.1 g/dL confirms a transudate even after diuresis.',
  ],
  target:{min:90, cost:1000},
},
{
  id:'tb', subject:'ID', tier:2, tierWhy:'Less common in the US, with public health steps to remember.', bed:'ED 9', setting:'Emergency Dept', name:'Joel Ramos', age:45, sex:'M',
  look:{skin:'#b98a62', hair:'#141010', sex:'M', habitus:'thin'},
  cc:'I’ve been coughing for two months, and this morning there was blood.',
  brief:'45-year-old man who moved from the Philippines 3 years ago. Two months of cough, night sweats, and weight loss. Small-volume hemoptysis this morning.',
  vitals:{hr:98, sbp:122, dbp:76, rr:18, spo2:96, temp:38.1, o2:'RA'},
  hist:{
    hpi:'Two months of cough. At first it was dry. Now there’s yellow phlegm, and today some streaks of blood.',
    cough:'Yellow sputum, with blood streaks this morning.',
    fever:'Fevers in the evening. I wake up soaked and have to change my shirt.',
    wt:'I’ve lost about 15 pounds.',
    travel:'I moved here from Manila three years ago. My uncle back home was treated for TB. I live with my wife and two kids.',
    smoke:'Only socially.',
    pmh:'Nothing. I’ve never been tested for HIV.',
    expo:'I work in a warehouse.',
  },
  keyHist:['travel','fever','wt'],
  exam:{
    general:'Thin, coughing frequently.',
    lungR:'Hollow (amphoric) breath sounds and crackles over the right apex, posteriorly.',
  },
  keyExam:['lungR'],
  tests:{
    cxr:{r:'Thick-walled cavity in the right upper lobe with surrounding patchy consolidation.', img:{type:'cxr', f:['cavity_RU','consol_RU']}, y:'key', w:'Upper-lobe cavitation is classic for reactivation TB.'},
    afb:{r:'AFB smear 2+ POSITIVE. TB NAAT: M. tuberculosis DETECTED, no rifampin-resistance mutation. Culture pending (2–6 weeks).', y:'key', w:'Diagnoses active pulmonary TB and screens for rifampin resistance.'},
    igra:{r:'QuantiFERON-TB: POSITIVE', y:'low', w:'IGRA and TST detect infection, not active disease. They can’t tell latent from active TB, and they’re negative in up to 20% of active cases.'},
    hiv:{r:'Nonreactive', y:'key', w:'Everyone with TB should be tested for HIV.'},
    cmp:{r:'Na 137 · K 4.1 · Cr 0.8 · AST 24 · ALT 21 · T bili 0.6', y:'useful', w:'Baseline liver tests before RIPE.'},
    cbc:{r:'WBC 9.8 · Hgb 12.2 · Plt 390', y:'optional', w:'Mild anemia of chronic disease.'},
    ct:{img:{type:'ct', region:'chest', f:['cavity']}, r:'Thick-walled right upper lobe cavity with tree-in-bud nodules.', y:'low', w:'The X-ray and sputum already make the diagnosis.'},
    sputum:{r:'Mixed oropharyngeal flora.', y:'optional', w:'A routine culture doesn’t grow mycobacteria.'},
    bronch:{r:'BAL: AFB positive.', y:'harmful', w:'Bronchoscopy creates aerosols, and sputum was enough here.'},
    ctpa:{img:{type:'ct', region:'chest', contrast:true, f:['cavity']}, r:'No PE. Right upper lobe cavity.', y:'low', w:'Hemoptysis plus a cavity isn’t a PE story.'},
  },
  dx:'tb', dxPartial:{adeno:0, sqcc:0},
  plan:[
    {t:'Airborne isolation in a negative-pressure room; N95 for staff', k:'essential', w:'Start as soon as TB is suspected, before results are back.'},
    {t:'RIPE: rifampin, isoniazid, pyrazinamide, ethambutol (+ pyridoxine)', k:'essential', w:'Standard initial four-drug regimen.'},
    {t:'Report to the health department and test household contacts', k:'essential', w:'TB is reportable. His wife and children need screening.'},
    {t:'Directly observed therapy', k:'good', w:'Improves adherence and prevents resistance.'},
    {t:'Baseline LFTs and visual acuity / color-vision testing', k:'good', w:'Monitors hepatotoxicity and ethambutol optic neuritis.'},
    {t:'Levofloxacin for presumed bacterial pneumonia', k:'harmful', w:'Fluoroquinolones partly treat TB, delay the diagnosis, and breed resistance.'},
    {t:'Isoniazid alone for 9 months', k:'harmful', w:'That’s a latent TB regimen. Monotherapy for active disease selects for resistance.'},
    {t:'Droplet precautions (surgical mask) only', k:'wrong', w:'TB is airborne. It needs a negative-pressure room and N95s.'},
  ],
  pearls:[
    'Reactivation TB: upper-lobe cavities (apical/posterior segments). Primary TB: lower/middle lobe plus hilar nodes (Ghon complex).',
    'Active TB: three sputum AFB smears and cultures plus NAAT. IGRA and TST only detect infection.',
    'RIPE for 2 months, then isoniazid + rifampin for 4 more (6 months total). Add pyridoxine with isoniazid.',
    'Toxicities: INH → neuropathy, hepatitis. Rifampin → orange fluids, CYP induction. PZA → hyperuricemia, hepatitis. Ethambutol → optic neuritis (red-green color loss).',
    'Latent TB (positive IGRA, normal CXR): 4 months of rifampin, 3 months of weekly INH + rifapentine, or 6–9 months of INH.',
  ],
  target:{min:100, cost:600},
},
{
  id:'osa', subject:'Pulm', tier:1, tierWhy:'Very common outpatient diagnosis.', bed:'Clinic 1', setting:'Primary care clinic', name:'Gary Whitfield', age:52, sex:'M',
  look:{skin:'#e5bfa6', hair:'#6b4a2f', sex:'M', habitus:'obese'},
  cc:'My wife made me come in. She says I stop breathing at night.',
  brief:'52-year-old man with loud snoring, witnessed apneas, and daytime sleepiness. BMI 38.',
  vitals:{hr:78, sbp:152, dbp:94, rr:14, spo2:95, temp:36.8, o2:'RA'},
  hist:{
    hpi:'I’ve been tired all the time for a couple of years, even after 8 hours in bed. I wake up with headaches.',
    sleep:'I snore like a freight train. My wife says I stop breathing and then gasp. I’ve dozed off at red lights and in meetings.',
    pmh:'High blood pressure that’s hard to control, even on three pills. Prediabetes.',
    meds:'Amlodipine, lisinopril, and hydrochlorothiazide. Sometimes zolpidem to sleep. Two or three beers most nights to help me unwind.',
    smoke:'Never.',
    cough:'No cough.',
  },
  keyHist:['sleep','hpi','pmh'],
  exam:{
    general:'Obese, BMI 38. Dozed off briefly in the waiting room.',
    heent:'Crowded oropharynx (Mallampati IV), large tongue, retrognathia.',
    neck:'Neck circumference 19 inches (48 cm). No JVD.',
    legs:'Trace bilateral ankle edema.',
  },
  keyExam:['heent','neck'],
  tests:{
    psg:{r:'AHI 38 events/h (severe OSA). Obstructive apneas with an O2 nadir of 79%. No central apneas.', y:'key', w:'The gold standard for diagnosing OSA.'},
    hsat:{r:'AHI 35 events/h. O2 nadir 80%.', y:'key', w:'Acceptable for uncomplicated patients with a high pretest probability.'},
    abg:{r:'Room air: pH 7.40 · PaCO2 41 · PaO2 80 · HCO3 25', y:'optional', w:'A normal daytime PaCO2 rules out obesity hypoventilation (PaCO2 > 45).'},
    cmp:{r:'Na 141 · K 3.9 · HCO3 25 · Cr 1.0 · Glu 112', y:'optional', w:'HCO3 < 27 makes obesity hypoventilation unlikely.'},
    endo:{r:'TSH 2.1 mIU/L · AM cortisol 14 µg/dL', y:'optional', w:'Hypothyroidism can cause fatigue and worsen OSA.'},
    cbc:{r:'WBC 7.0 · Hgb 15.8 · Plt 250', y:'optional', w:'Normal.'},
    ecg:{img:{type:'ecg', f:['nsr','lvh']}, r:'Normal sinus rhythm 78. Left ventricular hypertrophy by voltage.', y:'optional', w:'LVH from long-standing hypertension.'},
    tte:{r:'Mild concentric LVH. LVEF 60%. PASP 32 mmHg.', y:'low', w:'Doesn’t change the sleep workup.'},
    pft:{r:'Mildly reduced FVC from body habitus. Otherwise normal.', y:'low', w:'Not part of an OSA workup.'},
    cxr:{r:'No acute process.', img:{type:'cxr', f:[]}, y:'low', w:'Not indicated.'},
  },
  dx:'osa', dxPartial:{ohs:15}, keyOneOf:[['psg','hsat']],
  plan:[
    {t:'CPAP every night', k:'essential', w:'First-line treatment for moderate-to-severe OSA.'},
    {t:'Weight-loss program (diet and exercise; consider tirzepatide)', k:'essential', w:'Weight loss lowers the AHI. Tirzepatide is FDA-approved for OSA with obesity.'},
    {t:'Stop alcohol and sedatives at bedtime', k:'good', w:'Both relax upper-airway muscles and worsen apneas.'},
    {t:'Counsel against drowsy driving', k:'good', w:'He’s dozing at red lights.'},
    {t:'Zolpidem nightly for better sleep', k:'harmful', w:'Sedative-hypnotics worsen untreated OSA.'},
    {t:'Uvulopalatopharyngoplasty as first-line', k:'wrong', w:'Surgery is for patients who can’t tolerate CPAP.'},
    {t:'Nighttime home oxygen instead of CPAP', k:'wrong', w:'Doesn’t fix the airway obstruction.'},
    {t:'Modafinil instead of CPAP', k:'wrong', w:'Only for residual sleepiness despite adequate CPAP use.'},
  ],
  pearls:[
    'Diagnose with in-lab polysomnography, or a home sleep test for uncomplicated patients. AHI ≥ 5 with symptoms or ≥ 15 alone = OSA. ≥ 30 = severe.',
    'OSA is a common cause of resistant hypertension, atrial fibrillation, and pulmonary hypertension.',
    'First line: CPAP plus weight loss. Avoid alcohol and sedatives.',
    'Obesity hypoventilation: BMI ≥ 30 plus daytime PaCO2 > 45 with no other cause. A serum HCO3 < 27 makes it unlikely.',
  ],
  target:{min:540, cost:1800},
},
{
  id:'ards', subject:'Pulm', tier:3, tierWhy:'ICU-level physiology with specific ventilator rules.', bed:'Step-down 3', setting:'Rapid response', name:'Angela Moreno', age:45, sex:'F',
  look:{skin:'#c99777', hair:'#2a1a12', sex:'F', habitus:'heavy', cyan:.4, sweat:true, o2:'mask'},
  cc:'Nurse: “Her oxygen keeps dropping.”',
  brief:'45-year-old woman admitted 36 hours ago with severe gallstone pancreatitis, given 6 L of IV fluid. SpO2 fell to 86% on 6 L NC; now on a non-rebreather.',
  vitals:{hr:122, sbp:104, dbp:62, rr:34, spo2:88, temp:38.3, o2:'NRB'},
  decline:{by:120, to:{hr:134, sbp:96, dbp:56, rr:38, spo2:80}},
  events:[{at:45, text:'SpO2 is 85% on the non-rebreather. She’s tiring.'}],
  histDefault:'She’s too short of breath to say more than a few words.',
  hist:{
    hpi:'Nurse: “She came in yesterday with severe pancreatitis. Lipase over 3,000. Fluids running wide open. This morning she started breathing fast and her sats dropped.”',
    pmh:'Nurse: “Gallstones and obesity. No heart or lung disease. Her echo last year was normal.”',
    meds:'Nurse: “IV fluids, hydromorphone, ondansetron.”',
    cough:'A little dry cough.',
  },
  keyHist:['hpi','pmh'],
  exam:{
    general:'Tachypneic, using accessory muscles, speaking in short phrases.',
    neck:'No JVD.',
    lungR:'Diffuse inspiratory crackles.',
    lungL:'Diffuse inspiratory crackles.',
    heart:'Tachycardic. No S3. No murmur.',
    abd:'Epigastric tenderness. Distended, with hypoactive bowel sounds.',
    legs:'No edema.',
  },
  keyExam:['neck','heart','lungR','lungL'],
  tests:{
    abg:{r:'Non-rebreather (FiO2 ≈ 0.8): pH 7.46 · PaCO2 32 · PaO2 58 · HCO3 22\nP/F ratio ≈ 72', y:'key', w:'P/F ≤ 100 on high FiO2 = severe ARDS (Berlin).'},
    cxr:{r:'Bilateral diffuse patchy alveolar opacities. Normal heart size. No effusions.', img:{type:'cxr', f:['diffuse'], view:'AP'}, y:'key', w:'Bilateral opacities not explained by effusion or collapse.'},
    bnp:{r:'BNP 70 pg/mL', y:'useful', w:'A low BNP argues against cardiogenic edema.'},
    tte:{r:'LVEF 60%. Normal valves. No diastolic dysfunction. Normal RV.', y:'useful', w:'Rules out cardiogenic pulmonary edema.'},
    pocus:{r:'Diffuse bilateral B-lines with spared areas and an irregular pleural line. Normal LV. Small, collapsing IVC.', y:'useful', w:'Patchy B-lines with a normal heart point to noncardiogenic edema.'},
    lactate:{r:'Lactate 2.4 mmol/L', y:'optional', w:'Mildly elevated.'},
    cbc:{r:'WBC 16.4 · Hgb 13.1 · Plt 190', y:'optional', w:'Inflammatory leukocytosis.'},
    cmp:{r:'Na 137 · K 3.8 · BUN 22 · Cr 1.1 · Ca 7.9 · Glu 160', y:'optional', w:'Hypocalcemia fits severe pancreatitis.'},
    bcx:{r:'Drawn. Pending.', y:'optional', w:'Reasonable with a fever.'},
    ctpa:{img:{type:'ct', region:'chest', contrast:true, f:['ggo','consol'], side:'B'}, r:'No PE. Diffuse dependent consolidation and ground glass.', y:'low', w:'Transporting a crashing patient for a low-probability diagnosis.'},
    trop:{r:'hs-Troponin T 12 ng/L', y:'optional', w:'Normal.'},
    bronch:{r:'Nonspecific inflammation.', y:'harmful', w:'Invasive and destabilizing in a hypoxemic patient.'},
  },
  dx:'ards', dxPartial:{chf:5, cap:5},
  plan:[
    {t:'Intubate; tidal volume 6 mL/kg ideal body weight', k:'essential', w:'Lung-protective ventilation lowers mortality (ARDSNet).'},
    {t:'Keep plateau pressure ≤ 30 cm H2O; titrate PEEP', k:'essential', w:'Prevents barotrauma and recruits alveoli.'},
    {t:'Prone positioning 12–16 h/day', k:'essential', w:'Lowers mortality when P/F < 150 (PROSEVA).'},
    {t:'Conservative fluid strategy once out of shock', k:'good', w:'Shortens time on the ventilator (FACTT).'},
    {t:'Treat the cause: supportive pancreatitis care', k:'good', w:'ARDS improves as the cause resolves.'},
    {t:'Tidal volume 10–12 mL/kg actual body weight', k:'harmful', w:'High volumes cause ventilator-induced lung injury and raise mortality.'},
    {t:'IV furosemide 80 mg as the main treatment', k:'wrong', w:'This edema isn’t cardiogenic. Diuresis may help later, but it doesn’t treat ARDS and can drop her pressure now.'},
    {t:'Inhaled surfactant', k:'wrong', w:'No benefit in adult ARDS.'},
  ],
  pearls:[
    'Berlin definition: within 1 week of an insult, bilateral opacities not explained by effusion or collapse, not fully explained by heart failure, P/F ≤ 300 on PEEP ≥ 5.',
    'Severity by P/F ratio: 200–300 mild, 100–200 moderate, ≤ 100 severe.',
    'Lung-protective ventilation: 6 mL/kg ideal body weight, plateau ≤ 30. Prone when P/F < 150.',
    'Common causes: sepsis (most common), pneumonia, aspiration, pancreatitis, trauma, transfusion (TRALI).',
  ],
  target:{min:90, cost:1300},
},
);
