"use strict";
/* Infectious disease cases */
CASES.push(
{
  id:'urosepsis', subject:'ID', tier:1, tierWhy:'Sepsis bundle basics, plus one source-control catch.',
  bed:'ED 20', setting:'Emergency Dept', name:'Gloria Bennett', age:76, sex:'F',
  look:{skin:'#e7c6ae', hair:'#dedede', sex:'F', habitus:'heavy', sweat:true},
  cc:'Daughter: “Mom’s been confused and burning up since last night.”',
  brief:'76-year-old woman with 2 days of painful urination and flank pain, now febrile, confused, and hypotensive.',
  vitals:{hr:124, sbp:82, dbp:46, rr:26, spo2:95, temp:39.3, o2:'RA'},
  decline:{by:90, to:{hr:134, sbp:70, dbp:38}},
  events:[{at:30, text:'MAP is 55. She’s more confused.'}],
  histDefault:'She looks at you blankly. Her daughter answers.',
  hist:{
    hpi:'Daughter: “Two days of burning when she pees, and she said her back hurt. Last night she started shaking and got confused.”',
    gu:'Daughter: “Burning, going all the time, and pain in her right side.”',
    pmh:'Daughter: “Diabetes. She’s had kidney stones before.”',
    meds:'Daughter: “Metformin and lisinopril.”',
    fever:'Daughter: “Shaking chills, 103.”',
  },
  keyHist:['gu','pmh'],
  exam:{
    general:'Confused, flushed, warm.',
    back:'Right costovertebral angle tenderness.',
    abd:'Mild right flank tenderness. No peritoneal signs.',
    skin:'Warm and flushed. Capillary refill 4 s.',
    heart:'Tachycardic, regular.',
  },
  keyExam:['back'],
  tests:{
    lactate:{r:'Lactate 4.6 mmol/L', y:'key', w:'Lactate ≥ 4 = septic shock physiology. Repeat it after fluids.'},
    ua:{r:'Leukocyte esterase +, nitrite +, > 50 WBC/hpf, many bacteria', y:'key', w:'Urinary source.'},
    ursed:{img:{type:'urine', f:['wbc','wbccast','bacteria']}, r:'Pyuria, WBC casts, and bacteria.', y:'useful', w:'WBC casts localize infection to the kidney.'},
    bcx:{img:{type:'gram', f:['gnr']}, r:'Gram-negative rods in 2 of 2 bottles.', y:'key', w:'Draw before antibiotics, but don’t delay antibiotics for them.'},
    ucx:{r:'> 100,000 CFU/mL E. coli. Resistant to ampicillin only.', y:'useful', w:'Guides de-escalation.'},
    ctabd:{img:{type:'ct', region:'abd', f:['hydro','perinephric']}, r:'7-mm right proximal ureteral stone with moderate hydronephrosis and perinephric stranding.', y:'key', w:'An infected, obstructed kidney needs drainage.'},
    us_renal:{img:{type:'us', region:'renal', f:['hydro']}, r:'Moderate right hydronephrosis.', y:'key', w:'Bedside alternative that shows the obstruction.'},
    cbc:{r:'WBC 22.0 (14% bands) · Hgb 12.1 · Plt 140', y:'useful', w:'Leukocytosis with bandemia.'},
    cmp:{r:'Na 134 · K 4.8 · HCO3 17 · BUN 40 · Cr 2.1 (baseline 0.9) · Glu 260', y:'useful', w:'AKI. Hold metformin.'},
    pct:{r:'Procalcitonin 18 ng/mL', y:'low', w:'Doesn’t change anything when sepsis is obvious.'},
    cxr:{img:{type:'cxr', f:[]}, r:'Clear lungs.', y:'optional', w:'Reasonable to exclude a lung source.'},
  },
  keyOneOf:[['ctabd','us_renal']],
  dx:'urosepsis', dxPartial:{nephrolith:10, sepsis:20},
  plan:[
    {t:'30 mL/kg IV crystalloid within 3 hours', k:'essential', w:'Sepsis bundle.'},
    {t:'Broad-spectrum IV antibiotics within 1 hour (e.g., ceftriaxone or piperacillin-tazobactam)', k:'essential', w:'Each hour of delay raises mortality.'},
    {t:'Norepinephrine to MAP ≥ 65 if still hypotensive after fluids', k:'essential', w:'First-line vasopressor.'},
    {t:'Emergent urologic decompression (ureteral stent or nephrostomy tube)', k:'essential', w:'Antibiotics can’t sterilize an obstructed, infected kidney.'},
    {t:'Repeat lactate after resuscitation', k:'good', w:'Tracks perfusion.'},
    {t:'Hold metformin and lisinopril', k:'good', w:'AKI and hypotension.'},
    {t:'Dopamine as the first-line vasopressor', k:'wrong', w:'More arrhythmias than norepinephrine.'},
    {t:'Wait for the urine culture before antibiotics', k:'harmful', w:'Never delay antibiotics in septic shock.'},
    {t:'Lithotripsy now', k:'wrong', w:'Definitive stone treatment waits until the infection is controlled.'},
  ],
  pearls:[
    'Septic shock: vasopressors needed for MAP ≥ 65 plus lactate > 2 despite fluids.',
    'Hour-1 bundle: lactate, blood cultures, broad antibiotics, 30 mL/kg crystalloid for hypotension or lactate ≥ 4, vasopressors.',
    'Norepinephrine first. Add vasopressin second. Hydrocortisone for refractory shock.',
    'An obstructed, infected kidney is a urologic emergency: stent or nephrostomy.',
    'WBC casts localize infection to the kidney (pyelonephritis, interstitial nephritis).',
  ],
  target:{min:75, cost:1300},
},
{
  id:'meningitis', subject:'ID', tier:2, tierWhy:'Time-critical, with a CT-before-LP trap.',
  bed:'ED 21', setting:'Emergency Dept', name:'Kevin O’Brien', age:20, sex:'M',
  look:{skin:'#efd1bb', hair:'#8a4b22', sex:'M', habitus:'normal', sweat:true, petechiae:true, eyesClosed:true},
  cc:'Roommate: “His head is pounding, the light hurts his eyes, and he isn’t making sense.”',
  brief:'20-year-old college student brought from his dorm with 12 hours of fever, severe headache, and vomiting. His roommate says he’s getting confused.',
  vitals:{hr:122, sbp:104, dbp:62, rr:22, spo2:97, temp:39.6, o2:'RA'},
  decline:{by:120, to:{hr:136, sbp:84, dbp:48}},
  events:[{at:45, text:'The rash is spreading and his BP is drifting down.'}],
  histDefault:'He groans and turns away from the light. His roommate answers.',
  hist:{
    hpi:'Roommate: “Last night he said it was the worst headache of his life, then fever and throwing up. This morning he didn’t make sense.”',
    neuro:'Roommate: “He says his neck is stiff and the light hurts.”',
    ros:'Roommate: “Those spots on his legs weren’t there yesterday.”',
    travel:'Roommate: “We live in a dorm. No travel.”',
    meds:'Roommate: “Nothing.”',
    pmh:'Roommate: “He’s healthy. I don’t know about vaccines.”',
  },
  keyHist:['hpi','neuro'],
  exam:{
    general:'Lethargic and photophobic. Oriented to person only.',
    neck:'Nuchal rigidity. Positive Brudzinski sign.',
    skin:'Petechiae and a few purpuric spots on the legs and trunk.',
    neuro:'Confused. No focal deficits. No papilledema.',
    heart:'Tachycardic.',
  },
  keyExam:['neck','skin'],
  tests:{
    lp:{img:{type:'gram', f:['gndc','pmn']}, r:'Opening pressure 34 cm H2O. Cloudy. WBC 2,800 (92% neutrophils) · Glucose 22 (serum 110) · Protein 280. Gram stain: gram-negative diplococci within neutrophils.', y:'key', w:'Bacterial CSF profile. Neisseria meningitidis.'},
    bcx:{r:'Drawn. Gram-negative diplococci at 18 h.', y:'useful', w:'Draw before antibiotics, but never delay antibiotics for them.'},
    cthead:{img:{type:'ct', region:'head', f:[]}, r:'No mass, hemorrhage, or edema.', y:'optional', w:'Reasonable before LP given his altered mental status, but antibiotics go first.'},
    cbc:{r:'WBC 21.0 · Hgb 14.2 · Plt 98,000', y:'useful', w:'Falling platelets.'},
    pt:{r:'INR 1.4 · PTT 38 s · Fibrinogen 160', y:'useful', w:'Early DIC, which is common with meningococcemia.'},
    lactate:{r:'Lactate 4.1 mmol/L', y:'useful', w:'Septic physiology.'},
    cmp:{r:'Na 137 · Cr 1.1 · Glu 110', y:'optional', w:'Needed for the CSF/serum glucose ratio.'},
    hiv:{r:'Nonreactive', y:'optional', w:'Reasonable to screen.'},
    mri:{r:'Diffuse leptomeningeal enhancement.', y:'low', w:'Delays treatment and adds nothing.'},
  },
  dx:'meningitis', dxPartial:{viralmen:5, sah:5},
  plan:[
    {t:'Blood cultures, then IMMEDIATE IV ceftriaxone + vancomycin', k:'essential', w:'Antibiotics first, before CT or LP.'},
    {t:'Droplet precautions', k:'essential', w:'Meningococcus spreads by respiratory droplets.'},
    {t:'Prophylaxis for close contacts (ciprofloxacin, rifampin, or ceftriaxone)', k:'essential', w:'His roommate needs it.'},
    {t:'IV dexamethasone with or just before the first antibiotic dose', k:'good', w:'Proven benefit in pneumococcal meningitis. Give empirically, stop if another organism is found.'},
    {t:'Fluid resuscitation; vasopressors for septic shock', k:'good', w:'He’s becoming hypotensive.'},
    {t:'Add ampicillin', k:'wrong', w:'For Listeria risk: age > 50, immunocompromised, pregnant, or neonates.'},
    {t:'Wait for LP results before antibiotics', k:'harmful', w:'Every hour of delay raises mortality.'},
    {t:'Acyclovir alone', k:'wrong', w:'Treats HSV encephalitis, not bacterial meningitis.'},
  ],
  pearls:[
    'Empiric therapy: ages 1 month–50 years get ceftriaxone + vancomycin. Over 50 or immunocompromised: add ampicillin.',
    'CSF: bacterial = high PMNs, low glucose, high protein. Viral = lymphocytes, normal glucose.',
    'CT before LP if: immunocompromised, known CNS disease, new seizure, papilledema, altered consciousness, focal deficit. Give antibiotics first.',
    'Meningococcus: petechial rash, DIC, adrenal hemorrhage (Waterhouse-Friderichsen). Droplet precautions and contact prophylaxis.',
  ],
  target:{min:50, cost:800},
},
{
  id:'endocarditis', subject:'ID', tier:2, tierWhy:'Multi-system clues, Duke criteria, and harm reduction.',
  bed:'Ward 2D', setting:'Medicine ward', name:'Tyler Banks', age:31, sex:'M',
  look:{skin:'#e8c8b0', hair:'#5c4632', sex:'M', habitus:'thin', track:true, o2:'cannula'},
  cc:'I’ve had fevers and chills for a week, and now it hurts to breathe.',
  brief:'31-year-old man who injects heroin, with a week of fevers and rigors and new pleuritic chest pain.',
  vitals:{hr:118, sbp:108, dbp:64, rr:24, spo2:93, temp:39.4, o2:'RA'},
  hist:{
    hpi:'A week of fevers and shaking chills. For the last two days my chest hurts when I breathe in.',
    etoh:'I inject heroin, sometimes fentanyl, a few times a day. Sometimes I reuse needles.',
    cough:'A little cough. A bit of blood once.',
    pmh:'Hepatitis C.',
    meds:'Nothing prescribed.',
    sex:'Not tested for HIV in a couple of years.',
  },
  keyHist:['etoh'],
  exam:{
    general:'Thin, ill, febrile.',
    heart:'Holosystolic murmur at the left lower sternal border that gets louder with inspiration (tricuspid regurgitation).',
    neck:'Prominent v waves in the jugular pulse.',
    skin:'Track marks on both forearms.',
    hands:'Splinter hemorrhages under two fingernails.',
    lungR:'Scattered crackles.', lungL:'Scattered crackles.',
  },
  keyExam:['heart','hands','skin'],
  tests:{
    bcx:{img:{type:'gram', f:['gpc_clusters']}, r:'3 of 3 sets: gram-positive cocci in clusters → Staphylococcus aureus (MSSA).', y:'key', w:'Persistent bacteremia with a typical organism is a major Duke criterion.'},
    tte:{r:'1.8 cm vegetation on the tricuspid valve with severe TR. Left-sided valves normal.', y:'key', w:'Evidence of endocardial involvement is the other major criterion.'},
    cxr:{img:{type:'cxr', f:['septic']}, r:'Multiple peripheral nodules in both lungs.', y:'useful', w:'Septic pulmonary emboli.'},
    ct:{img:{type:'ct', region:'chest', f:['nodules']}, r:'Multiple peripheral nodules, several cavitating. Feeding-vessel sign.', y:'optional', w:'Characterizes the septic emboli.'},
    cbc:{r:'WBC 17.0 · Hgb 11.0 · Plt 160', y:'useful', w:'Leukocytosis, anemia of inflammation.'},
    hiv:{r:'Nonreactive', y:'useful', w:'Screen everyone who injects drugs.'},
    ecg:{img:{type:'ecg', f:['stach']}, r:'Sinus tachycardia 118. Normal PR interval.', y:'optional', w:'A new PR prolongation would suggest an aortic root abscess.'},
    ua:{r:'Microscopic hematuria.', y:'optional', w:'Immune complex glomerulonephritis or renal emboli.'},
    cmp:{r:'Cr 1.0 · AST 44 · ALT 52', y:'optional', w:'Baseline for vancomycin dosing.'},
    ctpa:{img:{type:'ct', region:'chest', contrast:true, f:['nodules']}, r:'No bland PE. Multiple septic emboli.', y:'low', w:'Doesn’t change management.'},
  },
  dx:'endocarditis', dxPartial:{pe:5, cap:5},
  plan:[
    {t:'IV vancomycin now, then narrow to cefazolin or nafcillin for MSSA', k:'essential', w:'Beta-lactams beat vancomycin for MSSA.'},
    {t:'Plan 4–6 weeks of IV antibiotics', k:'essential', w:'Long courses are needed to sterilize the vegetation.'},
    {t:'Offer medication for opioid use disorder (buprenorphine or methadone)', k:'essential', w:'Treats the cause and reduces reinfection and death.'},
    {t:'Repeat blood cultures until they clear', k:'good', w:'Defines day 1 of therapy.'},
    {t:'HIV and HCV care; naloxone kit and harm-reduction counseling', k:'good', w:'Comprehensive care.'},
    {t:'Anticoagulate for the pulmonary emboli', k:'harmful', w:'Septic emboli aren’t treated with anticoagulation, and it raises hemorrhage risk.'},
    {t:'Oral amoxicillin for 2 weeks', k:'harmful', w:'Inadequate for S. aureus endocarditis.'},
    {t:'Immediate valve surgery', k:'wrong', w:'Surgery is for heart failure, uncontrolled infection, abscess, or high embolic risk on left-sided valves.'},
  ],
  pearls:[
    'Duke major criteria: typical organism in 2 blood cultures (or persistent bacteremia), and evidence of endocardial involvement (vegetation, abscess, new regurgitation).',
    'IV drug use → tricuspid valve, S. aureus, septic pulmonary emboli.',
    'Subacute native valve: viridans strep. S. gallolyticus → colonoscopy. Culture-negative: HACEK, Coxiella, Bartonella.',
    'Signs: Osler nodes (painful), Janeway lesions (painless), Roth spots, splinter hemorrhages.',
    'Surgery: heart failure, abscess or heart block, persistent bacteremia, fungal infection, large mobile left-sided vegetation.',
  ],
  target:{min:120, cost:1700},
},
{
  id:'pjp', subject:'ID', tier:3, tierWhy:'A new HIV diagnosis with an opportunistic infection.',
  bed:'Ward 9A', setting:'Medicine ward', name:'Daniel Ruiz', age:34, sex:'M',
  look:{skin:'#c9a07c', hair:'#1f1610', sex:'M', habitus:'thin', o2:'cannula'},
  cc:'I’ve been getting more and more short of breath for three weeks.',
  brief:'34-year-old man with 3 weeks of progressive dyspnea on exertion, dry cough, and low-grade fevers. He hasn’t seen a doctor in years.',
  vitals:{hr:108, sbp:118, dbp:72, rr:26, spo2:88, temp:38.2, o2:'RA'},
  hist:{
    hpi:'Three weeks of getting winded. Now even walking to the bathroom. A dry cough.',
    sex:'I have sex with men, not always with condoms. I’ve never been tested for HIV.',
    wt:'Lost 20 pounds this year.',
    fever:'Low-grade fevers and night sweats.',
    pmh:'Thrush in my mouth a few times this year.',
    meds:'Nothing.',
  },
  keyHist:['sex','pmh'],
  exam:{
    general:'Thin, tachypneic, speaking in short sentences.',
    heent:'White plaques on the tongue and cheeks that scrape off (thrush).',
    lungR:'Faint crackles. Otherwise clear.',
    lungL:'Faint crackles. Otherwise clear.',
    neck:'Small, mobile cervical lymph nodes.',
    skin:'Seborrheic dermatitis on the face.',
  },
  keyExam:['heent'],
  tests:{
    cxr:{img:{type:'cxr', f:['ggo_bil']}, r:'Bilateral, symmetric perihilar hazy (ground-glass) opacities. No effusion.', y:'key', w:'Classic PJP pattern.'},
    hiv:{r:'HIV-1 antibody POSITIVE.', y:'key', w:'New HIV diagnosis.'},
    cd4:{r:'CD4 42 cells/µL · Viral load 245,000 copies/mL', y:'key', w:'AIDS (CD4 < 200).'},
    abg:{r:'Room air: pH 7.47 · PaCO2 32 · PaO2 58', y:'key', w:'PaO2 < 70 → add steroids.'},
    isputum:{r:'Direct fluorescent antibody POSITIVE for Pneumocystis jirovecii.', y:'key', w:'Confirms the diagnosis noninvasively.'},
    bdg:{r:'1,3-β-D-glucan 480 pg/mL (high)', y:'useful', w:'Supports PJP.'},
    ldh:{r:'LDH 520 U/L', y:'optional', w:'Elevated in PJP. Nonspecific.'},
    g6pd:{r:'Normal activity', y:'useful', w:'Check before dapsone or primaquine, the alternatives to TMP-SMX.'},
    afb:{r:'AFB smears negative. TB NAAT not detected.', y:'useful', w:'TB must be excluded in HIV with lung symptoms.'},
    hrct:{img:{type:'ct', region:'chest', f:['ggo']}, r:'Diffuse ground-glass opacities.', y:'optional', w:'Helpful when the X-ray is normal. Not needed here.'},
    bronch:{r:'BAL silver stain: Pneumocystis cysts.', y:'low', w:'Only needed if induced sputum is negative.'},
    cbc:{r:'WBC 3.2 · Hgb 11.8 · Plt 160', y:'optional', w:'Leukopenia is common in advanced HIV.'},
  },
  dx:'pjp', dxPartial:{tb:0, cap:5},
  plan:[
    {t:'High-dose TMP-SMX for 21 days', k:'essential', w:'First-line treatment.'},
    {t:'Prednisone (PaO2 < 70 or A-a gradient ≥ 35)', k:'essential', w:'Prevents worsening inflammation as organisms die. Lowers mortality.'},
    {t:'Start ART within 2 weeks', k:'essential', w:'Early ART improves survival in PJP.'},
    {t:'Fluconazole for oral thrush', k:'good', w:'Treats the candidiasis.'},
    {t:'Continue TMP-SMX prophylaxis until CD4 > 200 for 3 months', k:'good', w:'Secondary prophylaxis.'},
    {t:'Ceftriaxone + azithromycin alone', k:'harmful', w:'Doesn’t treat Pneumocystis.'},
    {t:'Inhaled pentamidine as treatment', k:'wrong', w:'Only an alternative for prophylaxis. Not treatment.'},
    {t:'Azithromycin MAC prophylaxis', k:'ok', w:'Not needed if ART starts promptly, per current guidelines.'},
  ],
  pearls:[
    'Prophylaxis thresholds: CD4 < 200 → TMP-SMX (PJP). CD4 < 100 and Toxoplasma IgG+ → TMP-SMX. CD4 < 50 → MAC prophylaxis only if not starting ART.',
    'PJP: subacute dyspnea, hypoxemia out of proportion to the exam, high LDH and β-D-glucan, bilateral ground glass.',
    'Steroids if PaO2 < 70 or A-a gradient ≥ 35.',
    'Start ART within 2 weeks for most OIs. Delay for cryptococcal and TB meningitis.',
  ],
  target:{min:180, cost:1500},
}
);
