"use strict";
/* Cardiology cases */
CASES.push(
{
  id:'stemi', subject:'Cardio', tier:1, tierWhy:'The classic emergency, with a right-ventricle twist.',
  bed:'ED 1', setting:'Emergency Dept', name:'Raymond Fuller', age:61, sex:'M',
  look:{skin:'#d6a587', hair:'#9a9a9a', sex:'M', habitus:'heavy', sweat:true, pallor:.35},
  cc:'It feels like an elephant is sitting on my chest.',
  brief:'61-year-old man with 45 minutes of crushing substernal pressure radiating to his jaw, with nausea and sweating.',
  vitals:{hr:56, sbp:98, dbp:62, rr:20, spo2:96, temp:36.9, o2:'RA'},
  hist:{
    hpi:'It started 45 minutes ago while I was shoveling snow. Heavy pressure right in the middle, going up into my jaw and down my left arm.',
    cp:'Crushing pressure, 9 out of 10. Breathing and moving don’t change it.',
    gi:'Nauseous. I threw up once.',
    pmh:'Diabetes, high blood pressure, high cholesterol.',
    meds:'Metformin, lisinopril, atorvastatin. And I took a sildenafil last night. Is that a problem?',
    etoh:'A pack a day. A couple of beers on weekends.',
    smoke:'A pack a day for 40 years.',
    fhx:'My dad had a heart attack at 50.',
  },
  keyHist:['cp','meds'],
  exam:{
    general:'Pale and diaphoretic, clutching his chest.',
    neck:'JVP elevated to 11 cm. It rises with inspiration (Kussmaul sign).',
    lungR:'Clear.', lungL:'Clear.',
    heart:'Bradycardic, regular. S4 gallop. No murmur.',
    hands:'Cool hands. Equal radial pulses.',
  },
  keyExam:['neck','lungR'],
  tests:{
    ecg:{img:{type:'ecg', f:['sbrady','stemi_inf','recip_lat']}, r:'Sinus bradycardia 56. ST elevation in II, III, aVF (III > II) with reciprocal ST depression in I and aVL. Right-sided leads: ST elevation in V4R (RV infarct).', y:'key', w:'STEMI is an ECG diagnosis. Inferior STEMI with III > II should prompt right-sided leads.'},
    trop:{r:'hs-Troponin T 48 ng/L (elevated, rising)', y:'useful', w:'Confirms injury, but never wait for troponin to activate the cath lab.'},
    cxr:{img:{type:'cxr', f:[]}, r:'Normal mediastinum. Clear lungs.', y:'optional', w:'A quick look for a widened mediastinum is reasonable but shouldn’t delay reperfusion.'},
    cmp:{r:'Na 138 · K 4.4 · Cr 1.1 · Glu 212', y:'optional', w:'Baseline kidney function before contrast.'},
    cbc:{r:'WBC 10.8 · Hgb 14.6 · Plt 250', y:'optional', w:'Baseline before anticoagulation.'},
    pt:{r:'INR 1.0 · PTT 29 s', y:'optional', w:'Baseline before anticoagulation.'},
    cta:{img:{type:'ct', region:'chest', contrast:true, f:[]}, r:'No aortic dissection.', y:'harmful', w:'Nothing suggests dissection (equal pulses, normal mediastinum). CT delays door-to-balloon time.'},
    tte:{r:'Inferior and RV free-wall hypokinesis. LVEF 50%.', y:'low', w:'Confirms what the ECG told you. Don’t delay the cath lab for it.'},
    ddimer:{r:'D-dimer 0.6 µg/mL FEU', y:'low', w:'Not the question.'},
  },
  dx:'stemi', dxPartial:{nstemi:15, dissection:0},
  plan:[
    {t:'Activate the cath lab for primary PCI (door-to-balloon < 90 min)', k:'essential', w:'Reperfusion is the treatment.'},
    {t:'Aspirin 325 mg, chewed', k:'essential', w:'Lowers mortality. Give immediately.'},
    {t:'P2Y12 inhibitor (ticagrelor or clopidogrel) + heparin', k:'essential', w:'Dual antiplatelet therapy plus anticoagulation for PCI.'},
    {t:'IV fluid bolus for his low blood pressure', k:'good', w:'RV infarcts are preload-dependent.'},
    {t:'High-intensity statin', k:'good', w:'For every patient with ACS.'},
    {t:'Sublingual nitroglycerin', k:'harmful', w:'RV infarct plus hypotension plus a PDE-5 inhibitor last night. Nitrates can cause profound hypotension.'},
    {t:'IV metoprolol now', k:'harmful', w:'He’s bradycardic and hypotensive. Hold beta-blockers in shock, bradycardia, or heart block.'},
    {t:'Wait for the troponin before calling cardiology', k:'harmful', w:'Every minute of delay costs myocardium.'},
    {t:'Fibrinolytics if PCI can’t happen within 120 min', k:'ok', w:'Correct backup plan, but PCI is available here.'},
  ],
  pearls:[
    'Inferior STEMI (II, III, aVF) = right coronary artery in most people. If III > II or there’s hypotension, get right-sided leads (V4R).',
    'RV infarct triad: hypotension, JVD, clear lungs. Give fluids. Avoid nitrates, diuretics, and morphine.',
    'No nitrates within 24 h of sildenafil or vardenafil, or 48 h of tadalafil.',
    'Door-to-balloon < 90 min. If PCI isn’t possible within 120 min, give fibrinolytics within 30 min of arrival.',
    'After MI: aspirin, P2Y12 inhibitor, high-intensity statin, beta-blocker, ACE inhibitor (especially if EF < 40%).',
  ],
  target:{min:30, cost:400},
},
{
  id:'adhf', subject:'Cardio', tier:1, tierWhy:'One of the most common admissions in medicine.',
  bed:'ED 4', setting:'Emergency Dept', name:'Dolores Hughes', age:74, sex:'F',
  look:{skin:'#e3b9a2', hair:'#d8d8d8', sex:'F', habitus:'heavy', edema:true, o2:'cannula', sweat:true},
  cc:'I can’t lie flat. I have to sleep sitting up.',
  brief:'74-year-old woman with a week of worsening shortness of breath, orthopnea, and leg swelling after a salty holiday weekend.',
  vitals:{hr:104, sbp:168, dbp:96, rr:26, spo2:89, temp:36.8, o2:'2 L NC'},
  hist:{
    hpi:'This past week I’ve gotten more and more short of breath. Now I wake up gasping and have to sit on the edge of the bed. We had ham and lots of salty food over the holidays.',
    cough:'A little cough, frothy and white.',
    cp:'No chest pain.',
    pmh:'A heart attack 5 years ago. They said my heart is weak. Diabetes and high blood pressure.',
    meds:'Furosemide, carvedilol, lisinopril, metformin. I ran out of the furosemide a week ago. I’ve also been taking ibuprofen for my knee.',
    sleep:'I sleep in my recliner now. Three pillows isn’t enough.',
    immob:'My ankles have been huge.',
  },
  keyHist:['meds','sleep','hpi'],
  exam:{
    general:'Sitting bolt upright, speaking in short sentences.',
    neck:'JVP 14 cm with a positive hepatojugular reflux.',
    lungR:'Inspiratory crackles halfway up the back.',
    lungL:'Inspiratory crackles halfway up the back.',
    heart:'S3 gallop. Laterally displaced PMI. Soft holosystolic murmur at the apex.',
    abd:'Mildly enlarged, tender liver.',
    legs:'3+ pitting edema to the knees.',
  },
  keyExam:['neck','heart','lungR','legs'],
  tests:{
    cxr:{img:{type:'cxr', f:['cardiomeg','edema','eff_bil']}, r:'Cardiomegaly, cephalization, Kerley B lines, and small bilateral effusions.', y:'key', w:'Classic pulmonary edema.'},
    bnp:{r:'BNP 1,840 pg/mL', y:'key', w:'Supports heart failure as the cause of dyspnea.'},
    ecg:{img:{type:'ecg', f:['stach','lvh']}, r:'Sinus tachycardia 104. LVH by voltage. No acute ST changes.', y:'useful', w:'Rule out ischemia or arrhythmia as the trigger.'},
    trop:{r:'hs-Troponin T 22 ng/L, flat on repeat', y:'useful', w:'Mild stable elevation is common in HF. Not an ACS pattern.'},
    tte:{r:'LVEF 25%. Global hypokinesis, worst in the anterior wall. Moderate functional MR.', y:'key', w:'Classifies her as HFrEF, which drives long-term therapy.'},
    cmp:{r:'Na 132 · K 4.6 · BUN 38 · Cr 1.6 (baseline 1.1) · Glu 180', y:'useful', w:'Cardiorenal physiology. Monitor during diuresis.'},
    cbc:{r:'WBC 8.1 · Hgb 11.8 · Plt 220', y:'optional', w:'Anemia can worsen HF.'},
    abg:{r:'2 L NC: pH 7.45 · PaCO2 34 · PaO2 60', y:'optional', w:'Hypoxemia without hypercapnia.'},
    ctpa:{img:{type:'ct', region:'chest', contrast:true, f:['effusion','ggo'], side:'B'}, r:'No PE. Bilateral effusions and interstitial edema.', y:'low', w:'The story is HF. Contrast is risky with her kidneys.'},
    ddimer:{r:'D-dimer 0.9 µg/mL FEU', y:'low', w:'Nonspecific. Adds noise.'},
  },
  dx:'chf', dxPartial:{ards:0, pe:0},
  plan:[
    {t:'IV loop diuretic (furosemide at or above her home dose, given IV)', k:'essential', w:'Decongestion is the main treatment for a warm, wet patient.'},
    {t:'Stop NSAIDs', k:'essential', w:'NSAIDs cause sodium retention and worsen kidney function.'},
    {t:'IV nitroglycerin for hypertensive pulmonary edema', k:'good', w:'Lowers preload and afterload when BP is high.'},
    {t:'Oxygen; BiPAP if work of breathing worsens', k:'good', w:'Noninvasive ventilation reduces intubation in cardiogenic edema.'},
    {t:'Daily weights, strict I/O, 2 g sodium restriction', k:'good', w:'Tracks response to diuresis.'},
    {t:'Before discharge: add an SGLT2 inhibitor and MRA; switch ACE inhibitor to sacubitril-valsartan after a 36-h washout', k:'good', w:'Guideline-directed therapy for HFrEF lowers mortality.'},
    {t:'IV fluids for the rising creatinine', k:'harmful', w:'Her kidneys are congested, not dry. Diuresis usually improves cardiorenal AKI.'},
    {t:'Diltiazem for rate control', k:'harmful', w:'Non-dihydropyridine calcium channel blockers worsen HFrEF.'},
    {t:'Start dobutamine', k:'wrong', w:'Inotropes are for low-output (cold) heart failure. She’s warm and hypertensive.'},
  ],
  pearls:[
    'Warm and wet (congested, perfusing): diuretics ± vasodilators. Cold and wet: inotropes and specialist care.',
    'HFrEF mortality benefit: ACEi/ARB/ARNI, beta-blocker (carvedilol, metoprolol succinate, bisoprolol), MRA, SGLT2 inhibitor. Add hydralazine-nitrate in Black patients.',
    'Avoid in HFrEF: NSAIDs, non-DHP calcium channel blockers, thiazolidinediones.',
    'Common triggers: dietary sodium, missed meds, ischemia, arrhythmia (AF), infection, uncontrolled BP, NSAIDs.',
    'ICD if EF ≤ 35% after 3 months of optimal therapy.',
  ],
  target:{min:110, cost:1400},
},
{
  id:'afib', subject:'Cardio', tier:1, tierWhy:'The most common arrhythmia you’ll manage.',
  bed:'ED 6', setting:'Emergency Dept', name:'Thomas Byrne', age:69, sex:'M', rhythm:'afib',
  look:{skin:'#e6c0a5', hair:'#b0b0b0', sex:'M', habitus:'heavy'},
  cc:'My heart’s been racing since this morning.',
  brief:'69-year-old man with 8 hours of palpitations and mild lightheadedness.',
  vitals:{hr:148, sbp:128, dbp:80, rr:20, spo2:96, temp:37.0, o2:'RA'},
  hist:{
    hpi:'I woke up around 6 this morning with my heart pounding and skipping. A little lightheaded, but I can walk fine.',
    cp:'No chest pain. Just fluttering.',
    pmh:'High blood pressure and diabetes. I had a mini-stroke two years ago.',
    meds:'Amlodipine, metformin, and a baby aspirin.',
    etoh:'I drink a six-pack most weekends. Last night was a wedding, so more than that.',
    sleep:'My wife says I snore loudly.',
    cough:'No shortness of breath.',
  },
  keyHist:['pmh','hpi'],
  exam:{
    general:'Anxious but comfortable.',
    heart:'Irregularly irregular rhythm at about 150. No murmur.',
    neck:'No JVD. Thyroid normal.',
    legs:'No edema.',
  },
  keyExam:['heart'],
  tests:{
    ecg:{img:{type:'ecg', f:['afib'], rate:148}, r:'Atrial fibrillation with rapid ventricular response, about 148. Narrow QRS. No ST elevation.', y:'key', w:'Diagnoses AF. No P waves, irregularly irregular.'},
    tsh:{r:'TSH 1.6 mIU/L · Free T4 1.1 ng/dL', y:'useful', w:'Check thyroid function in new-onset AF.'},
    cmp:{r:'Na 139 · K 4.0 · Mg 1.9 · Cr 1.0 · Glu 150', y:'useful', w:'Electrolytes and kidney function guide drug choice and DOAC dosing.'},
    tte:{r:'Left atrium 4.6 cm. LVEF 55%. No significant valve disease.', y:'useful', w:'Structure and EF guide rate-control and rhythm-control choices.'},
    trop:{r:'hs-Troponin T 8 ng/L', y:'optional', w:'Reasonable if ischemia is suspected.'},
    cbc:{r:'WBC 7.6 · Hgb 14.2 · Plt 220', y:'optional', w:'Baseline before anticoagulation.'},
    cxr:{img:{type:'cxr', f:[]}, r:'Normal.', y:'optional', w:'Reasonable but low yield.'},
    ddimer:{r:'D-dimer 0.4 µg/mL FEU', y:'low', w:'No PE features.'},
    ctpa:{img:{type:'ct', region:'chest', contrast:true, f:[]}, r:'No PE.', y:'low', w:'No PE features.'},
  },
  dx:'afib', dxPartial:{aflutter:15, svt:5},
  plan:[
    {t:'Rate control with IV diltiazem or metoprolol', k:'essential', w:'Stable patient with a preserved EF.'},
    {t:'Start a DOAC (e.g., apixaban) for stroke prevention', k:'essential', w:'CHA₂DS₂-VASc = 5 (age 65–74, hypertension, diabetes, prior TIA ×2).'},
    {t:'If rhythm control is chosen: TEE or 3 weeks of anticoagulation before cardioversion', k:'good', w:'Prevents embolizing a left atrial clot. Continue anticoagulation 4 weeks after.'},
    {t:'Counsel on alcohol and refer for a sleep study', k:'good', w:'Both are reversible AF triggers.'},
    {t:'Immediate synchronized cardioversion', k:'wrong', w:'Only for hemodynamic instability.'},
    {t:'Aspirin alone for stroke prevention', k:'wrong', w:'Aspirin doesn’t adequately prevent AF strokes.'},
    {t:'Digoxin as first-line rate control', k:'wrong', w:'Slow onset and weak during exertion. Second-line, or for HFrEF with hypotension.'},
    {t:'Amiodarone load as first-line therapy', k:'wrong', w:'Toxic. Not first-line for rate control in a stable patient.'},
  ],
  pearls:[
    'Unstable AF (hypotension, shock, ischemia) → synchronized cardioversion.',
    'Stable: rate control with a beta-blocker or diltiazem/verapamil (avoid non-DHP CCBs in HFrEF).',
    'CHA₂DS₂-VASc ≥ 2 in men or ≥ 3 in women → anticoagulate. DOACs preferred, except with a mechanical valve or moderate-to-severe mitral stenosis (warfarin).',
    'AF > 48 h or unknown duration: 3 weeks of anticoagulation or a TEE before cardioversion, then 4 weeks after.',
    'Workup for new AF: ECG, TSH, electrolytes, echo. Think alcohol, OSA, hyperthyroidism, PE.',
  ],
  target:{min:100, cost:1300},
},
{
  id:'dissection', subject:'Cardio', tier:3, tierWhy:'Rare, deadly, and easily mistaken for an MI.',
  bed:'ED 8', setting:'Emergency Dept', name:'Victor Salazar', age:58, sex:'M',
  look:{skin:'#c99a74', hair:'#2b2018', sex:'M', habitus:'heavy', sweat:true},
  cc:'Something ripped in my chest, and it’s going straight through to my back.',
  brief:'58-year-old man with sudden, severe tearing chest pain radiating between his shoulder blades. It began 30 minutes ago.',
  vitals:{hr:102, sbp:184, dbp:98, rr:22, spo2:97, temp:36.7, o2:'RA'},
  hist:{
    hpi:'It came on all at once, the worst pain of my life. Like tearing, right between my shoulder blades.',
    cp:'Ripping pain. It was strongest the moment it started.',
    pmh:'High blood pressure. I stopped my pills a few months ago.',
    meds:'Nothing now. I used to take amlodipine.',
    etoh:'No cocaine in years. A few beers a week.',
    fhx:'Nobody with Marfan’s that I know of.',
    neuro:'No weakness or numbness.',
  },
  keyHist:['hpi','pmh'],
  exam:{
    general:'Writhing in pain, diaphoretic.',
    heart:'Early diastolic decrescendo murmur at the right sternal border (aortic regurgitation).',
    hands:'Left radial pulse weaker than right. BP 184/98 right arm, 142/80 left arm.',
    neuro:'No focal deficits.',
    lungR:'Clear.', lungL:'Clear.',
  },
  keyExam:['hands','heart'],
  tests:{
    cta:{img:{type:'ct', region:'chest', contrast:true, f:['dissection']}, r:'Intimal flap from the ascending aorta through the arch into the descending aorta. Stanford type A.', y:'key', w:'CTA is the test of choice in a stable patient.'},
    cxr:{img:{type:'cxr', f:['widemed']}, r:'Widened mediastinum (9 cm).', y:'useful', w:'Suggestive, but a normal film doesn’t exclude dissection.'},
    ecg:{img:{type:'ecg', f:['stach','lvh']}, r:'Sinus tachycardia 102. LVH. No ST elevation.', y:'useful', w:'Rule out STEMI before anyone gives heparin. Dissection can also extend into the RCA.'},
    cmp:{r:'Na 139 · K 3.9 · Cr 1.1', y:'useful', w:'Kidney function before contrast.'},
    tnc:{r:'O negative. 4 units crossmatched.', y:'useful', w:'He’s going to the OR.'},
    trop:{r:'hs-Troponin T 9 ng/L', y:'optional', w:'Normal. Doesn’t exclude dissection.'},
    cbc:{r:'Hgb 14.0 · Plt 210', y:'optional', w:'Baseline.'},
    ddimer:{r:'D-dimer 4.2 µg/mL FEU', y:'low', w:'High suspicion → image directly.'},
    ctpa:{img:{type:'ct', region:'chest', contrast:true, f:['dissection']}, r:'Timed for the pulmonary arteries. Possible ascending aortic flap, poorly opacified.', y:'low', w:'Wrong protocol. A dedicated aortic CTA is needed.'},
    tte:{r:'Dilated aortic root with moderate AR. Possible flap. No pericardial effusion.', y:'optional', w:'Bedside TTE can help, but TEE or CTA is needed to confirm.'},
  },
  dx:'dissection', dxPartial:{stemi:0, pe:0},
  plan:[
    {t:'IV esmolol (or labetalol) first: HR < 60, then SBP 100–120', k:'essential', w:'Lowers shear stress on the aortic wall.'},
    {t:'Emergency cardiothoracic surgery', k:'essential', w:'Type A (ascending) dissection is a surgical emergency.'},
    {t:'IV opioid analgesia', k:'good', w:'Pain drives the sympathetic surge.'},
    {t:'Type and crossmatch blood', k:'good', w:'Prepare for surgery.'},
    {t:'Nitroprusside alone, without a beta-blocker', k:'harmful', w:'Reflex tachycardia increases shear stress. Beta-block first.'},
    {t:'Aspirin and heparin for presumed ACS', k:'harmful', w:'Anticoagulation can be fatal in dissection.'},
    {t:'Thrombolytics', k:'harmful', w:'Catastrophic in dissection.'},
    {t:'Medical management with outpatient follow-up', k:'harmful', w:'That’s for uncomplicated type B. Type A needs surgery.'},
  ],
  pearls:[
    'Stanford A (any ascending aorta) → surgery. Stanford B (descending only) → medical management unless complicated.',
    'Risk factors: hypertension (most common), Marfan, Ehlers-Danlos, bicuspid aortic valve, cocaine, pregnancy.',
    'Clues: tearing pain to the back, BP difference > 20 mmHg between arms, new AR murmur, widened mediastinum.',
    'Imaging: CTA if stable; TEE if unstable or contrast is contraindicated.',
    'Complications: AR, tamponade, MI (usually RCA), stroke, limb or mesenteric ischemia.',
  ],
  target:{min:75, cost:1400},
}
);
