"use strict";
/* GI and hepatology cases */
CASES.push(
{
  id:'ugib', subject:'GI', tier:1, tierWhy:'A bread-and-butter bleed with clear resuscitation rules.',
  bed:'ED 10', setting:'Emergency Dept', name:'Michael Turner', age:66, sex:'M',
  look:{skin:'#e0b79c', hair:'#9b9b9b', sex:'M', habitus:'normal', pallor:.55, sweat:true},
  cc:'I threw up something that looked like coffee grounds, and my stool is black.',
  brief:'66-year-old man with 2 days of black, tarry stools and one episode of coffee-ground emesis today. Lightheaded when he stands.',
  vitals:{hr:118, sbp:96, dbp:58, rr:20, spo2:98, temp:36.6, o2:'RA'},
  decline:{by:180, to:{hr:128, sbp:86, dbp:52}},
  hist:{
    hpi:'Two days of black, sticky stools. This morning I threw up dark stuff like coffee grounds. I nearly fainted getting out of bed.',
    gi:'A burning pain in my upper belly for a few weeks. It gets better when I eat.',
    meds:'Naproxen twice a day for my back for the last two months, plus a baby aspirin.',
    pmh:'Arthritis and high blood pressure. No liver problems.',
    etoh:'A couple of beers a week.',
    cp:'No chest pain.',
  },
  keyHist:['meds','hpi'],
  exam:{
    general:'Pale and diaphoretic.',
    abd:'Mild epigastric tenderness. No guarding or rebound. No hepatosplenomegaly.',
    rectal:'Black, tarry stool (melena) on the glove.',
    skin:'Pale and cool. No jaundice, spider angiomas, or palmar erythema.',
    heart:'Tachycardic, regular. No murmur.',
  },
  keyExam:['rectal'],
  tests:{
    cbc:{r:'Hgb 7.1 (baseline 13.5) · MCV 88 · WBC 9.4 · Plt 260', y:'key', w:'Significant acute blood loss.'},
    cmp:{r:'Na 140 · K 4.3 · BUN 48 · Cr 1.0 · Glu 120 · AST 22 · ALT 18 · Alb 3.8', y:'useful', w:'BUN/Cr > 30 suggests an upper GI source (digested blood).'},
    pt:{r:'INR 1.1 · PTT 30 s', y:'useful', w:'No coagulopathy.'},
    tnc:{r:'A positive. 4 units crossmatched.', y:'key', w:'Prepare blood before you need it.'},
    egd:{r:'2 cm duodenal bulb ulcer with a visible vessel. Treated with epinephrine injection and clips. Rapid urease test positive (H. pylori).', y:'key', w:'Endoscopy within 24 h diagnoses and treats.'},
    ecg:{img:{type:'ecg', f:['stach']}, r:'Sinus tachycardia 118. No ischemic changes.', y:'optional', w:'Reasonable in an older patient with anemia.'},
    trop:{r:'hs-Troponin T 7 ng/L', y:'optional', w:'Demand ischemia can follow severe anemia.'},
    ctabd:{img:{type:'ct', region:'abd', f:[]}, r:'No acute abnormality. No free air.', y:'low', w:'Endoscopy is both diagnostic and therapeutic.'},
    colo:{r:'Old blood throughout. No colonic source.', y:'low', w:'Hematemesis plus melena points upstream.'},
    cxr:{img:{type:'cxr', f:[]}, r:'No free air. Normal.', y:'low', w:'No peritoneal signs.'},
  },
  dx:'pud', dxPartial:{varices:10, mallory:5},
  plan:[
    {t:'Two large-bore IVs and crystalloid resuscitation', k:'essential', w:'Restore perfusion first.'},
    {t:'Transfuse red cells to keep Hgb > 7', k:'essential', w:'Restrictive transfusion improves survival (> 8 with active coronary disease).'},
    {t:'High-dose IV proton pump inhibitor', k:'essential', w:'Stabilizes the clot and lowers rebleeding.'},
    {t:'Upper endoscopy within 24 h', k:'essential', w:'Treat high-risk stigmata like a visible vessel.'},
    {t:'Stop naproxen; treat H. pylori (e.g., bismuth quadruple therapy)', k:'good', w:'Removes both main causes of ulcers.'},
    {t:'Transfuse to Hgb > 10', k:'harmful', w:'Liberal transfusion increases rebleeding and mortality.'},
    {t:'IV octreotide and ceftriaxone', k:'wrong', w:'For variceal bleeding in cirrhosis. He has no liver disease.'},
    {t:'Emergency surgery now', k:'wrong', w:'Only if endoscopic therapy fails.'},
  ],
  pearls:[
    'Upper GI bleed: hematemesis, coffee-ground emesis, melena, BUN/Cr > 30.',
    'Resuscitate, transfuse to Hgb > 7, IV PPI, endoscopy within 24 h.',
    'Peptic ulcer causes: H. pylori and NSAIDs. Duodenal ulcer pain improves with food; gastric ulcer pain worsens.',
    'Suspected varices (cirrhosis): octreotide + ceftriaxone + banding within 12 h.',
    'Glasgow-Blatchford score helps decide who can go home.',
  ],
  target:{min:150, cost:2600},
},
{
  id:'pancreatitis', subject:'GI', tier:1, tierWhy:'Common, and supportive care has specific rules.',
  bed:'ED 11', setting:'Emergency Dept', name:'Shawn Kelley', age:44, sex:'M',
  look:{skin:'#e7c4a8', hair:'#5a3a22', sex:'M', habitus:'normal', sweat:true},
  cc:'The pain in my stomach goes straight through to my back.',
  brief:'44-year-old man with 12 hours of severe epigastric pain radiating to the back, with vomiting, after a weekend of heavy drinking.',
  vitals:{hr:112, sbp:132, dbp:84, rr:20, spo2:96, temp:37.9, o2:'RA'},
  hist:{
    hpi:'It started last night and keeps getting worse. Sharp, right in the middle, boring into my back. Leaning forward helps a little.',
    gi:'I’ve thrown up six times. Nothing stays down.',
    etoh:'About a fifth of vodka a day for years. More this weekend.',
    pmh:'Nothing. No gallstones that I know of.',
    meds:'None.',
  },
  keyHist:['etoh','hpi'],
  exam:{
    general:'Curled up on his side, sweating.',
    abd:'Severe epigastric tenderness with guarding. Hypoactive bowel sounds. No rebound.',
    skin:'No jaundice. No flank or periumbilical bruising.',
    heent:'Dry mucous membranes. Anicteric.',
  },
  keyExam:['abd'],
  tests:{
    lipase:{r:'Lipase 1,850 U/L (more than 3× the upper limit)', y:'key', w:'Pain plus lipase > 3× ULN makes the diagnosis.'},
    cmp:{r:'Na 136 · K 3.6 · BUN 22 · Cr 1.0 · Glu 168 · Ca 8.6 · AST 140 · ALT 62 · ALP 90 · T bili 0.9', y:'useful', w:'AST:ALT > 2 fits alcohol. Normal bilirubin and ALP argue against a stone.'},
    cbc:{r:'WBC 14.0 · Hct 48% · Plt 210', y:'useful', w:'Hemoconcentration predicts severity.'},
    us_ruq:{img:{type:'us', region:'ruq', f:[]}, r:'No gallstones. CBD 4 mm. Fatty liver.', y:'useful', w:'Every first episode needs a RUQ ultrasound for gallstones.'},
    tg:{r:'Triglycerides 210 mg/dL', y:'optional', w:'Rules out hypertriglyceridemia (> 1,000) as the cause.'},
    ctabd:{img:{type:'ct', region:'abd', f:['pancreatitis']}, r:'Diffusely enlarged pancreas with peripancreatic fat stranding. No necrosis.', y:'low', w:'The diagnosis was already made. Early CT is for unclear diagnoses or no improvement after 48–72 h.'},
    cxr:{img:{type:'cxr', f:[]}, r:'Normal.', y:'optional', w:'Baseline. Severe pancreatitis can cause effusions or ARDS.'},
    trop:{r:'hs-Troponin T 4 ng/L', y:'low', w:'Not an MI story.'},
    ecg:{img:{type:'ecg', f:['stach']}, r:'Sinus tachycardia 112.', y:'optional', w:'Reasonable for epigastric pain.'},
  },
  dx:'pancreatitis', dxPartial:{pud:0, cholangitis:0},
  plan:[
    {t:'Goal-directed IV lactated Ringer’s', k:'essential', w:'Early fluids are the cornerstone. Avoid overload.'},
    {t:'IV opioid analgesia', k:'essential', w:'Pain control is part of treatment.'},
    {t:'Early oral feeding as tolerated (within 24–72 h)', k:'good', w:'Early feeding protects the gut barrier.'},
    {t:'Alcohol withdrawal monitoring and thiamine', k:'good', w:'He’ll start withdrawing within a day.'},
    {t:'Alcohol cessation counseling', k:'good', w:'Prevents recurrence.'},
    {t:'Prophylactic imipenem', k:'harmful', w:'Not recommended for sterile pancreatitis, even when severe.'},
    {t:'NPO for 7 days and start TPN', k:'wrong', w:'Prolonged NPO is outdated. Enteral beats parenteral.'},
    {t:'ERCP', k:'wrong', w:'Only for gallstone pancreatitis with cholangitis or ongoing biliary obstruction.'},
  ],
  pearls:[
    'Diagnosis needs 2 of 3: typical pain, lipase > 3× ULN, imaging findings.',
    'Causes: gallstones and alcohol (most common), triglycerides > 1,000, hypercalcemia, drugs, post-ERCP, trauma.',
    'RUQ ultrasound for every first episode. CT isn’t needed early.',
    'Treat with fluids (LR), analgesia, and early feeding. Gallstone pancreatitis → cholecystectomy in the same admission.',
    'Severity markers: persistent organ failure > 48 h, BUN rising, Hct > 44%, SIRS.',
  ],
  target:{min:60, cost:700},
},
{
  id:'cholangitis', subject:'GI', tier:2, tierWhy:'Sepsis from a source that needs a procedure.',
  bed:'ED 12', setting:'Emergency Dept', name:'Margaret Liu', age:71, sex:'F',
  look:{skin:'#e6c39c', hair:'#cfcfcf', sex:'F', habitus:'normal', jaundice:.75, sweat:true},
  cc:'I’ve had chills and pain under my right ribs, and my eyes turned yellow.',
  brief:'71-year-old woman with a day of fever, rigors, and right upper quadrant pain. Her daughter noticed yellow eyes.',
  vitals:{hr:116, sbp:94, dbp:56, rr:22, spo2:95, temp:39.2, o2:'RA'},
  decline:{by:150, to:{hr:128, sbp:80, dbp:46}},
  events:[{at:90, text:'BP is 84/50. She’s more confused.'}],
  hist:{
    hpi:'Yesterday I started shaking with chills. There’s pain under my right ribs. Today my daughter said my eyes look yellow.',
    gi:'Light-colored stools.',
    gu:'My urine is dark, like tea.',
    pmh:'An ultrasound 2 years ago found gallstones. I never had surgery.',
    meds:'Amlodipine.',
    fever:'Shaking chills, 103 at home.',
  },
  keyHist:['pmh','hpi'],
  exam:{
    general:'Ill-appearing, a little confused about the date.',
    heent:'Scleral icterus.',
    abd:'RUQ tenderness. Murphy sign negative. No rebound.',
    skin:'Jaundiced. Warm and flushed.',
  },
  keyExam:['heent','abd'],
  tests:{
    cmp:{r:'Na 136 · K 3.9 · Cr 1.4 · Glu 140 · T bili 5.8 (direct 4.6) · ALP 410 · AST 180 · ALT 210', y:'key', w:'Cholestatic pattern with conjugated hyperbilirubinemia.'},
    cbc:{r:'WBC 19.6 (12% bands) · Hgb 12.8 · Plt 180', y:'useful', w:'Leukocytosis with a left shift.'},
    us_ruq:{img:{type:'us', region:'ruq', f:['stones','cbd']}, r:'Multiple gallstones. CBD dilated to 11 mm. No gallbladder wall thickening.', y:'key', w:'Shows the obstruction.'},
    bcx:{img:{type:'gram', f:['gnr']}, r:'Gram-negative rods in 2 of 2 bottles (E. coli).', y:'useful', w:'Bacteremia is common in cholangitis.'},
    lactate:{r:'Lactate 3.2 mmol/L', y:'useful', w:'Hypoperfusion.'},
    pt:{r:'INR 1.3', y:'optional', w:'Mildly elevated. Check before ERCP.'},
    lipase:{r:'Lipase 60 U/L', y:'optional', w:'Normal. No gallstone pancreatitis.'},
    ctabd:{img:{type:'ct', region:'abd', f:['cbd']}, r:'Dilated CBD to 11 mm. Cholelithiasis.', y:'low', w:'Ultrasound already showed the dilated duct.'},
  },
  dx:'cholangitis', dxPartial:{cholecystitis:15, pancreatitis:0},
  plan:[
    {t:'Blood cultures, then broad-spectrum IV antibiotics (e.g., piperacillin-tazobactam)', k:'essential', w:'Gram-negative and anaerobic coverage within the hour.'},
    {t:'30 mL/kg IV crystalloid', k:'essential', w:'She’s hypotensive.'},
    {t:'Urgent ERCP for biliary decompression', k:'essential', w:'Source control. Within 24 h, sooner if septic.'},
    {t:'Norepinephrine if MAP < 65 after fluids', k:'good', w:'First-line vasopressor.'},
    {t:'Cholecystectomy after recovery', k:'good', w:'Prevents recurrence.'},
    {t:'Emergency open cholecystectomy now', k:'wrong', w:'The stone is in the CBD. ERCP decompresses it with less risk.'},
    {t:'Oral antibiotics and outpatient follow-up', k:'harmful', w:'She’s septic.'},
    {t:'HIDA scan', k:'wrong', w:'For suspected cholecystitis when ultrasound is equivocal.'},
  ],
  pearls:[
    'Charcot triad: fever, RUQ pain, jaundice. Reynolds pentad adds hypotension and confusion.',
    'Treat with antibiotics plus ERCP drainage.',
    'Cholecystitis: Murphy sign, fever, usually no jaundice. Ultrasound shows wall thickening and pericholecystic fluid → cholecystectomy.',
    'Choledocholithiasis without infection → ERCP. HIDA when ultrasound is equivocal for cholecystitis.',
  ],
  target:{min:80, cost:900},
},
{
  id:'sbp', subject:'GI', tier:2, tierWhy:'Three problems in one cirrhotic patient.',
  bed:'Ward 5C', setting:'Medicine ward', name:'Gerald Pike', age:57, sex:'M',
  look:{skin:'#dcb092', hair:'#7a6a5a', sex:'M', habitus:'thin', jaundice:.5, ascites:true},
  cc:'Sister: “His belly is bigger, it hurts, and he’s been confused.”',
  brief:'57-year-old man with alcohol-related cirrhosis and ascites. His sister brought him in for 2 days of abdominal pain and confusion.',
  vitals:{hr:102, sbp:98, dbp:60, rr:18, spo2:96, temp:38.1, o2:'RA'},
  histDefault:'He mumbles something unrelated. His sister answers for him.',
  hist:{
    hpi:'Sister: “He’s been sleepy and mixed up for two days. He says his belly hurts all over.”',
    pmh:'Sister: “Cirrhosis from drinking. Fluid in his belly. He’s never had a bleed.”',
    meds:'Sister: “Spironolactone and furosemide. Lactulose too, but he stopped taking it.”',
    etoh:'Sister: “He quit drinking six months ago.”',
    gi:'Sister: “He hasn’t had a bowel movement in three days.”',
  },
  keyHist:['meds','pmh'],
  exam:{
    general:'Drowsy but arousable. Oriented to person only.',
    heent:'Scleral icterus.',
    abd:'Tense, distended abdomen with shifting dullness. Diffuse mild tenderness.',
    hands:'Asterixis. Palmar erythema.',
    skin:'Jaundiced. Spider angiomas on the chest.',
    neuro:'Asterixis. No focal deficits.',
  },
  keyExam:['abd','hands'],
  tests:{
    para:{r:'Cloudy fluid. PMN 650 cells/µL. Total protein 0.9 g/dL. Albumin 0.8 g/dL (serum 2.4 → SAAG 1.6). Gram stain negative. Culture pending.', y:'key', w:'PMN ≥ 250 = SBP. SAAG ≥ 1.1 = portal hypertension.'},
    cmp:{r:'Na 129 · K 3.6 · BUN 28 · Cr 1.6 (baseline 0.9) · T bili 4.2 · Alb 2.4 · AST 68 · ALT 30', y:'key', w:'AKI and bilirubin > 4 are indications for albumin.'},
    cbc:{r:'WBC 11.2 · Hgb 10.8 · Plt 72', y:'useful', w:'Thrombocytopenia from portal hypertension.'},
    pt:{r:'INR 2.0', y:'useful', w:'Synthetic dysfunction. Not a contraindication to paracentesis.'},
    nh3:{r:'Ammonia 118 µmol/L', y:'low', w:'Hepatic encephalopathy is a clinical diagnosis. Levels don’t guide treatment.'},
    us_ruq:{img:{type:'us', region:'ruq', f:['ascites']}, r:'Large-volume ascites. Coarse, nodular liver. No gallstones.', y:'optional', w:'Can guide the paracentesis.'},
    bcx:{r:'Drawn. Pending.', y:'optional', w:'Reasonable with a fever.'},
    ctabd:{img:{type:'ct', region:'abd', f:['ascites','nodularliver','splenomeg']}, r:'Small, nodular liver. Large ascites. Splenomegaly.', y:'low', w:'Paracentesis answers the question.'},
    cthead:{img:{type:'ct', region:'head', f:[]}, r:'No hemorrhage.', y:'optional', w:'Reasonable in a coagulopathic patient with confusion, especially after a fall.'},
    ua:{r:'Bland. No infection.', y:'optional', w:'Part of the infection search.'},
  },
  dx:'sbp', dxPartial:{he:15, hrs:10},
  plan:[
    {t:'IV ceftriaxone (or cefotaxime)', k:'essential', w:'Treats SBP.'},
    {t:'IV albumin 1.5 g/kg on day 1 and 1 g/kg on day 3', k:'essential', w:'Prevents hepatorenal syndrome when Cr > 1, BUN > 30, or bilirubin > 4.'},
    {t:'Lactulose titrated to 2–3 soft stools a day (± rifaximin)', k:'essential', w:'Treats the hepatic encephalopathy.'},
    {t:'Hold diuretics during the AKI', k:'good', w:'Diuretics worsen prerenal physiology.'},
    {t:'Long-term SBP prophylaxis after recovery (ciprofloxacin or TMP-SMX)', k:'good', w:'Recurrence is common.'},
    {t:'Refer for liver transplant evaluation', k:'good', w:'Decompensated cirrhosis.'},
    {t:'FFP and vitamin K before the paracentesis', k:'wrong', w:'Paracentesis is safe despite an elevated INR.'},
    {t:'Lorazepam for agitation', k:'harmful', w:'Benzodiazepines worsen hepatic encephalopathy.'},
    {t:'Large-volume paracentesis now without albumin', k:'wrong', w:'Risks circulatory dysfunction and worsens AKI.'},
  ],
  pearls:[
    'Do a diagnostic paracentesis in every cirrhotic patient admitted with ascites.',
    'SBP: ascitic PMN ≥ 250. Treat with a 3rd-generation cephalosporin plus albumin.',
    'SAAG ≥ 1.1 = portal hypertension. < 1.1 = peritoneal disease (cancer, TB) or nephrotic syndrome.',
    'Hepatic encephalopathy: find the trigger (infection, bleeding, constipation, sedatives, hypokalemia). Treat with lactulose ± rifaximin.',
    'Prophylaxis after a first SBP episode, or during a GI bleed (ceftriaxone).',
  ],
  target:{min:90, cost:1000},
}
);
