"use strict";
/* Cases built around triage judgment (watchful waiting through emergent) and gait/neurologic exams. */
CASES.push(
{
  id:'nodule', subject:'Pulm', tier:2, tierWhy:'The skill is restraint: knowing when not to chase a finding.',
  care:'Outpatient', bed:'Clinic 5', setting:'Primary care clinic', name:'Grace Okonkwo', age:58, sex:'F',
  look:{skin:'#5e3b28', hair:'#1a1410', sex:'F', habitus:'normal'},
  cc:'My ER doctor said my CT showed a spot on my lung. Do I have cancer?',
  brief:'58-year-old woman seen 2 weeks after an ED visit for a kidney stone. The CT incidentally showed a 7-mm solid nodule in the right lower lobe. She feels well.',
  vitals:{hr:72, sbp:124, dbp:78, rr:14, spo2:98, temp:36.8, o2:'RA'},
  hist:{
    hpi:'I feel completely fine. The kidney stone passed. They just mentioned a spot on my lung.',
    smoke:'Never smoked. Nobody smoked at home.',
    expo:'Librarian. No asbestos. Our basement was tested for radon, and it was fine.',
    fhx:'No lung cancer in the family.',
    wt:'No weight loss.',
    cough:'No cough or blood.',
    travel:'I grew up in Ohio near the river.',
    pmh:'Kidney stones. Otherwise healthy.',
  },
  keyHist:['smoke','fhx','hpi'],
  exam:{ general:'Well-appearing.', neck:'No lymphadenopathy.', hands:'No clubbing.' },
  keyExam:[],
  tests:{
    priorct:{img:{type:'ct', region:'chest', f:['nodule']}, r:'7-mm smooth, solid nodule in the right lower lobe. No calcification. No adenopathy. No prior chest imaging for comparison.', y:'key', w:'Size, density, and margins drive the follow-up plan.'},
    pet:{r:'No FDG uptake (below reliable resolution).', y:'low', w:'PET isn’t reliable for nodules under 8 mm and isn’t indicated for a small low-risk nodule.'},
    ct:{img:{type:'ct', region:'chest', f:['nodule']}, r:'Unchanged 7-mm nodule.', y:'low', w:'Repeating CT 2 weeks later adds radiation without new information. The interval is 6–12 months.'},
    cxr:{img:{type:'cxr', f:[]}, r:'Normal. Nodule not visible.', y:'low', w:'Too small to follow on X-ray.'},
    bronch:{r:'Normal airways. Nondiagnostic.', y:'harmful', w:'Invasive and very low yield for a small peripheral nodule.'},
    cbc:{r:'Normal.', y:'low', w:'Doesn’t change the plan.'},
    cea:{r:'CEA 1.6 ng/mL', y:'low', w:'Not a screening or diagnostic test for nodules.'},
  },
  dx:'nodule', dxPartial:{adeno:5},
  acuity:{level:'watch', partial:['routine'], why:'Low-risk patient with a solid 6–8 mm nodule: CT in 6–12 months (Fleischner). Nothing urgent.'},
  plan:[
    {t:'Repeat chest CT in 6–12 months', k:'essential', w:'Fleischner guidance for a solid 6–8 mm nodule in a low-risk patient.'},
    {t:'Explain the plan and the low cancer risk', k:'good', w:'Most nodules this size are benign (often old granulomas).'},
    {t:'Consider another CT at 18–24 months if unchanged', k:'good', w:'Two years of stability in a solid nodule suggests it’s benign.'},
    {t:'PET-CT now', k:'wrong', w:'For solid nodules > 8 mm.'},
    {t:'CT-guided biopsy', k:'harmful', w:'Risk of pneumothorax for a low-probability lesion.'},
    {t:'Surgical wedge resection', k:'harmful', w:'Not indicated without growth or high-risk features.'},
    {t:'No follow-up needed', k:'wrong', w:'No follow-up is only for nodules < 6 mm in low-risk patients.'},
    {t:'Repeat CT in 3 months', k:'wrong', w:'The 3-month interval is for solid nodules > 8 mm.'},
  ],
  approach:[
    {t:'Look at the actual images and report: size, solid vs subsolid, margins, calcification.', do:['test:priorct']},
    {t:'Estimate risk: age, smoking, exposures, family history, nodule features.', do:['hx:smoke','hx:fhx']},
    {t:'Apply Fleischner: low-risk, solid, 6–8 mm → CT in 6–12 months.'},
    {t:'Avoid PET, biopsy, and surgery for a small low-risk nodule.'},
    {t:'Explain the plan and book the follow-up scan.'},
  ],
  pearls:[
    'Fleischner (solid, single): < 6 mm → no routine follow-up (low risk). 6–8 mm → CT at 6–12 months, then consider 18–24. > 8 mm → CT at 3 months, PET-CT, or tissue.',
    'Benign features: central, diffuse, laminated, or popcorn calcification; solid nodule stable for 2 years.',
    'Higher risk: larger size, spiculation, upper lobe, smoking, older age, emphysema, family history.',
    'Lung cancer screening: ages 50–80, ≥ 20 pack-years, current smoker or quit within 15 years → yearly low-dose CT.',
  ],
  target:{min:30, cost:150},
},
{
  id:'bronchitis', subject:'Pulm', tier:1, tierWhy:'Very common, and the antibiotic request is the trap.',
  care:'Outpatient', bed:'Clinic 6', setting:'Primary care clinic', name:'Ethan Park', age:34, sex:'M',
  look:{skin:'#e9c9a4', hair:'#141010', sex:'M', habitus:'normal'},
  cc:'I’ve had this cough for ten days. Can I get a Z-Pack before my work trip?',
  brief:'34-year-old man with 10 days of cough after a cold. He wants antibiotics before he travels.',
  vitals:{hr:76, sbp:122, dbp:78, rr:14, spo2:99, temp:37.0, o2:'RA'},
  hist:{
    hpi:'It started with a runny nose and sore throat. That’s gone, but the cough hangs on. Sometimes yellow phlegm.',
    cough:'Hacking cough, worse at night. Yellow phlegm sometimes. No blood. Not short of breath.',
    fever:'A low fever the first two days. None since.',
    smoke:'Never.',
    pmh:'Healthy. No asthma.',
    meds:'Cough drops.',
    travel:'My kids had the same cold.',
  },
  keyHist:['fever','cough'],
  exam:{
    general:'Well-appearing. Coughs occasionally.',
    heent:'Mild nasal congestion. Normal throat.',
    lungR:'Clear. No crackles, dullness, or egophony. A few rhonchi that clear with coughing.',
    lungL:'Clear. No crackles, dullness, or egophony.',
  },
  keyExam:['lungR','lungL'],
  tests:{
    cxr:{img:{type:'cxr', f:[]}, r:'Normal.', y:'low', w:'Normal vitals and a normal lung exam make pneumonia very unlikely. No X-ray needed.'},
    resp:{r:'Rhinovirus detected.', y:'low', w:'Doesn’t change management.'},
    sputum:{r:'Mixed flora.', y:'low', w:'Not useful in acute bronchitis.'},
    pct:{r:'Procalcitonin 0.04 ng/mL', y:'low', w:'Not needed when the clinical picture is clear.'},
    cbc:{r:'Normal.', y:'low', w:'Doesn’t change management.'},
    ct:{img:{type:'ct', region:'chest', f:[]}, r:'Normal.', y:'harmful', w:'Radiation and cost for a self-limited illness.'},
  },
  dx:'bronchitis', dxPartial:{cap:0, asthma:0},
  acuity:{level:'watch', partial:['routine'], why:'Self-limited viral illness with normal vitals and exam: reassure and give return precautions.'},
  plan:[
    {t:'Reassure: the cough can last up to 3 weeks; no antibiotics', k:'essential', w:'Acute bronchitis is almost always viral.'},
    {t:'Symptom relief (honey, fluids, dextromethorphan or guaifenesin)', k:'good', w:'Comfort while it resolves.'},
    {t:'Return if fever, shortness of breath, or cough beyond 3–8 weeks', k:'good', w:'Safety-netting.'},
    {t:'Albuterol inhaler if he’s wheezing', k:'ok', w:'Reasonable for wheeze. He isn’t wheezing.'},
    {t:'Azithromycin (Z-Pack)', k:'harmful', w:'Doesn’t shorten the illness. Causes side effects, QT risk, and resistance.'},
    {t:'Chest X-ray “to be safe”', k:'wrong', w:'Normal vitals and exam → no imaging.'},
    {t:'Oral steroids', k:'wrong', w:'No benefit in acute bronchitis without asthma.'},
  ],
  approach:[
    {t:'Check vitals and do a focused lung exam. Normal findings argue strongly against pneumonia.', do:['ex:lungR','ex:lungL']},
    {t:'Ask about red flags: high fever, dyspnea, hemoptysis, weight loss, whooping paroxysms.', do:['hx:fever','hx:cough']},
    {t:'With normal vitals and exam, skip imaging and antibiotics.'},
    {t:'Explain the natural course and when to come back.'},
  ],
  pearls:[
    'Acute bronchitis: viral, cough up to 3 weeks. Colored sputum doesn’t mean bacterial infection.',
    'Get a CXR if HR > 100, RR > 24, temp > 38 °C, or focal lung findings (or older patients with atypical signs).',
    'Pertussis: paroxysms, post-tussive vomiting, whoop → azithromycin and treat contacts.',
    'Chronic cough (> 8 weeks): upper-airway cough syndrome, asthma, GERD, ACE inhibitors.',
  ],
  target:{min:12, cost:40},
},
{
  id:'subhypo', subject:'Endo', tier:1, tierWhy:'A common lab finding where monitoring beats treatment.',
  care:'Outpatient', bed:'Clinic 7', setting:'Primary care clinic', name:'Rachel Stein', age:45, sex:'F',
  look:{skin:'#efd2bc', hair:'#6b4a2f', sex:'F', habitus:'normal'},
  cc:'My annual labs showed my thyroid was “a little off.”',
  brief:'45-year-old woman referred after routine labs showed a TSH of 7.2. She isn’t pregnant and has no plans to be.',
  vitals:{hr:70, sbp:118, dbp:76, rr:14, spo2:99, temp:36.7, o2:'RA'},
  hist:{
    hpi:'I feel pretty normal. Maybe a little tired, but I have two teenagers.',
    wt:'Stable.',
    meds:'A multivitamin with biotin for my hair and nails.',
    fhx:'My mom has Hashimoto’s.',
    sex:'Not pregnant. I have an IUD.',
    ros:'No cold intolerance, constipation, dry skin, or hair loss.',
    pmh:'Nothing.',
  },
  keyHist:['meds','sex','ros'],
  exam:{ neck:'Thyroid normal size. No nodules.', neuro:'Normal reflexes with normal relaxation.', skin:'Normal.' },
  keyExam:['neck'],
  tests:{
    tsh:{r:'TSH 6.8 mIU/L · Free T4 1.0 ng/dL (normal)', y:'key', w:'A repeat TSH with free T4 confirms subclinical hypothyroidism. Single values fluctuate.'},
    tpo:{r:'TPO antibodies positive (high titer)', y:'useful', w:'Predicts progression to overt hypothyroidism (about 4% a year).'},
    usthy:{r:'Mildly heterogeneous gland. No nodules.', y:'low', w:'No nodule on exam. Ultrasound isn’t indicated.'},
    cbc:{r:'Normal.', y:'low', w:'Doesn’t change the plan.'},
    cmp:{r:'Normal.', y:'low', w:'Doesn’t change the plan.'},
    hcg:{r:'Negative', y:'optional', w:'Pregnancy would change the plan, but she has an IUD.'},
  },
  dx:'subhypo', dxPartial:{hypothyroid:5},
  acuity:{level:'watch', partial:['routine'], why:'TSH < 10, normal free T4, no pregnancy plans, minimal symptoms → monitor.'},
  plan:[
    {t:'No levothyroxine now; recheck TSH and free T4 in 6–12 months', k:'essential', w:'Treatment doesn’t help most patients with TSH < 10.'},
    {t:'Stop biotin 2–3 days before thyroid labs', k:'good', w:'Biotin interferes with many immunoassays.'},
    {t:'Treat if TSH ≥ 10, pregnancy is planned, or symptoms are clear', k:'good', w:'The usual thresholds for treatment.'},
    {t:'Start levothyroxine 100 mcg', k:'wrong', w:'Not indicated at this TSH without pregnancy or clear symptoms.'},
    {t:'Thyroid ultrasound', k:'wrong', w:'No nodule.'},
    {t:'Radioactive iodine uptake scan', k:'wrong', w:'For hyperthyroidism, not hypothyroidism.'},
  ],
  approach:[
    {t:'Repeat TSH with free T4 before labeling anything.', do:['test:tsh']},
    {t:'Look for interference and context: biotin, recent illness, pregnancy plans.', do:['hx:meds','hx:sex']},
    {t:'Check TPO antibodies to estimate progression risk.', do:['test:tpo']},
    {t:'TSH < 10, not pregnant, few symptoms → monitor.'},
  ],
  pearls:[
    'Subclinical hypothyroidism: high TSH, normal free T4. Confirm with a repeat in 6–12 weeks.',
    'Treat if TSH ≥ 10, pregnancy or trying to conceive, or (individualized) symptoms or positive TPO.',
    'Over 70, a TSH up to ~7 can be normal.',
    'Biotin can falsely change thyroid tests. Stop it before testing.',
    'Overt hypothyroidism: high TSH, low free T4 → levothyroxine (start low in elderly patients or those with CAD).',
  ],
  target:{min:1500, cost:250},
},
{
  id:'gallstones', subject:'GI', tier:1, tierWhy:'An incidental finding with a classic “don’t operate” answer.',
  care:'Outpatient', bed:'Clinic 8', setting:'Primary care clinic', name:'Patricia Long', age:52, sex:'F',
  look:{skin:'#e8c3a7', hair:'#8a5a32', sex:'F', habitus:'heavy'},
  cc:'An ultrasound found gallstones. Do I need my gallbladder out?',
  brief:'52-year-old woman whose ultrasound to follow a kidney cyst showed gallstones. She has never had abdominal pain.',
  vitals:{hr:74, sbp:128, dbp:80, rr:14, spo2:99, temp:36.8, o2:'RA'},
  hist:{
    hpi:'I’ve never had belly pain. Fatty meals don’t bother me.',
    gi:'No pain, nausea, yellow eyes, or light stools.',
    pmh:'A simple kidney cyst they’re watching. Weight is my main issue.',
    fhx:'My sister had her gallbladder out.',
    wt:'Trying to lose weight. Slowly.',
    meds:'None.',
  },
  keyHist:['hpi','gi'],
  exam:{ abd:'Soft, nontender. Murphy sign negative. No hepatomegaly.', heent:'Anicteric.' },
  keyExam:['abd'],
  tests:{
    us_ruq:{img:{type:'us', region:'ruq', f:['stones']}, r:'Several mobile gallstones. Normal wall thickness. No pericholecystic fluid. CBD 4 mm.', y:'key', w:'Confirms uncomplicated stones: normal wall and duct.'},
    cmp:{r:'AST 21 · ALT 18 · ALP 76 · T bili 0.5', y:'useful', w:'Normal LFTs make a duct stone unlikely.'},
    hida:{r:'Normal gallbladder filling.', y:'low', w:'HIDA is for suspected acute cholecystitis.'},
    mrcp:{r:'Normal ducts.', y:'low', w:'No duct dilation or abnormal LFTs to justify it.'},
    lipase:{r:'Lipase 30 U/L', y:'low', w:'No pain.'},
    ctabd:{img:{type:'ct', region:'abd', f:[]}, r:'No acute abnormality.', y:'low', w:'Ultrasound is better for stones.'},
  },
  dx:'gallstones', dxPartial:{cholecystitis:0},
  acuity:{level:'watch', partial:['routine'], why:'Asymptomatic stones: expectant management. Only 1–2% a year become symptomatic.'},
  plan:[
    {t:'No surgery; observe', k:'essential', w:'Prophylactic cholecystectomy isn’t recommended for asymptomatic stones.'},
    {t:'Teach the symptoms of biliary colic and when to return', k:'good', w:'Surgery once symptoms start.'},
    {t:'Gradual weight loss (avoid very rapid loss)', k:'good', w:'Rapid weight loss promotes new stones.'},
    {t:'Elective cholecystectomy', k:'wrong', w:'Reserved for symptoms or special cases (porcelain gallbladder, stones > 3 cm, polyps ≥ 1 cm).'},
    {t:'Ursodiol', k:'wrong', w:'Slow, often ineffective, and stones recur.'},
    {t:'ERCP', k:'harmful', w:'Pancreatitis and perforation risk with no indication.'},
  ],
  approach:[
    {t:'Confirm there has never been biliary colic.', do:['hx:hpi','hx:gi']},
    {t:'Examine for RUQ tenderness and jaundice.', do:['ex:abd']},
    {t:'Check the ultrasound for complications and LFTs for duct stones.', do:['test:us_ruq','test:cmp']},
    {t:'Asymptomatic stones → no surgery. Teach the warning symptoms.'},
  ],
  pearls:[
    'Asymptomatic gallstones → expectant management.',
    'Biliary colic → elective cholecystectomy. Cholecystitis → antibiotics + early cholecystectomy.',
    'Risk factors: female, age > 40, obesity, pregnancy, rapid weight loss, TPN, octreotide, ceftriaxone.',
    'Choledocholithiasis: abnormal LFTs or a dilated duct → MRCP or ERCP.',
  ],
  target:{min:4500, cost:400},
},
{
  id:'mgus', subject:'Heme/Onc', tier:2, tierWhy:'Telling a premalignant finding from cancer.',
  care:'Outpatient', bed:'Clinic 9', setting:'Hematology clinic', name:'Howard Ellis', age:66, sex:'M',
  look:{skin:'#e6c2a5', hair:'#bfbfbf', sex:'M', habitus:'normal'},
  cc:'My doctor said my blood protein was high and sent me here.',
  brief:'66-year-old man referred because routine labs showed total protein of 8.9 g/dL with a normal albumin. He feels well.',
  vitals:{hr:70, sbp:130, dbp:80, rr:14, spo2:98, temp:36.7, o2:'RA'},
  hist:{
    hpi:'I feel fine. I golf three times a week.',
    wt:'Stable.',
    fever:'No fevers. No recurring infections.',
    ros:'No bone pain.',
    pmh:'High cholesterol.',
    meds:'Atorvastatin.',
  },
  keyHist:['ros','fever'],
  exam:{ back:'No spinal tenderness.', general:'Well.' },
  keyExam:[],
  tests:{
    spep:{r:'IgG kappa M-spike 1.2 g/dL. Free light chain ratio 1.4 (normal).', y:'key', w:'Defines a low-risk MGUS (IgG, < 1.5 g/dL, normal ratio).'},
    cmp:{r:'Ca 9.4 · Cr 0.9 · Total protein 8.9 · Albumin 4.2', y:'key', w:'No hypercalcemia or kidney injury.'},
    cbc:{r:'Hgb 14.6 · WBC 6.2 · Plt 230', y:'key', w:'No anemia.'},
    skel:{r:'No lytic lesions.', y:'low', w:'Not required for low-risk MGUS without bone symptoms.'},
    bmbx:{r:'6% plasma cells.', y:'harmful', w:'Not needed for low-risk MGUS.'},
    smear:{img:{type:'smear', f:[]}, r:'Normal.', y:'low', w:'No rouleaux expected at this level.'},
    ua:{r:'Normal.', y:'optional', w:'Reasonable kidney screen.'},
  },
  dx:'mgus', dxPartial:{myeloma:5},
  acuity:{level:'watch', partial:['routine'], why:'Low-risk MGUS: monitor. About 1% a year progress.'},
  plan:[
    {t:'Repeat SPEP, CBC, calcium, and creatinine in 6 months, then yearly if stable', k:'essential', w:'Standard surveillance.'},
    {t:'Teach the warning symptoms (bone pain, fatigue, infections)', k:'good', w:'Earlier detection of progression.'},
    {t:'Start chemotherapy', k:'harmful', w:'MGUS isn’t treated.'},
    {t:'Bone marrow biopsy', k:'wrong', w:'Only for intermediate or high-risk MGUS, or CRAB features.'},
    {t:'No follow-up needed', k:'wrong', w:'Lifelong risk of progression.'},
    {t:'Start a bisphosphonate', k:'wrong', w:'No bone disease.'},
  ],
  approach:[
    {t:'Quantify the M-protein and its type with SPEP, immunofixation, and free light chains.', do:['test:spep']},
    {t:'Screen for end-organ damage (CRAB): calcium, creatinine, hemoglobin, bone pain.', do:['test:cmp','test:cbc','hx:ros']},
    {t:'Low-risk features → no marrow or skeletal survey.'},
    {t:'Monitor at 6 months, then yearly.'},
  ],
  pearls:[
    'MGUS: M-protein < 3 g/dL, clonal plasma cells < 10%, no CRAB or SLiM features.',
    'Low risk: IgG type, < 1.5 g/dL, normal free light chain ratio.',
    'Smoldering myeloma: M ≥ 3 g/dL or 10–60% plasma cells, still no CRAB.',
    'Myeloma: CRAB, or SLiM (≥ 60% plasma cells, light chain ratio ≥ 100, > 1 focal MRI lesion).',
  ],
  target:{min:3000, cost:500},
},
{
  id:'hyperpth', subject:'Endo', tier:2, tierWhy:'Knowing the surgery criteria, and when they aren’t met.',
  care:'Outpatient', bed:'Clinic 10', setting:'Endocrine clinic', name:'Carol Benson', age:68, sex:'F',
  look:{skin:'#efd6c3', hair:'#d6d6d6', sex:'F', habitus:'thin'},
  cc:'My calcium has been a little high on a few blood tests.',
  brief:'68-year-old woman with calcium between 10.5 and 10.7 mg/dL on three checks over a year. No symptoms.',
  vitals:{hr:68, sbp:126, dbp:76, rr:14, spo2:98, temp:36.6, o2:'RA'},
  hist:{
    hpi:'I feel fine. They keep calling about my calcium.',
    gu:'No kidney stones, ever.',
    gi:'No constipation or belly pain.',
    neuro:'No confusion. My memory is good.',
    meds:'Calcium and vitamin D supplements. No water pills, no lithium.',
    pmh:'Osteopenia on a scan 3 years ago.',
    fhx:'No family calcium problems.',
  },
  keyHist:['meds','gu'],
  exam:{ back:'No vertebral tenderness.', general:'Well.' },
  keyExam:[],
  tests:{
    pth:{r:'Calcium 10.6 mg/dL · Intact PTH 88 pg/mL (high) · PTHrP undetectable', y:'key', w:'High calcium with a high (not suppressed) PTH = primary hyperparathyroidism.'},
    cmp:{r:'Ca 10.6 · Alb 4.1 · Cr 0.8 (eGFR 75) · Phos 2.6', y:'useful', w:'Kidney function is part of the surgery criteria.'},
    vitd:{r:'25-OH vitamin D 34 ng/mL', y:'useful', w:'Vitamin D deficiency causes secondary hyperparathyroidism. Replete before interpreting.'},
    ucal:{r:'24-h urine calcium 210 mg. Calcium/creatinine clearance ratio 0.02.', y:'key', w:'Excludes FHH (ratio < 0.01) and checks for hypercalciuria (> 400 mg/day).'},
    dexa:{r:'T-scores: lumbar −1.6, hip −1.8, distal radius −2.0 (osteopenia).', y:'key', w:'Osteoporosis (≤ −2.5) would be a surgical indication.'},
    us_renal:{img:{type:'us', region:'renal', f:[]}, r:'No stones or nephrocalcinosis.', y:'useful', w:'Silent stones are a surgical indication.'},
    sestamibi:{r:'Focal uptake behind the left lower thyroid lobe.', y:'low', w:'Localization is for surgical planning once surgery is chosen. It doesn’t diagnose.'},
  },
  dx:'hyperpth', dxPartial:{fhh:5, myeloma:0},
  acuity:{level:'watch', partial:['routine'], why:'Asymptomatic, and no surgical criteria are met: monitor.'},
  plan:[
    {t:'Monitor: calcium and creatinine yearly, DEXA every 1–2 years', k:'essential', w:'Surgery if a criterion develops.'},
    {t:'Normal dietary calcium, hydration, avoid thiazides and lithium', k:'good', w:'Don’t restrict calcium; avoid things that raise it.'},
    {t:'Parathyroidectomy now', k:'wrong', w:'No criteria: age ≥ 50, Ca < 1 above normal, no osteoporosis, eGFR ≥ 60, no stones or hypercalciuria.'},
    {t:'Sestamibi scan now', k:'wrong', w:'Only for surgical planning.'},
    {t:'Cinacalcet', k:'wrong', w:'For patients who need treatment but can’t have surgery.'},
    {t:'Low-calcium diet', k:'harmful', w:'Raises PTH further and worsens bone loss.'},
  ],
  approach:[
    {t:'Confirm PTH-dependent hypercalcemia with an intact PTH.', do:['test:pth']},
    {t:'Exclude mimics: thiazides, lithium, vitamin D deficiency, FHH (24-h urine calcium).', do:['hx:meds','test:vitd','test:ucal']},
    {t:'Check end-organ criteria: bone density, kidney function, stones.', do:['test:dexa','test:cmp','test:us_renal']},
    {t:'No criteria → monitor. Refer for surgery if any criterion appears.'},
  ],
  pearls:[
    'Surgery if any: symptoms, Ca > 1 mg/dL above normal, age < 50, T-score ≤ −2.5 or vertebral fracture, eGFR < 60, stones or nephrocalcinosis, urine Ca > 400 mg/day.',
    'FHH: calcium/creatinine clearance ratio < 0.01. Benign, no surgery.',
    'Symptoms: stones, bones, groans, thrones, psychiatric overtones.',
    'Secondary hyperparathyroidism: vitamin D deficiency or CKD (calcium normal or low).',
  ],
  target:{min:11000, cost:900},
},
{
  id:'mskcp', subject:'Cardio', tier:2, tierWhy:'Safely sending a chest pain patient home.',
  care:'ED', bed:'ED 24', setting:'Emergency Dept', name:'Sofia Marino', age:38, sex:'F',
  look:{skin:'#e3b994', hair:'#2a1a12', sex:'F', habitus:'normal'},
  cc:'My chest hurts when I take a deep breath or twist.',
  brief:'38-year-old woman with 2 days of left-sided chest pain that started after she helped a friend move.',
  vitals:{hr:78, sbp:124, dbp:76, rr:16, spo2:99, temp:36.8, o2:'RA'},
  hist:{
    hpi:'It started the day after I helped move a couch. Sharp, on the left side, when I twist or press there.',
    cp:'Sharp, lasting seconds to hours. Worse when I press on it or twist. Not with walking or stairs.',
    pmh:'Healthy.',
    meds:'Birth control pills.',
    smoke:'Never.',
    fhx:'No early heart disease.',
    immob:'No travel or leg swelling.',
    cough:'No cough or shortness of breath.',
  },
  keyHist:['cp','meds','fhx'],
  exam:{
    general:'Comfortable.',
    heart:'Normal heart sounds. No rub. Pressing on the left 4th and 5th costochondral junctions reproduces her pain exactly.',
    lungR:'Clear.', lungL:'Clear.',
    legs:'No swelling or calf tenderness.',
  },
  keyExam:['heart'],
  tests:{
    ecg:{img:{type:'ecg', f:['nsr']}, r:'Normal sinus rhythm 78. No ST changes.', y:'key', w:'Every chest pain gets an ECG within 10 minutes.'},
    trop:{r:'hs-Troponin T < 6 ng/L at 0 h and 2 h', y:'key', w:'Two negative high-sensitivity troponins plus a low HEART score → safe discharge.'},
    ddimer:{r:'D-dimer 0.31 µg/mL FEU (negative)', y:'useful', w:'PERC fails (estrogen), but Wells is low, so a negative D-dimer rules out PE.'},
    cxr:{img:{type:'cxr', f:[]}, r:'Normal.', y:'optional', w:'Reasonable but low yield.'},
    ctpa:{img:{type:'ct', region:'chest', contrast:true, f:[]}, r:'No PE.', y:'low', w:'Low pretest probability with a negative D-dimer. CTPA adds radiation and incidental findings.'},
    stress:{r:'Negative at 11 METs.', y:'low', w:'HEART score 1. No stress test needed before discharge.'},
    ccta:{r:'Calcium score 0. No stenosis.', y:'low', w:'Not needed at this risk level.'},
    tte:{r:'Normal.', y:'low', w:'No murmur or HF signs.'},
    bnp:{r:'BNP 20 pg/mL', y:'low', w:'Not the question.'},
  },
  dx:'mskcp', dxPartial:{pericarditis:0, pe:0},
  acuity:{level:'routine', partial:['watch','soon'], why:'HEART score 1 with two negative troponins and PE ruled out → discharge with primary care follow-up.'},
  plan:[
    {t:'Discharge with NSAIDs or acetaminophen and primary care follow-up', k:'essential', w:'Low-risk chest pain is safe for outpatient care.'},
    {t:'Return for exertional pain, dyspnea, or fainting', k:'good', w:'Safety-netting.'},
    {t:'Admit for telemetry and serial troponins', k:'wrong', w:'Two negative high-sensitivity troponins already done.'},
    {t:'Stress test before discharge', k:'wrong', w:'Not needed with a low HEART score.'},
    {t:'Aspirin and heparin for possible ACS', k:'harmful', w:'Bleeding risk without ACS.'},
    {t:'CT pulmonary angiogram', k:'wrong', w:'PE excluded by D-dimer.'},
  ],
  approach:[
    {t:'ECG within 10 minutes.', do:['test:ecg']},
    {t:'Characterize the pain and risk factors to build the HEART score.', do:['hx:cp','hx:fhx','hx:smoke']},
    {t:'High-sensitivity troponin at 0 h and 1–3 h.', do:['test:trop']},
    {t:'Address PE: PERC fails (estrogen), Wells low → D-dimer.', do:['test:ddimer','hx:meds']},
    {t:'Reproduce the pain on exam, then discharge with follow-up.', do:['ex:heart']},
  ],
  pearls:[
    'HEART score (History, ECG, Age, Risk factors, Troponin): 0–3 → < 2% 6-week MACE → discharge.',
    'Reproducible chest wall pain makes ACS less likely but doesn’t rule it out alone.',
    'PERC rule (all 8 negative → no testing). Estrogen use makes PERC fail.',
    'Low Wells + negative D-dimer rules out PE.',
  ],
  target:{min:150, cost:350},
},
{
  id:'cdiff', subject:'GI', tier:2, tierWhy:'A hospital complication with severity-based treatment.',
  care:'Inpatient', bed:'Ward 6D', setting:'Medicine ward', name:'Edward Simms', age:74, sex:'M',
  look:{skin:'#e8c9b2', hair:'#d0d0d0', sex:'M', habitus:'normal', o2:'cannula'},
  cc:'I can’t stop going to the bathroom.',
  brief:'74-year-old man on hospital day 6 of ceftriaxone for pneumonia. Since yesterday he has had 8 watery stools and cramping.',
  vitals:{hr:104, sbp:118, dbp:70, rr:18, spo2:95, temp:38.2, o2:'2 L NC'},
  hist:{
    hpi:'Since yesterday, watery diarrhea, eight times. My belly cramps.',
    gi:'Watery, no blood. Cramping. I’m not on any laxatives.',
    meds:'Here they give me ceftriaxone and azithromycin, and pantoprazole for my stomach.',
    pmh:'Diabetes and kidney disease.',
    fever:'Fever again since this morning.',
  },
  keyHist:['gi','meds'],
  exam:{
    general:'Tired.',
    heent:'Dry mucous membranes.',
    abd:'Mild diffuse tenderness. Active bowel sounds. Not distended. No peritoneal signs.',
  },
  keyExam:['abd'],
  tests:{
    cdiff:{r:'GDH antigen positive · Toxin A/B positive', y:'key', w:'Confirms C. difficile infection.'},
    cbc:{r:'WBC 18.4 · Hgb 12.0 · Plt 260', y:'key', w:'WBC ≥ 15,000 = severe.'},
    cmp:{r:'Na 136 · K 3.3 · Cr 1.7 (baseline 1.1) · Alb 2.8', y:'key', w:'Cr > 1.5 also marks severe disease. Replace potassium.'},
    lactate:{r:'Lactate 1.4 mmol/L', y:'useful', w:'No sign of fulminant colitis.'},
    ctabd:{img:{type:'ct', region:'abd', f:['colitis']}, r:'Diffuse colonic wall thickening. No megacolon or perforation.', y:'optional', w:'Useful if fulminant disease is suspected (ileus, distension, peritonitis).'},
    stoolcx:{r:'No enteric pathogens.', y:'low', w:'Diarrhea starting after hospital day 3 → test for C. diff, not routine stool culture.'},
    colo:{r:'Pseudomembranes.', y:'harmful', w:'Perforation risk in active colitis, and not needed for diagnosis.'},
  },
  dx:'cdiff', dxPartial:{},
  acuity:{level:'admit', partial:['now'], why:'Severe but not fulminant: start oral vancomycin today on the ward.'},
  plan:[
    {t:'Oral vancomycin (or fidaxomicin) for 10 days', k:'essential', w:'First-line for severe and nonsevere disease.'},
    {t:'Contact precautions and soap-and-water hand hygiene', k:'essential', w:'Spores resist alcohol gel.'},
    {t:'Stop antibiotics no longer needed and reassess the PPI', k:'good', w:'Removes ongoing risk factors.'},
    {t:'IV fluids and potassium replacement', k:'good', w:'Volume loss and hypokalemia.'},
    {t:'IV metronidazole alone', k:'wrong', w:'IV metronidazole is only added for fulminant disease.'},
    {t:'Loperamide for the diarrhea', k:'harmful', w:'Antimotility drugs risk toxic megacolon.'},
    {t:'Alcohol hand gel only', k:'wrong', w:'Doesn’t kill spores.'},
    {t:'Colectomy now', k:'wrong', w:'Only for fulminant or refractory disease.'},
  ],
  approach:[
    {t:'Confirm significant diarrhea (≥ 3 unformed stools in 24 h, no laxatives) and risk factors.', do:['hx:gi','hx:meds']},
    {t:'Examine for fulminant colitis: distension, peritonitis, ileus.', do:['ex:abd']},
    {t:'Send C. difficile testing.', do:['test:cdiff']},
    {t:'Grade severity with WBC and creatinine.', do:['test:cbc','test:cmp']},
    {t:'Oral vancomycin or fidaxomicin, contact precautions, stop unnecessary antibiotics.'},
  ],
  pearls:[
    'Severe = WBC ≥ 15,000 or Cr > 1.5. Treat with oral vancomycin or fidaxomicin either way.',
    'Fulminant (hypotension, ileus, megacolon): high-dose oral vancomycin + IV metronidazole (± rectal vancomycin), surgery consult.',
    'Recurrence: fidaxomicin, bezlotoxumab, or fecal microbiota transplant after multiple recurrences.',
    'Risk factors: antibiotics (clindamycin, fluoroquinolones, cephalosporins), PPIs, age, hospitalization.',
  ],
  target:{min:80, cost:350},
},
{
  id:'parkinson', subject:'Neuro', tier:2, tierWhy:'A clinical diagnosis made by watching the patient move.',
  care:'Outpatient', bed:'Clinic 11', setting:'Neurology clinic', name:'Arthur Hale', age:69, sex:'M',
  look:{skin:'#e7c4aa', hair:'#bdbdbd', sex:'M', habitus:'normal', gait:'shuffle', tremor:'rest'},
  cc:'My right hand shakes when I’m sitting still, and my wife says I’ve slowed down.',
  brief:'69-year-old man with a year of right-hand tremor at rest, slowness, and smaller handwriting.',
  vitals:{hr:72, sbp:132, dbp:80, rr:14, spo2:98, temp:36.7, o2:'RA'},
  hist:{
    hpi:'About a year ago my right hand started trembling when it rests in my lap. It stops when I reach for something. Everything takes longer, and my handwriting got tiny.',
    sleep:'My wife says I act out my dreams. I punched her once in my sleep.',
    gi:'Constipated for years.',
    ros:'I can’t smell my coffee anymore.',
    meds:'Lisinopril. Never on antipsychotics or metoclopramide.',
    neuro:'No falls yet. No hallucinations. My memory is okay.',
    fhx:'My father’s hands shook when he held a cup.',
  },
  keyHist:['hpi','meds','sleep'],
  exam:{
    general:'Reduced facial expression (hypomimia), soft voice, infrequent blinking.',
    hands:'4–5 Hz pill-rolling tremor in the right hand at rest. It disappears when he reaches for something.',
    neuro:'Cogwheel rigidity at the right wrist. Finger tapping slows and shrinks with repetition (bradykinesia), worse on the right. Normal strength, reflexes, and eye movements. No cerebellar signs.',
    gait:'Stooped posture, short shuffling steps, reduced right arm swing, turns en bloc in 4 steps. Pull test: 2 steps back, recovers.',
  },
  keyExam:['neuro','gait','hands'],
  tests:{
    mri:{r:'Normal for age.', y:'low', w:'Parkinson disease is a clinical diagnosis. MRI only for atypical features.'},
    datscan:{r:'Reduced striatal uptake, left > right.', y:'optional', w:'Only needed when it’s unclear vs essential tremor.'},
    tsh:{r:'Normal.', y:'low', w:'Doesn’t explain rigidity or bradykinesia.'},
    cerulo:{r:'Normal.', y:'low', w:'Screen for Wilson disease only in patients under 50.'},
    cthead:{img:{type:'ct', region:'head', f:[]}, r:'Normal.', y:'low', w:'Not needed.'},
    b12:{r:'Normal.', y:'low', w:'Not the picture.'},
  },
  dx:'parkinson', dxPartial:{ess:0, nph:0},
  acuity:{level:'routine', partial:['soon'], why:'Slowly progressive, no emergency. Start treatment when symptoms limit function.'},
  plan:[
    {t:'Start carbidopa-levodopa when symptoms affect daily function', k:'essential', w:'The most effective symptomatic therapy.'},
    {t:'Physical therapy and regular exercise', k:'good', w:'Improves mobility and balance.'},
    {t:'Treat constipation; screen for depression and orthostasis', k:'good', w:'Common nonmotor features.'},
    {t:'Avoid dopamine blockers (haloperidol, metoclopramide)', k:'good', w:'They worsen parkinsonism.'},
    {t:'Propranolol for the tremor', k:'wrong', w:'That treats essential tremor.'},
    {t:'Haloperidol if hallucinations develop', k:'harmful', w:'Can cause severe worsening. Use quetiapine or pimavanserin.'},
    {t:'Deep brain stimulation now', k:'wrong', w:'For motor fluctuations despite optimal medications.'},
  ],
  approach:[
    {t:'Characterize the tremor: at rest or with action?', do:['hx:hpi','ex:hands']},
    {t:'Examine for rigidity and bradykinesia.', do:['ex:neuro']},
    {t:'Watch him walk: shuffling, reduced arm swing, en bloc turns.', do:['ex:gait']},
    {t:'Rule out drug-induced parkinsonism; ask about RBD, anosmia, constipation.', do:['hx:meds','hx:sleep']},
    {t:'The diagnosis is clinical. Treat when function is affected.'},
  ],
  pearls:[
    'TRAP: Tremor at rest, Rigidity (cogwheel), Akinesia/bradykinesia, Postural instability (late).',
    'Prodrome: REM sleep behavior disorder, anosmia, constipation, depression.',
    'Essential tremor: action tremor, bilateral, better with alcohol, family history → propranolol or primidone.',
    'Red flags for Parkinson-plus: early falls and vertical gaze palsy (PSP), autonomic failure (MSA), early dementia and hallucinations (Lewy body).',
  ],
  target:{min:30, cost:100},
},
{
  id:'nph', subject:'Neuro', tier:3, tierWhy:'A reversible dementia you only catch by watching the gait.',
  care:'Outpatient', bed:'Clinic 12', setting:'Neurology clinic', name:'Lorraine Webb', age:74, sex:'F',
  look:{skin:'#efd5c2', hair:'#e2e2e2', sex:'F', habitus:'normal', gait:'magnetic'},
  cc:'Daughter: “Mom’s walking has gotten really strange, and she’s having accidents.”',
  brief:'74-year-old woman with 8 months of a worsening gait, urinary incontinence, and forgetfulness.',
  vitals:{hr:74, sbp:136, dbp:78, rr:14, spo2:97, temp:36.6, o2:'RA'},
  histDefault:'She answers slowly. Her daughter fills in.',
  hist:{
    hpi:'Daughter: “Her feet seem glued to the floor. She’s fallen twice. In the last few months she’s wet herself, and she forgets appointments.”',
    gu:'Daughter: “She can’t make it to the bathroom in time.”',
    neuro:'Daughter: “No tremor. No headaches.”',
    meds:'Daughter: “Amlodipine, and oxybutynin for the bladder, started 2 months ago.”',
    pmh:'Daughter: “High blood pressure.”',
  },
  keyHist:['hpi','gu','meds'],
  exam:{
    general:'Pleasant, a little slow to answer.',
    neuro:'Oriented to person and place. Recalls 1 of 3 words. Normal strength and sensation. No rigidity or rest tremor.',
    gait:'Wide-based, slow, short steps with feet barely leaving the floor (“magnetic”). Turning takes 6 steps. Arm swing preserved.',
  },
  keyExam:['gait','neuro'],
  tests:{
    cthead:{img:{type:'ct', region:'head', f:['vent']}, r:'Enlarged lateral and third ventricles out of proportion to sulcal atrophy (Evans index 0.36). No mass.', y:'key', w:'Ventriculomegaly is required for the diagnosis.'},
    mri:{r:'Ventriculomegaly, callosal angle 70°, tight high-convexity sulci. No obstruction.', y:'useful', w:'Supports NPH and excludes obstruction.'},
    taptest:{r:'Opening pressure 14 cm H2O. 40 mL removed. 10-m walk time 18 s → 12 s at 2 hours; fewer steps on turning.', y:'key', w:'Improvement predicts a good shunt response.'},
    b12:{r:'B12 450 pg/mL', y:'useful', w:'Part of the reversible dementia workup.'},
    tsh:{r:'Normal.', y:'useful', w:'Part of the reversible dementia workup.'},
    rpr:{r:'Nonreactive', y:'optional', w:'Some guidelines include syphilis screening.'},
    cmp:{r:'Normal.', y:'optional', w:'Baseline.'},
    datscan:{r:'Normal.', y:'low', w:'No parkinsonian features.'},
  },
  keyOneOf:[['cthead','mri']],
  dx:'nph', dxPartial:{alzheimer:5, parkinson:5},
  acuity:{level:'routine', partial:['soon'], why:'Progressive but not urgent: outpatient imaging and tap test over weeks.'},
  plan:[
    {t:'Neurosurgery referral for a ventriculoperitoneal shunt', k:'essential', w:'Gait improves most reliably.'},
    {t:'Stop oxybutynin', k:'good', w:'Anticholinergics worsen cognition.'},
    {t:'Fall-prevention physical therapy', k:'good', w:'She has already fallen twice.'},
    {t:'Donepezil as the main treatment', k:'wrong', w:'Doesn’t treat NPH.'},
    {t:'Carbidopa-levodopa', k:'wrong', w:'Not Parkinson disease.'},
  ],
  approach:[
    {t:'Take the history from family: gait first, then urine, then cognition.', do:['hx:hpi','hx:gu']},
    {t:'Watch the gait: magnetic, wide-based, slow turns.', do:['ex:gait']},
    {t:'Look for reversible causes: medications, B12, thyroid.', do:['hx:meds','test:b12','test:tsh']},
    {t:'Image the brain for ventriculomegaly.', do:['test:cthead','test:mri']},
    {t:'High-volume tap test; improvement → VP shunt.', do:['test:taptest']},
  ],
  pearls:[
    'NPH triad: wet, wobbly, wacky. Gait comes first and responds best to a shunt.',
    'Imaging: ventricles enlarged out of proportion to atrophy.',
    'Tap test or lumbar drain predicts shunt response.',
    'Reversible dementias: B12, hypothyroidism, NPH, depression, syphilis, medications.',
    'Compared with Parkinson disease: arm swing preserved, no rest tremor (“lower-body parkinsonism”).',
  ],
  target:{min:25000, cost:2500},
},
{
  id:'b12', subject:'Heme/Onc', tier:2, tierWhy:'A blood disorder that shows up as a neurologic gait.',
  care:'Outpatient', bed:'Clinic 13', setting:'Primary care clinic', name:'Nancy Feld', age:62, sex:'F',
  look:{skin:'#efdcc0', hair:'#9a7b5a', sex:'F', habitus:'normal', pallor:.35, gait:'ataxic', jaundice:.12},
  cc:'My feet feel like they’re wrapped in cotton, and I wobble in the dark.',
  brief:'62-year-old woman with 4 months of numbness and tingling in her feet and unsteadiness, worse at night.',
  vitals:{hr:92, sbp:124, dbp:76, rr:16, spo2:98, temp:36.8, o2:'RA'},
  hist:{
    hpi:'My feet tingle and feel numb. I nearly fell in the shower when I closed my eyes to rinse my hair.',
    meds:'Metformin for 10 years and omeprazole for reflux.',
    pmh:'Diabetes and hypothyroidism.',
    ros:'My tongue has been sore.',
    neuro:'Some trouble remembering things lately.',
    etoh:'Rarely drink.',
  },
  keyHist:['hpi','meds','pmh'],
  exam:{
    heent:'Smooth, beefy red tongue (glossitis). Mild conjunctival pallor.',
    neuro:'Decreased vibration and position sense in both feet. Romberg positive. Ankle reflexes absent, knee reflexes brisk, Babinski upgoing bilaterally.',
    gait:'Wide-based, high-stepping, stamping gait. She watches her feet. Much worse with eyes closed (Romberg positive).',
    skin:'Pale, faintly lemon-tinged.',
  },
  keyExam:['neuro','gait'],
  tests:{
    cbc:{r:'Hgb 9.8 · MCV 112 · WBC 3.9 · Plt 140', y:'key', w:'Macrocytic anemia with mild pancytopenia.'},
    smear:{img:{type:'smear', f:['macro','hyperseg']}, r:'Macro-ovalocytes and hypersegmented neutrophils.', y:'key', w:'Megaloblastic picture.'},
    b12:{r:'B12 140 pg/mL (low) · Folate 11 ng/mL', y:'key', w:'Low B12.'},
    mma:{r:'MMA 1.8 µmol/L (high) · Homocysteine 32 µmol/L (high)', y:'useful', w:'Both high = B12 deficiency. Only homocysteine high = folate deficiency.'},
    ifab:{r:'Positive', y:'useful', w:'Pernicious anemia.'},
    hemol:{r:'LDH 620 · Indirect bili 1.8 · Haptoglobin low', y:'optional', w:'Ineffective erythropoiesis mimics hemolysis.'},
    mri:{r:'T2 hyperintensity in the dorsal columns of the cervical cord.', y:'optional', w:'Supports subacute combined degeneration. Not required.'},
    tsh:{r:'Normal on levothyroxine.', y:'optional', w:'Reasonable.'},
  },
  dx:'b12', dxPartial:{folate:5, diabneuro:5},
  acuity:{level:'soon', partial:['routine'], why:'Neurologic deficits can become permanent: replace B12 promptly, but no emergency.'},
  plan:[
    {t:'IM (or high-dose oral) vitamin B12, lifelong for pernicious anemia', k:'essential', w:'Stops progression. Some deficits may not recover.'},
    {t:'Recheck CBC and reticulocytes in 1–2 weeks; watch potassium early', k:'good', w:'Brisk marrow response can drop potassium.'},
    {t:'Folic acid alone', k:'harmful', w:'Can fix the anemia while neurologic damage progresses.'},
    {t:'Transfuse 2 units', k:'wrong', w:'Stable chronic anemia.'},
    {t:'Stop metformin', k:'wrong', w:'Not required. Check B12 yearly on metformin.'},
    {t:'One-time upper endoscopy for gastric cancer risk', k:'ok', w:'Pernicious anemia raises gastric neoplasm risk. Practice varies.'},
  ],
  approach:[
    {t:'Localize: numb feet + unsteady with eyes closed = dorsal columns (proprioception).', do:['hx:hpi','ex:neuro']},
    {t:'Watch her walk and do a Romberg test.', do:['ex:gait']},
    {t:'Ask about metformin, PPIs, diet, and autoimmune disease.', do:['hx:meds','hx:pmh']},
    {t:'CBC and smear, B12 level, then MMA if borderline.', do:['test:cbc','test:smear','test:b12','test:mma']},
    {t:'Replace B12 promptly. Never folate alone.'},
  ],
  pearls:[
    'Subacute combined degeneration: dorsal columns (vibration, position, Romberg) + corticospinal tracts (Babinski, spasticity). Ankle jerks may be lost.',
    'MMA is high in B12 deficiency, normal in folate deficiency. Homocysteine is high in both.',
    'Causes: pernicious anemia, metformin, PPIs, vegan diet, gastrectomy, ileal disease, fish tapeworm.',
    'Treatment can cause hypokalemia in the first days.',
  ],
  target:{min:3000, cost:600},
},
{
  id:'dgi', subject:'ID', tier:2, tierWhy:'A joint infection whose source is found on the GU exam.',
  care:'ED', bed:'ED 25', setting:'Emergency Dept', name:'Jordan Ellis', age:23, sex:'F',
  look:{skin:'#c99a74', hair:'#3a2418', sex:'F', habitus:'thin', gait:'antalgic', knee:'R', pustules:true, sweat:true},
  cc:'My wrists and knee are killing me, and I have these bumps on my skin.',
  brief:'23-year-old woman with 4 days of fever and joint pain that moves from joint to joint, now a swollen right knee and a few skin bumps.',
  vitals:{hr:104, sbp:116, dbp:72, rr:16, spo2:99, temp:38.4, o2:'RA'},
  hist:{
    hpi:'It started in my left wrist, then my right ankle, now my right knee. Fevers and chills.',
    sex:'A new partner a month ago. We don’t always use condoms.',
    gu:'Some yellow vaginal discharge last week, and burning when I pee.',
    ros:'A few spots on my hands and arms.',
    meds:'None.',
    pmh:'Healthy.',
  },
  keyHist:['sex','gu'],
  exam:{
    general:'Ill-appearing and febrile.',
    joints:'Right knee warm and swollen with an effusion; painful range of motion. Tenosynovitis along the left wrist extensor tendons.',
    skin:'A few painless pustules on red bases on the hands and forearms.',
    gu:'Speculum exam: mucopurulent cervical discharge. No genital ulcers.',
    gait:'Limps, avoiding weight on the right knee.',
  },
  keyExam:['joints','skin','gu'],
  tests:{
    arthro:{img:{type:'synovial', f:['pmn']}, r:'Cloudy fluid. WBC 42,000 (90% PMNs). No crystals. Gram stain negative. Culture pending (often negative in DGI).', y:'key', w:'Inflammatory, crystal-negative fluid in a septic-appearing joint.'},
    gcnaat:{r:'Cervical NAAT: N. gonorrhoeae POSITIVE. Chlamydia negative.', y:'key', w:'Mucosal NAAT is the highest-yield test in DGI.'},
    bcx:{r:'Drawn. Pending (positive in < 50%).', y:'useful', w:'Should be drawn, though often negative.'},
    hcg:{r:'Negative', y:'key', w:'Required before treatment decisions and imaging.'},
    hiv:{r:'Nonreactive', y:'useful', w:'Test everyone with an STI.'},
    rpr:{r:'Nonreactive', y:'useful', w:'Screen for co-infection.'},
    cbc:{r:'WBC 13.2', y:'optional', w:'Mild leukocytosis.'},
    uric:{r:'4.1 mg/dL', y:'low', w:'Gout is very unlikely here.'},
    auto:{r:'Negative', y:'low', w:'Not an autoimmune picture.'},
  },
  dx:'dgi', dxPartial:{septicarthritis:20, reactive:10, gout:0},
  acuity:{level:'admit', partial:['now'], why:'Septic arthritis picture: IV ceftriaxone and admission.'},
  plan:[
    {t:'IV ceftriaxone 1 g daily', k:'essential', w:'First-line for DGI.'},
    {t:'Partner notification and treatment; HIV and syphilis testing', k:'essential', w:'Prevents reinfection and spread.'},
    {t:'Repeated aspiration of the knee effusion', k:'good', w:'Drainage of the purulent joint.'},
    {t:'Add doxycycline for chlamydia if not excluded', k:'ok', w:'Chlamydia NAAT is negative here.'},
    {t:'Oral ciprofloxacin', k:'harmful', w:'Widespread gonococcal fluoroquinolone resistance.'},
    {t:'Prednisone for the arthritis', k:'harmful', w:'Immunosuppression in an infected joint.'},
    {t:'Wait for synovial culture before antibiotics', k:'harmful', w:'Cultures are often negative. Treat on suspicion.'},
  ],
  approach:[
    {t:'Characterize the arthritis: migratory, tenosynovitis, skin lesions.', do:['ex:joints','ex:skin']},
    {t:'Take a sexual history and do a chaperoned GU exam.', do:['hx:sex','ex:gu']},
    {t:'Aspirate the effusion: cell count, crystals, Gram stain, culture.', do:['test:arthro']},
    {t:'NAAT from mucosal sites, blood cultures, pregnancy test.', do:['test:gcnaat','test:bcx','test:hcg']},
    {t:'IV ceftriaxone; treat partners.'},
  ],
  pearls:[
    'DGI: tenosynovitis + migratory polyarthralgia + pustular dermatitis, OR purulent monoarthritis.',
    'Test mucosal sites (cervix or urethra, pharynx, rectum) with NAAT. Synovial cultures are often negative.',
    'Reactive arthritis: weeks after GI or GU infection, with conjunctivitis or urethritis; sterile joint.',
    'Overall, S. aureus is the most common septic arthritis. Synovial WBC > 50,000 is suspicious.',
  ],
  target:{min:90, cost:900},
}
);
