"use strict";
/* Hematology / oncology cases */
CASES.push(
{
  id:'ida', subject:'Heme/Onc', tier:1, tierWhy:'Common anemia whose real job is finding the source.',
  bed:'Clinic 3', setting:'Primary care clinic', name:'Leonard Price', age:67, sex:'M',
  look:{skin:'#e3c0a8', hair:'#a8a8a8', sex:'M', habitus:'normal', pallor:.6},
  cc:'I’m exhausted, and I get winded walking up my driveway.',
  brief:'67-year-old man with 3 months of fatigue and exertional dyspnea. He has never had a colonoscopy.',
  vitals:{hr:96, sbp:124, dbp:74, rr:18, spo2:98, temp:36.8, o2:'RA'},
  hist:{
    hpi:'Three months of being worn out. I get winded doing things that used to be easy.',
    gi:'Maybe my stools have been darker? No obvious blood. They’ve been thinner lately.',
    wt:'I’ve lost about 8 pounds.',
    ros:'I crave ice. I chew it all day.',
    meds:'Low-dose aspirin.',
    pmh:'High blood pressure.',
    fhx:'My brother had colon polyps.',
  },
  keyHist:['gi','wt','ros'],
  exam:{
    general:'Pale. Comfortable at rest.',
    heent:'Conjunctival pallor. Cracks at the corners of the mouth. Smooth, glossy tongue.',
    hands:'Spoon-shaped nails (koilonychia).',
    abd:'Soft, nontender. No palpable masses.',
    rectal:'Brown stool, guaiac positive.',
    heart:'Soft systolic flow murmur.',
  },
  keyExam:['rectal','heent'],
  tests:{
    cbc:{r:'Hgb 8.2 · MCV 71 · RDW 18.5% · WBC 6.8 · Plt 450', y:'key', w:'Microcytic anemia with a high RDW and reactive thrombocytosis.'},
    iron:{r:'Ferritin 6 ng/mL · Iron 22 · TIBC 460 · Transferrin sat 5%', y:'key', w:'Ferritin < 30 = iron deficiency.'},
    smear:{img:{type:'smear', f:['micro']}, r:'Microcytic, hypochromic RBCs with anisocytosis and pencil cells.', y:'useful', w:'Classic iron deficiency morphology.'},
    colo:{r:'Friable, partially obstructing 4 cm mass in the ascending colon. Biopsy: adenocarcinoma.', y:'key', w:'Iron deficiency in an older man is GI cancer until proven otherwise.'},
    ctabd:{img:{type:'ct', region:'abd', f:['colonmass']}, r:'Ascending colon mass. No liver lesions or adenopathy.', y:'useful', w:'Staging after the diagnosis.'},
    egd:{r:'Mild gastritis. No ulcer or mass.', y:'optional', w:'Bidirectional endoscopy is standard for IDA. Here the colon explained it.'},
    hgbe:{r:'HbA2 2.4% (normal)', y:'low', w:'Ferritin already shows iron deficiency. A high RDW argues against thalassemia trait.'},
    b12:{r:'B12 410 · Folate 9', y:'low', w:'Not a macrocytic anemia.'},
    cea:{r:'CEA 12 ng/mL', y:'low', w:'For monitoring after treatment, not diagnosis.'},
    hemol:{r:'LDH 160 · Haptoglobin 140 · Retic 0.8%', y:'low', w:'Not hemolysis. Low retic fits iron deficiency.'},
  },
  dx:'colonca', dxPartial:{ida:20, thal:0},
  plan:[
    {t:'Staging CT chest/abdomen/pelvis and baseline CEA', k:'essential', w:'Required before surgery.'},
    {t:'Surgical resection (right hemicolectomy)', k:'essential', w:'Curative intent for localized disease.'},
    {t:'Iron replacement (oral, or IV before surgery)', k:'essential', w:'Rebuilds iron stores.'},
    {t:'Earlier colonoscopy screening for first-degree relatives', k:'good', w:'Family risk is now higher.'},
    {t:'Oral iron and recheck in 3 months, no further workup', k:'harmful', w:'Misses the cancer.'},
    {t:'Transfuse 2 units now', k:'wrong', w:'He’s stable with Hgb 8.2. No transfusion needed.'},
    {t:'Start erythropoietin', k:'wrong', w:'Iron deficiency needs iron, not EPO.'},
  ],
  pearls:[
    'Iron deficiency in a man or postmenopausal woman → colonoscopy and EGD.',
    'Right-sided colon cancer: anemia. Left-sided: obstruction and changes in stool caliber.',
    'Ferritin < 30 = iron deficiency. Anemia of chronic disease: normal or high ferritin, low TIBC.',
    'Thalassemia trait: Mentzer index (MCV/RBC) < 13, normal RDW, normal ferritin.',
    'Streptococcus gallolyticus (bovis) endocarditis → colonoscopy.',
  ],
  target:{min:300, cost:4000},
},
{
  id:'ttp', subject:'Heme/Onc', tier:3, tierWhy:'Rare and lethal if missed. The smear is the clue.',
  bed:'ED 19', setting:'Emergency Dept', name:'Kendra Simmons', age:29, sex:'F',
  look:{skin:'#9b6a48', hair:'#151010', sex:'F', habitus:'normal', jaundice:.3, pallor:.35, petechiae:true},
  cc:'Roommate: “She has a headache and these red spots, and she’s confused.”',
  brief:'29-year-old woman brought by her roommate for 2 days of headache, confusion, and a new rash on her legs.',
  vitals:{hr:108, sbp:138, dbp:82, rr:18, spo2:98, temp:38.2, o2:'RA'},
  hist:{
    hpi:'Roommate: “She’s been mixing up words and forgetting things since yesterday. She noticed red dots on her legs.”',
    neuro:'Headache. My right hand went numb for an hour this morning.',
    gu:'My urine looks dark.',
    gi:'No diarrhea.',
    meds:'Birth control pills.',
    pmh:'Nothing.',
  },
  keyHist:['neuro','gi'],
  exam:{
    general:'Mildly confused. Oriented to person and place.',
    heent:'Scleral icterus.',
    skin:'Petechiae on both lower legs. Mild jaundice.',
    neuro:'Word-finding difficulty. No focal motor deficit right now.',
    legs:'Petechiae on both shins.',
  },
  keyExam:['skin','neuro'],
  tests:{
    cbc:{r:'Hgb 7.8 · Plt 12,000 · WBC 8.4', y:'key', w:'Anemia and severe thrombocytopenia.'},
    smear:{img:{type:'smear', f:['schisto','lowplt']}, r:'Numerous schistocytes (5 per HPF). Very few platelets.', y:'key', w:'Microangiopathic hemolytic anemia.'},
    hemol:{r:'LDH 1,420 · Haptoglobin < 10 · Indirect bili 3.2 · Retic 6%', y:'key', w:'Intravascular hemolysis.'},
    pt:{r:'INR 1.0 · PTT 30 s · Fibrinogen 320', y:'key', w:'Normal coags separate TTP from DIC.'},
    dat:{r:'Negative', y:'useful', w:'Excludes autoimmune hemolytic anemia.'},
    adamts:{r:'Sent out. ADAMTS13 activity < 5% with an inhibitor (resulted day 2).', y:'useful', w:'Confirms TTP, but don’t wait for it to start plasma exchange.'},
    cmp:{r:'Cr 1.4 · T bili 3.4 · AST 40 · ALT 28', y:'useful', w:'Mild renal involvement.'},
    hcg:{r:'Negative', y:'useful', w:'Pregnancy can trigger TTP and HELLP.'},
    cthead:{img:{type:'ct', region:'head', f:[]}, r:'No hemorrhage.', y:'optional', w:'Reasonable with neurologic symptoms and platelets of 12,000.'},
    bcx:{r:'Drawn. Pending.', y:'optional', w:'Fever workup.'},
    ua:{r:'Blood 1+, protein 1+', y:'optional', w:'Mild renal involvement.'},
  },
  dx:'ttp', dxPartial:{hus:15, dic:5, itp:5},
  plan:[
    {t:'Emergent plasma exchange', k:'essential', w:'Removes the inhibitor and replaces ADAMTS13. Mortality drops from ~90% to ~10–20%.'},
    {t:'High-dose glucocorticoids', k:'essential', w:'Suppresses the autoantibody.'},
    {t:'Caplacizumab', k:'good', w:'Blocks von Willebrand factor–platelet binding. Faster platelet recovery.'},
    {t:'Rituximab', k:'good', w:'Reduces relapse.'},
    {t:'Stop the oral contraceptive', k:'good', w:'Estrogen is a possible trigger.'},
    {t:'Platelet transfusion', k:'harmful', w:'Feeds microthrombi. Avoid unless there is life-threatening bleeding.'},
    {t:'Wait for ADAMTS13 before starting plasma exchange', k:'harmful', w:'Results take days. Start on clinical suspicion.'},
    {t:'IVIG as primary therapy', k:'wrong', w:'That’s for ITP.'},
  ],
  pearls:[
    'Microangiopathic hemolytic anemia + thrombocytopenia → think TTP and get a smear.',
    'The “pentad” (fever, neuro, renal, MAHA, thrombocytopenia) is rarely complete.',
    'TTP: ADAMTS13 deficiency, normal PT/PTT. DIC: high PT/PTT, low fibrinogen.',
    'HUS: E. coli O157:H7 diarrhea, kidney-predominant, mostly children.',
    'ITP: isolated thrombocytopenia with a normal smear and no hemolysis.',
  ],
  target:{min:90, cost:1100},
},
{
  id:'hit', subject:'Heme/Onc', tier:3, tierWhy:'An inpatient trap. The fix is the opposite of instinct.',
  bed:'Ward 3B', setting:'Cardiac surgery ward', name:'Samuel Ortiz', age:63, sex:'M',
  look:{skin:'#c4946e', hair:'#3a3a3a', sex:'M', habitus:'heavy', swollen:'R'},
  cc:'My right leg is swollen and sore.',
  brief:'63-year-old man on hospital day 8 after coronary bypass surgery, on subcutaneous heparin. Platelets have fallen from 240,000 to 70,000 over 4 days, and his right leg is swollen.',
  vitals:{hr:96, sbp:128, dbp:76, rr:18, spo2:96, temp:37.2, o2:'RA'},
  hist:{
    hpi:'My right calf started hurting yesterday. Now it’s puffy.',
    meds:'Heparin shots, aspirin, metoprolol, atorvastatin. They gave me heparin during the surgery too.',
    pmh:'Coronary disease and diabetes. No bleeding problems ever.',
    immob:'Mostly in bed since surgery.',
    cough:'No shortness of breath.',
  },
  keyHist:['meds'],
  exam:{
    general:'Comfortable at rest.',
    legs:'Right calf swollen, warm, and tender.',
    skin:'A dark, necrotic patch at a heparin injection site on the abdomen.',
    abd:'Bruising and one necrotic lesion at injection sites.',
    lungR:'Clear.', lungL:'Clear.',
  },
  keyExam:['legs','skin'],
  tests:{
    cbc:{r:'Plt 70,000 (240,000 at admission) · Hgb 10.9 · WBC 9.0', y:'key', w:'More than a 50% drop, starting 5–10 days after heparin exposure.'},
    pf4:{r:'PF4–heparin ELISA positive (OD 2.1)', y:'key', w:'A high optical density makes HIT likely.'},
    sra:{r:'Positive (send-out)', y:'useful', w:'Confirms HIT. Don’t wait for it to change management.'},
    duplex:{r:'Acute right femoral-popliteal DVT.', y:'useful', w:'HIT causes clots, not bleeding.'},
    pt:{r:'INR 1.1 · PTT 32 s · Fibrinogen 380', y:'useful', w:'Rules out DIC.'},
    smear:{img:{type:'smear', f:['lowplt']}, r:'Thrombocytopenia. No schistocytes.', y:'optional', w:'Excludes TTP.'},
    ctpa:{img:{type:'ct', region:'chest', contrast:true, f:[]}, r:'No PE.', y:'optional', w:'Reasonable if he develops respiratory symptoms.'},
    dat:{r:'Negative', y:'low', w:'No hemolysis.'},
  },
  dx:'hit', dxPartial:{dvt:10, dic:5, ttp:0},
  plan:[
    {t:'Stop ALL heparin, including flushes and LMWH', k:'essential', w:'Removes the trigger.'},
    {t:'Start a non-heparin anticoagulant (argatroban or bivalirudin; fondaparinux or a DOAC if stable)', k:'essential', w:'HIT is prothrombotic. He already has a DVT.'},
    {t:'List heparin as an allergy', k:'good', w:'Prevents re-exposure.'},
    {t:'Warfarin only after platelets recover above 150,000, with ≥ 5 days of overlap', k:'good', w:'Early warfarin can cause venous limb gangrene.'},
    {t:'Switch to enoxaparin', k:'harmful', w:'LMWH cross-reacts with HIT antibodies.'},
    {t:'Transfuse platelets', k:'harmful', w:'Can fuel more clotting.'},
    {t:'Stop heparin and give no anticoagulant', k:'harmful', w:'Thrombosis risk stays high for weeks.'},
    {t:'Start warfarin today', k:'harmful', w:'Protein C depletion → venous limb gangrene.'},
  ],
  pearls:[
    '4Ts: Thrombocytopenia (> 50% fall), Timing (5–10 days, or sooner with heparin in the past 100 days), Thrombosis, no oTher cause.',
    'Platelets rarely fall below 20,000. Clots are far more common than bleeding.',
    'Screen with the PF4 ELISA, confirm with the serotonin release assay.',
    'Treat with argatroban or bivalirudin (or fondaparinux or a DOAC). No LMWH. Warfarin only after recovery.',
  ],
  target:{min:100, cost:1000},
},
{
  id:'myeloma', subject:'Heme/Onc', tier:2, tierWhy:'A common cancer that hides behind back pain.',
  bed:'Ward 7A', setting:'Medicine ward', name:'Harriet Coleman', age:71, sex:'F',
  look:{skin:'#8c5e40', hair:'#bdbdbd', sex:'F', habitus:'normal', pallor:.3},
  cc:'My back is killing me, and I’m so tired and thirsty.',
  brief:'71-year-old woman with 2 months of worsening low back pain, fatigue, constipation, and new confusion.',
  vitals:{hr:88, sbp:136, dbp:80, rr:16, spo2:97, temp:36.9, o2:'RA'},
  hist:{
    hpi:'The back pain started two months ago and keeps getting worse, especially at night. My family says I’ve been forgetful.',
    gi:'Constipated for a week.',
    gu:'Peeing a lot. Always thirsty.',
    wt:'I’ve lost 10 pounds.',
    fever:'No fevers now, but I’ve had pneumonia twice this year.',
    meds:'Ibuprofen for the back pain.',
    pmh:'High blood pressure.',
  },
  keyHist:['hpi','fever'],
  exam:{
    general:'Tired, mildly confused.',
    heent:'Dry mucous membranes.',
    back:'Point tenderness over the L2 and L4 vertebrae.',
    neuro:'Mild confusion. Normal leg strength, sensation, and rectal tone.',
  },
  keyExam:['back'],
  tests:{
    cmp:{r:'Na 136 · K 4.2 · BUN 36 · Cr 2.1 · Ca 13.1 · Total protein 9.8 · Albumin 3.0', y:'key', w:'Hypercalcemia, AKI, and a protein gap (total protein − albumin) of 6.8.'},
    cbc:{r:'Hgb 9.1 · MCV 92 · WBC 5.0 · Plt 190', y:'useful', w:'Normocytic anemia.'},
    smear:{img:{type:'smear', f:['rouleaux']}, r:'Rouleaux formation (red cells stacked like coins).', y:'key', w:'Paraprotein makes red cells stick together.'},
    spep:{r:'IgG kappa M-spike 4.2 g/dL. Free light chain ratio 48.', y:'key', w:'Monoclonal protein.'},
    pth:{r:'PTH 8 pg/mL (suppressed) · PTHrP normal', y:'useful', w:'PTH-independent hypercalcemia.'},
    skel:{r:'Multiple punched-out lytic lesions in the skull, spine, and pelvis. L2 compression fracture.', y:'key', w:'Bone disease (the “B” in CRAB).'},
    bmbx:{r:'38% clonal plasma cells.', y:'key', w:'≥ 10% clonal plasma cells plus CRAB features = myeloma.'},
    ecg:{img:{type:'ecg', f:['nsr','shortQT']}, r:'Normal sinus rhythm 88. Short QT interval.', y:'optional', w:'Short QT is the classic ECG sign of hypercalcemia.'},
    ua:{r:'Dipstick protein trace.', y:'optional', w:'Dipstick misses light chains. A UPEP would show Bence Jones protein.'},
    mri:{r:'Normal brain.', y:'low', w:'Confusion is explained by calcium.'},
  },
  dx:'myeloma', dxPartial:{mgus:5, hyperpth:0},
  plan:[
    {t:'IV normal saline for hypercalcemia', k:'essential', w:'First step. She’s volume-depleted from calcium-induced diuresis.'},
    {t:'Bisphosphonate (dose-adjusted) or denosumab', k:'essential', w:'Lowers calcium over days and protects bone.'},
    {t:'Refer for myeloma therapy (bortezomib-lenalidomide-dexamethasone–based) and transplant evaluation', k:'essential', w:'Treats the underlying disease.'},
    {t:'Calcitonin for rapid short-term lowering', k:'good', w:'Works within hours. Tachyphylaxis after 48 h.'},
    {t:'Stop ibuprofen and avoid IV contrast', k:'good', w:'Protect the kidneys.'},
    {t:'Hydrochlorothiazide', k:'harmful', w:'Raises serum calcium.'},
    {t:'Furosemide before volume repletion', k:'wrong', w:'Only for volume overload once repleted.'},
    {t:'Bone scan to evaluate lesions', k:'wrong', w:'Purely lytic lesions are often missed on bone scan.'},
  ],
  pearls:[
    'CRAB: hyperCalcemia, Renal failure, Anemia, Bone lesions.',
    'Clues: protein gap, rouleaux, recurrent infections, back pain.',
    'Workup: SPEP + immunofixation + free light chains, skeletal survey or low-dose whole-body CT (not bone scan), bone marrow biopsy.',
    'Hypercalcemia treatment: IV fluids → calcitonin → bisphosphonate or denosumab.',
    'MGUS: M protein < 3 g/dL, < 10% plasma cells, no CRAB features.',
  ],
  target:{min:300, cost:4000},
},
{
  id:'chestsyndrome', subject:'Heme/Onc', tier:2, tierWhy:'A sickle cell emergency that can mimic pneumonia.',
  bed:'Ward 8C', setting:'Medicine ward', name:'Andre Williams', age:22, sex:'M',
  look:{skin:'#6a4430', hair:'#0f0b08', sex:'M', habitus:'thin', jaundice:.3, o2:'cannula'},
  cc:'My chest hurts and I can’t breathe. It’s like my pain crises, but worse.',
  brief:'22-year-old man with sickle cell disease (HbSS), admitted yesterday for a pain crisis in his back and legs. Today he has new chest pain, fever, and low oxygen.',
  vitals:{hr:118, sbp:124, dbp:74, rr:28, spo2:89, temp:38.6, o2:'RA'},
  decline:{by:150, to:{spo2:84, rr:32}},
  hist:{
    hpi:'I came in for my usual pain crisis. This morning my chest started hurting when I breathe, and I can’t get enough air.',
    pmh:'Sickle cell disease. I had acute chest once at 15. They told me my spleen doesn’t work.',
    meds:'Hydroxyurea, but I haven’t been taking it. Folic acid. Here, a morphine pump.',
    cough:'Some cough.',
    fever:'Started this morning.',
  },
  keyHist:['pmh','meds'],
  exam:{
    general:'Splinting, tachypneic.',
    heent:'Scleral icterus.',
    lungR:'Crackles and dullness at the right base.',
    lungL:'Clear.',
    heart:'Tachycardic. Systolic flow murmur.',
  },
  keyExam:['lungR'],
  tests:{
    cxr:{img:{type:'cxr', f:['consol_RL']}, r:'New right lower lobe opacity.', y:'key', w:'A new infiltrate plus fever or respiratory symptoms = acute chest syndrome.'},
    cbc:{r:'Hgb 6.4 (baseline 8.5) · WBC 18.0 · Plt 310 · Retic 12%', y:'key', w:'Dropping hemoglobin. Will need transfusion.'},
    abg:{r:'Room air: pH 7.44 · PaCO2 34 · PaO2 58', y:'useful', w:'Significant hypoxemia.'},
    smear:{img:{type:'smear', f:['sickle','target','howell']}, r:'Sickled cells, target cells, and Howell-Jolly bodies (functional asplenia).', y:'useful', w:'Classic HbSS smear.'},
    tnc:{r:'Extended phenotype-matched units available.', y:'key', w:'Matching reduces alloimmunization in chronically transfused patients.'},
    bcx:{r:'Drawn. Pending.', y:'useful', w:'Functional asplenia puts him at risk for encapsulated organisms.'},
    hemol:{r:'LDH 640 · Haptoglobin < 10 · Indirect bili 3.8 · Retic 12%', y:'optional', w:'Ongoing hemolysis.'},
    ctpa:{img:{type:'ct', region:'chest', contrast:true, f:['consol'], side:'R'}, r:'No PE. Right lower lobe consolidation.', y:'low', w:'Acute chest syndrome explains the picture.'},
    uag:{r:'Both negative.', y:'optional', w:'Reasonable infection workup.'},
  },
  dx:'chestsyndrome', dxPartial:{cap:15, pe:0},
  plan:[
    {t:'Empiric ceftriaxone + azithromycin', k:'essential', w:'Covers typical and atypical organisms.'},
    {t:'Simple transfusion toward Hgb ~10 (exchange transfusion if severe or worsening)', k:'essential', w:'Improves oxygenation and lowers HbS.'},
    {t:'Supplemental O2 for SpO2 < 95%', k:'essential', w:'Hypoxemia drives more sickling.'},
    {t:'Incentive spirometry', k:'good', w:'Prevents and treats atelectasis.'},
    {t:'Balanced analgesia, avoiding oversedation', k:'good', w:'Splinting worsens atelectasis, but too much opioid causes hypoventilation.'},
    {t:'Restart hydroxyurea at discharge', k:'good', w:'Reduces future crises and acute chest episodes.'},
    {t:'Transfuse to Hgb 13', k:'harmful', w:'Hyperviscosity worsens sickling.'},
    {t:'IV fluids at twice the maintenance rate', k:'wrong', w:'Over-hydration can cause pulmonary edema. Keep him euvolemic.'},
  ],
  pearls:[
    'Acute chest syndrome = a new infiltrate + fever or respiratory symptoms in sickle cell disease. A leading cause of death.',
    'Treatment: antibiotics, O2, incentive spirometry, analgesia, transfusion (exchange if severe).',
    'Functional asplenia → vaccinate against encapsulated organisms. Penicillin prophylaxis in children.',
    'Hydroxyurea raises HbF and reduces crises.',
  ],
  target:{min:70, cost:800},
}
);
