"use strict";
/* Teaching layer for the original 40 cases: care setting, triage level, step-by-step approach,
   and extra exam findings (close-up views, tremor, gait, skin marks). Merged into CASES at load. */
const A = (t, ...d) => d.length ? {t, do:d} : {t};
const TEACH = {
  copd:{care:'ED', acuity:{level:'now', partial:['admit'], why:'pH 7.31 with hypercapnia and tachypnea: BiPAP now, then step-down admission.'},
    look:{mouth:['cyanosis'], nails:['cyanosis']},
    approach:[A('Assess work of breathing and SpO₂; start controlled O₂ (88–92%) and nebulizers.','ex:general'), A('ABG for hypercapnic acidosis.','test:abg'), A('CXR and ECG to find the trigger and exclude pneumothorax, pneumonia, or ischemia.','test:cxr','test:ecg'), A('Steroids, plus antibiotics for purulent sputum.','hx:cough'), A('BiPAP for pH < 7.35 with PaCO₂ > 45; intubate if it fails.')]},
  asthma:{care:'ED', acuity:{level:'now', partial:['admit'], why:'Severe features and a normal PaCO₂ = impending respiratory failure. Treat in resus, admit to ICU.'},
    approach:[A('Rapid look: speech, accessory muscles, SpO₂. Start albuterol/ipratropium immediately.','ex:general'), A('Peak flow to grade severity.','test:pef'), A('ABG: a normal PaCO₂ is ominous.','test:abg'), A('Steroids within the hour; IV magnesium if not improving.'), A('Ask about prior intubation or ICU stays; plan ICU.','hx:pmh')]},
  pe:{care:'ED', acuity:{level:'admit', partial:['now'], why:'Stable PE without RV strain, but hypoxemic: anticoagulate and admit.'},
    approach:[A('Pretest probability (Wells): recent surgery, calf swelling, tachycardia.','hx:immob','ex:legs'), A('High probability → start anticoagulation and get a CTPA (skip D-dimer).','test:ctpa'), A('Risk-stratify: BP, troponin/BNP, RV size on CT.','test:trop'), A('Kidney function and platelets before choosing an anticoagulant.','test:cmp','test:cbc'), A('3 months of anticoagulation for provoked PE.')]},
  tension:{care:'ED', acuity:{level:'now', partial:[], why:'Obstructive shock: decompress within minutes.'},
    look:{mouth:['cyanosis']},
    approach:[A('Primary survey: absent breath sounds, deviated trachea, distended neck veins.','ex:lungR','ex:neck'), A('Decompress on clinical grounds. No imaging first.'), A('Optional 30-second bedside ultrasound if it causes no delay.','test:pocus'), A('Chest tube, then imaging once stable.')]},
  cap:{care:'ED', acuity:{level:'admit', partial:[], why:'CURB-65 of 2 with hypoxemia: admit to the ward.'},
    approach:[A('History and exam for consolidation.','ex:lungR','hx:cough'), A('CXR to confirm pneumonia.','test:cxr'), A('CURB-65: confusion, BUN, RR, BP, age.','test:cmp','ex:general'), A('Pick the site of care, then empiric antibiotics for that site.')]},
  sarcoid:{care:'Outpatient', target:{min:30000, cost:5500}, acuity:{level:'routine', partial:['soon'], why:'Symptomatic but stable: outpatient workup over weeks.'},
    approach:[A('Multisystem history: eyes, skin, joints, kidney stones.','hx:ros','hx:pmh'), A('CXR and CT for hilar adenopathy and lung involvement.','test:cxr','test:ct'), A('Calcium and PFTs to judge organ involvement.','test:cmp','test:pft'), A('Tissue diagnosis: EBUS biopsy showing noncaseating granulomas; exclude TB and fungus.','test:bronch'), A('Screen heart (ECG) and eyes; steroids for symptomatic disease.','test:ecg')]},
  ipf:{care:'Outpatient', target:{min:15000, cost:1800}, acuity:{level:'routine', partial:['soon'], why:'Chronic and progressive: outpatient workup and therapy.'},
    look:{nails:['clubbing']},
    approach:[A('Exposure, drug, and connective tissue history to exclude secondary ILD.','hx:expo','hx:meds','hx:ros'), A('Exam: velcro crackles and clubbing.','ex:lungR','ex:hands'), A('HRCT: a definite UIP pattern is diagnostic.','test:hrct'), A('PFTs and a 6-minute walk for restriction and O₂ needs.','test:pft','test:walk'), A('Antifibrotic, O₂, rehab, transplant referral. No steroids.')]},
  sclc:{care:'Inpatient', acuity:{level:'admit', partial:['soon'], why:'Symptomatic hyponatremia (confusion): correct it in hospital while the cancer workup proceeds.'},
    approach:[A('Confirm hypotonic hyponatremia and assess volume status.','test:cmp','ex:heent','ex:legs'), A('Serum/urine osmolality and urine Na → SIADH; exclude thyroid and adrenal causes.','test:osm','test:endo'), A('Find the cause: heavy smoker with weight loss → chest imaging.','hx:smoke','test:ct'), A('Tissue by bronchoscopy, then staging.','test:bronch'), A('Fluid restriction; correct ≤ 8 mEq/L per 24 h.')]},
  empyema:{care:'Inpatient', acuity:{level:'admit', partial:['now'], why:'Infected pleural space: drain today.'},
    approach:[A('Not improving on antibiotics → look for a complication.','hx:hpi'), A('Exam and CXR for an effusion.','ex:lungL','test:cxr'), A('Ultrasound-guided thoracentesis: pH, glucose, LDH, protein, Gram stain.','test:pocus','test:thora'), A('Light’s criteria and drainage criteria → chest tube.')]},
  tb:{care:'ED', acuity:{level:'admit', partial:['soon'], why:'Smear-positive cavitary TB with children at home: airborne isolation and admission.'},
    approach:[A('Suspect TB (chronic cough, sweats, weight loss, endemic origin) → airborne isolation first.','hx:travel','hx:fever'), A('CXR for an upper-lobe cavity.','test:cxr'), A('Three sputum AFB smears/cultures plus NAAT.','test:afb'), A('HIV test and baseline LFTs.','test:hiv','test:cmp'), A('Start RIPE, report, trace contacts.')]},
  osa:{care:'Outpatient', target:{min:12000, cost:900}, acuity:{level:'routine', partial:['soon'], why:'Important but not urgent; the drowsy driving needs same-visit counseling.'},
    look:{mouth:['mallampati4']},
    approach:[A('Sleep history from patient and partner (STOP-BANG).','hx:sleep'), A('Airway and neck exam.','ex:heent','ex:neck'), A('Home sleep apnea test (or PSG if complicated).','test:hsat'), A('Exclude hypoventilation with bicarbonate if obese.','test:cmp'), A('CPAP and weight loss; counsel about driving.')]},
  ards:{care:'Inpatient', acuity:{level:'now', partial:['admit'], why:'P/F ≈ 72 and tiring: intubate and move to ICU now.'},
    look:{mouth:['cyanosis']},
    approach:[A('Rapid assessment of work of breathing and oxygenation.','ex:general'), A('ABG for the P/F ratio.','test:abg'), A('CXR for bilateral opacities.','test:cxr'), A('Exclude cardiogenic edema (BNP, echo, JVP).','test:bnp','ex:neck'), A('Intubate with lung-protective settings; prone if P/F < 150.')]},
  stemi:{care:'ED', acuity:{level:'now', partial:[], why:'STEMI: door-to-balloon < 90 minutes.'},
    approach:[A('ECG within 10 minutes of arrival.','test:ecg'), A('Aspirin now; activate the cath lab on the ECG alone.'), A('Inferior STEMI → right-sided leads, BP, and JVP (RV infarct).','ex:neck'), A('Ask about PDE-5 inhibitors before any nitrate.','hx:meds'), A('Antiplatelets, anticoagulation, PCI.')]},
  adhf:{care:'ED', acuity:{level:'admit', partial:['now'], why:'Hypoxemic, congested: IV diuresis and admission.'},
    approach:[A('Assess congestion and perfusion (warm/cold, wet/dry).','ex:neck','ex:lungR','ex:legs'), A('CXR and BNP to confirm HF.','test:cxr','test:bnp'), A('ECG and troponin to find a trigger.','test:ecg','test:trop'), A('Find precipitants: missed meds, salt, NSAIDs.','hx:meds'), A('IV diuretic ± nitrates; echo; start GDMT.','test:tte')]},
  afib:{care:'ED', acuity:{level:'admit', partial:['soon'], why:'Stable: rate control and anticoagulation now; observe or admit until the rate is controlled. Not an emergency cardioversion.'},
    approach:[A('Check stability: BP, mental status, chest pain.','ex:general'), A('ECG to confirm AF.','test:ecg'), A('Rate control with a beta-blocker or diltiazem.'), A('CHA₂DS₂-VASc for stroke risk → anticoagulate.','hx:pmh'), A('Triggers: thyroid, alcohol, electrolytes, structural heart disease.','test:tsh','test:cmp','test:tte')]},
  dissection:{care:'ED', acuity:{level:'now', partial:[], why:'Type A dissection: surgical emergency.'},
    approach:[A('Pain history: sudden, tearing, radiating to the back.','hx:hpi'), A('Check BP in both arms; listen for AR.','ex:hands','ex:heart'), A('ECG to exclude STEMI before anyone gives heparin.','test:ecg'), A('CT angiogram (TEE if unstable).','test:cta'), A('Beta-blocker first, then vasodilator; type A → surgery.')]},
  ugib:{care:'ED', acuity:{level:'now', partial:['admit'], why:'Hypotensive bleed: resuscitate now; endoscopy within 24 h.'},
    look:{mouth:['pale'], nails:['pale']},
    approach:[A('Hemodynamics first; two large-bore IVs.','ex:general'), A('Confirm melena and an upper source.','ex:rectal'), A('CBC, coags, type and crossmatch.','test:cbc','test:pt','test:tnc'), A('NSAIDs, aspirin, liver disease?','hx:meds'), A('IV PPI, transfuse to > 7, EGD within 24 h.','test:egd')]},
  pancreatitis:{care:'ED', acuity:{level:'admit', partial:['now'], why:'Needs IV fluids and analgesia in hospital; no organ failure yet.'},
    approach:[A('Typical pain + lipase > 3× ULN.','hx:hpi','test:lipase'), A('Find the cause: alcohol, gallstones (RUQ US), triglycerides, calcium.','hx:etoh','test:us_ruq','test:tg'), A('Severity markers: BUN, hematocrit, organ function.','test:cmp','test:cbc'), A('LR fluids, analgesia, early feeding; no early CT.')]},
  cholangitis:{care:'ED', acuity:{level:'now', partial:['admit'], why:'Septic from an obstructed duct: antibiotics and fluids now, ERCP within 24 h.'},
    approach:[A('Recognize Charcot/Reynolds: fever, RUQ pain, jaundice, hypotension, confusion.','ex:heent','ex:abd'), A('Blood cultures and broad antibiotics within the hour.','test:bcx'), A('LFTs for a cholestatic pattern.','test:cmp'), A('RUQ ultrasound for stones and duct dilation.','test:us_ruq'), A('ERCP drainage.')]},
  sbp:{care:'Inpatient', acuity:{level:'admit', partial:['now'], why:'Infected ascites with AKI and encephalopathy: inpatient antibiotics and albumin.'},
    look:{nails:['palmarErythema'], tremor:'asterixis', marks:['spiders','caput','gyn']},
    exam:{gu:'Small, soft testes (testicular atrophy). Sparse pubic hair.', skin:'Jaundiced. Spider angiomas on the chest. Dilated periumbilical veins (caput medusae). Gynecomastia.'},
    approach:[A('Every cirrhotic admitted with ascites gets a diagnostic paracentesis.','ex:abd','test:para'), A('PMN ≥ 250 = SBP → ceftriaxone.'), A('Kidney function and bilirubin → albumin.','test:cmp'), A('Encephalopathy: asterixis; find triggers; lactulose.','ex:hands','hx:meds')]},
  hyperk:{care:'ED', acuity:{level:'now', partial:['admit'], why:'Hyperkalemia with ECG changes: calcium within minutes.'},
    look:{mouth:['dry']},
    approach:[A('ECG immediately.','test:ecg'), A('Calcium gluconate for ECG changes.'), A('Shift (insulin/glucose, albuterol), then remove.'), A('Find the cause: meds, AKI type (FENa), volume.','hx:meds','test:cmp','test:ulytes')]},
  rhabdo:{care:'ED', acuity:{level:'admit', partial:['now'], why:'Needs high-volume IV fluids and electrolyte monitoring in hospital.'},
    look:{mouth:['dry']},
    approach:[A('History of immobilization, drugs, or exertion.','hx:etoh','hx:hpi'), A('CK, electrolytes, ECG.','test:ck','test:cmp','test:ecg'), A('UA: heme+ without RBCs.','test:ua'), A('Check compartments.','ex:legs'), A('Aggressive isotonic fluids.')]},
  dka:{care:'ED', acuity:{level:'now', partial:['admit'], why:'Severe DKA (pH 7.08): insulin drip in the ICU.'},
    look:{mouth:['dry']},
    approach:[A('Glucose, BMP with anion gap, ketones, blood gas.','test:cmp','test:bhb','test:abg'), A('Know the potassium before insulin.'), A('Fluids first, then insulin drip; add K.'), A('Find the trigger: missed insulin, infection, pregnancy.','hx:meds','test:hcg'), A('Add dextrose at glucose < 250; continue until the gap closes.')]},
  storm:{care:'ED', acuity:{level:'now', partial:['admit'], why:'Thyroid storm: treat immediately and admit to ICU.'},
    look:{tremor:'fine'},
    approach:[A('Recognize storm clinically; don’t wait for labs.','ex:general'), A('Thyroid and eye exam.','ex:neck','ex:heent'), A('TSH/free T4 to confirm; CBC before a thionamide.','test:tsh','test:cbc'), A('Beta-blocker → PTU → iodine 1 h later → steroids.')]},
  adrenal:{care:'ED', acuity:{level:'now', partial:['admit'], why:'Shock from cortisol deficiency: hydrocortisone now.'},
    look:{mouth:['pigment'], nails:['creases']},
    approach:[A('Hypotension not responding to fluids + GI symptoms → think adrenal crisis.'), A('Clues: hyperpigmentation, autoimmune history.','ex:skin','hx:pmh'), A('Draw cortisol/ACTH, then hydrocortisone immediately.','test:cortisol'), A('Electrolytes and glucose.','test:cmp','test:fsg')]},
  ida:{care:'Outpatient', target:{min:21000, cost:4000}, acuity:{level:'soon', partial:['routine'], why:'Stable anemia, but suspected colon cancer → expedited colonoscopy within weeks.'},
    look:{mouth:['glossitis','angular','pale'], nails:['koilonychia','pale']},
    approach:[A('Confirm microcytic anemia and iron deficiency (ferritin).','test:cbc','test:iron'), A('GI history: stool changes, weight loss, family history.','hx:gi','hx:wt'), A('Rectal exam with guaiac.','ex:rectal'), A('Colonoscopy (± EGD) for every older adult with IDA.','test:colo'), A('Stage, resect, replace iron.')]},
  ttp:{care:'ED', acuity:{level:'now', partial:['admit'], why:'TTP is fatal without plasma exchange: start emergently.'},
    look:{mouth:['petechiae']},
    approach:[A('Thrombocytopenia + anemia → look at the smear.','test:cbc','test:smear'), A('Hemolysis labs and coags (TTP vs DIC).','test:hemol','test:pt'), A('PLASMIC score; send ADAMTS13 but don’t wait.','test:adamts'), A('Plasma exchange + steroids. No platelets.')]},
  hit:{care:'Inpatient', acuity:{level:'admit', partial:['now'], why:'HIT with thrombosis: change anticoagulants today.'},
    look:{marks:['sternotomy']},
    exam:{skin:'Healing midline sternotomy scar. A dark, necrotic patch at a heparin injection site on the abdomen.'},
    approach:[A('Platelet drop 5–10 days after heparin → 4Ts score.','hx:meds','test:cbc'), A('Stop all heparin and start an alternative before results.'), A('PF4 ELISA, then SRA.','test:pf4'), A('Look for thrombosis.','ex:legs','test:duplex')]},
  myeloma:{care:'Inpatient', acuity:{level:'admit', partial:['soon'], why:'Ca 13.1 with confusion and AKI: inpatient hydration; myeloma therapy follows.'},
    approach:[A('Hypercalcemia + AKI + anemia + back pain → CRAB.','test:cmp','test:cbc'), A('PTH to separate PTH-mediated from malignancy.','test:pth'), A('SPEP/IFE/free light chains; smear.','test:spep','test:smear'), A('Skeletal survey and marrow biopsy.','test:skel','test:bmbx'), A('Fluids, bisphosphonate, hematology.')]},
  chestsyndrome:{care:'Inpatient', acuity:{level:'admit', partial:['now'], why:'Acute chest syndrome: inpatient antibiotics, O₂, transfusion; ICU if worsening.'},
    approach:[A('New chest symptoms in sickle cell disease → CXR.','ex:lungR','test:cxr'), A('Hemoglobin vs baseline and retic.','test:cbc'), A('Oxygenation (blood gas).','test:abg'), A('Antibiotics, O₂, incentive spirometry, transfusion.')]},
  urosepsis:{care:'ED', acuity:{level:'now', partial:['admit'], why:'Septic shock: antibiotics, fluids, pressors, and source control now.'},
    approach:[A('Recognize septic shock: hypotension and lactate.','test:lactate'), A('Cultures, then antibiotics within 1 h; 30 mL/kg fluids.','test:bcx'), A('UA for the source; CVA tenderness.','test:ua','ex:back'), A('Image for obstruction (CT or renal US).','test:ctabd','test:us_renal'), A('Pressors and urgent decompression.')]},
  meningitis:{care:'ED', acuity:{level:'now', partial:[], why:'Bacterial meningitis: antibiotics within minutes.'},
    approach:[A('Fever, headache, stiff neck, confusion → antibiotics now.','ex:neck'), A('Blood cultures, then ceftriaxone + vancomycin + dexamethasone.','test:bcx'), A('CT before LP only if altered, focal, papilledema, seizure, or immunocompromised.','test:cthead'), A('LP: cells, glucose, protein, Gram stain.','test:lp'), A('Droplet precautions; contact prophylaxis.')]},
  endocarditis:{care:'Inpatient', acuity:{level:'admit', partial:['now'], why:'Bacteremic endocarditis: weeks of IV antibiotics in hospital.'},
    look:{nails:['splinter']},
    approach:[A('Fever + injection drug use → endocarditis until proven otherwise.','hx:etoh'), A('Murmur and peripheral stigmata.','ex:heart','ex:hands'), A('Three sets of blood cultures before antibiotics.','test:bcx'), A('Echocardiogram.','test:tte'), A('Weeks of IV antibiotics; treat the addiction.')]},
  pjp:{care:'Inpatient', acuity:{level:'admit', partial:['now'], why:'Hypoxemic PJP: inpatient TMP-SMX and steroids.'},
    look:{mouth:['thrush']},
    approach:[A('Subacute hypoxemia + HIV risk → PJP.','hx:sex'), A('Thrush and other AIDS clues.','ex:heent'), A('HIV test, CD4, ABG.','test:hiv','test:cd4','test:abg'), A('Induced sputum for Pneumocystis; exclude TB.','test:isputum','test:afb'), A('TMP-SMX + steroids; ART within 2 weeks.')]},
  gout:{care:'ED', acuity:{level:'soon', partial:['routine'], why:'Treat the flare today and follow up as an outpatient. No admission.'},
    look:{gait:'antalgic'},
    exam:{gait:'Limps, keeping weight off the right forefoot.'},
    approach:[A('Acute monoarthritis → aspirate to exclude infection and see crystals.','ex:joints','test:arthro'), A('Kidney function before choosing a drug.','test:cmp'), A('Triggers: thiazides, alcohol, diet.','hx:meds','hx:etoh'), A('Treat the flare; plan urate-lowering therapy.')]},
  sle:{care:'Inpatient', acuity:{level:'admit', partial:['soon'], why:'Active nephritis with AKI: pulse steroids and biopsy.'},
    look:{mouth:['palatalUlcers']},
    approach:[A('Multisystem history and exam: rash, ulcers, joints, edema.','ex:skin','ex:heent','ex:hands'), A('UA and sediment for glomerulonephritis.','test:ua','test:ursed'), A('ANA, then dsDNA/Smith and complements.','test:auto','test:lupus'), A('Renal biopsy to classify the nephritis.','test:renalbx'), A('Steroids + MMF or cyclophosphamide + hydroxychloroquine.')]},
  gca:{care:'ED', acuity:{level:'admit', partial:['now','soon'], why:'Visual symptoms: high-dose steroids today; don’t wait for biopsy.'},
    approach:[A('New headache over 50 with jaw claudication or vision change → GCA.','hx:hpi'), A('Temporal artery exam.','ex:heent'), A('ESR/CRP.','test:esr'), A('Steroids immediately, biopsy within 1–2 weeks.','test:tab')]},
  stroke:{care:'ED', acuity:{level:'now', partial:[], why:'Inside the thrombolysis window: door-to-needle < 60 minutes.'},
    look:{gait:'unable'},
    approach:[A('Last known well, and check glucose.','hx:hpi','test:fsg'), A('NIHSS exam.','ex:neuro'), A('Noncontrast CT to exclude hemorrhage.','test:cthead'), A('CTA for large-vessel occlusion.','test:ctahead'), A('Thrombolysis within 4.5 h; thrombectomy for LVO.')]},
  mg:{care:'Inpatient', acuity:{level:'now', partial:['admit'], why:'Impending respiratory failure: ICU and elective intubation.'},
    look:{gait:'unable'},
    approach:[A('Bulbar and respiratory weakness in MG → measure NIF and VC.','test:nif'), A('Find the trigger (fluoroquinolone).','hx:meds'), A('ICU; intubate electively at thresholds.'), A('PLEX or IVIG; stop offending drugs.')]},
  apap:{care:'ED', acuity:{level:'admit', partial:['now'], why:'Looks well, but needs NAC now and psychiatric care: admit.'},
    approach:[A('Time and amount of ingestion.','hx:hpi'), A('4-hour (or later) level on the nomogram.','test:apap'), A('Co-ingestants: salicylate, ECG.','test:sal','test:ecg'), A('Baseline LFTs and INR.','test:cmp','test:pt'), A('NAC within 8 h; psychiatry.')]},
};
for(const c of CASES){
  const t = TEACH[c.id];
  if(t){
    c.care = c.care || t.care; c.acuity = c.acuity || t.acuity; c.approach = c.approach || t.approach;
    if(t.target) c.target = t.target;
    if(t.look) Object.assign(c.look, t.look);
    if(t.exam) Object.assign(c.exam, t.exam);
  }
  // gait: explicit, or unable to walk if critically ill
  if(!c.look.gait) c.look.gait = (c.acuity && c.acuity.level==='now') || c.look.o2==='mask' ? 'unable' : 'normal';
  if(!c.exam.gait) c.exam.gait = GAIT_DEFAULT[c.look.gait] || GAIT_DEFAULT.normal;
}
